// This file was automatically generated.  Do not modify.

'use strict';

const messages = Object.create(null);

messages["ADD_COMMENT"] = "Дадаць камэнтар";
messages["CANNOT_DELETE_VARIABLE_PROCEDURE"] = "Немагчыма выдаліць зьменную «%1», таму што яна зьяўляецца часткай вызначэньня функцыі «%2»";
messages["CHANGE_VALUE_TITLE"] = "Зьмяніць значэньне:";
messages["CLEAN_UP"] = "Ачысьціць блёкі";
messages["COLLAPSED_WARNINGS_WARNING"] = "Згорнутыя блёкі ўтрымліваюць папярэджаньні.";
messages["COLLAPSE_ALL"] = "Згарнуць блёкі";
messages["COLLAPSE_BLOCK"] = "Згарнуць блёк";
messages["COLOUR_BLEND_COLOUR1"] = "колер 1";
messages["COLOUR_BLEND_COLOUR2"] = "колер 2";
messages["COLOUR_BLEND_HELPURL"] = "https://meyerweb.com/eric/tools/color-blend/#:::rgbp";  // untranslated
messages["COLOUR_BLEND_RATIO"] = "дзеля";
messages["COLOUR_BLEND_TITLE"] = "зьмяшаць";
messages["COLOUR_BLEND_TOOLTIP"] = "Зьмешвае два колеры ў дадзенай прапорцыі (0.0 — 1.0)";
messages["COLOUR_PICKER_HELPURL"] = "https://be-x-old.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BB%D0%B5%D1%80";
messages["COLOUR_PICKER_TOOLTIP"] = "Абярыце колер з палітры.";
messages["COLOUR_RANDOM_HELPURL"] = "http://randomcolour.com";  // untranslated
messages["COLOUR_RANDOM_TITLE"] = "выпадковы колер";
messages["COLOUR_RANDOM_TOOLTIP"] = "Абраць выпадковы колер.";
messages["COLOUR_RGB_BLUE"] = "сіняга";
messages["COLOUR_RGB_GREEN"] = "зялёнага";
messages["COLOUR_RGB_HELPURL"] = "https://www.december.com/html/spec/colorpercompact.html";  // untranslated
messages["COLOUR_RGB_RED"] = "чырвонага";
messages["COLOUR_RGB_TITLE"] = "колер з";
messages["COLOUR_RGB_TOOLTIP"] = "Стварыць колер з абранымі прапорцыямі чырвонага, зялёнага і сіняга. Усе значэньні павінны быць ад 0 да 100.";
messages["CONTROLS_FLOW_STATEMENTS_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
messages["CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK"] = "перарваць цыкль";
messages["CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE"] = "працягнуць з наступнага кроку цыклю";
messages["CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK"] = "Спыніць гэты цыкль.";
messages["CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE"] = "Прапусьціць рэшту цыклю і перайсьці да наступнага кроку.";
messages["CONTROLS_FLOW_STATEMENTS_WARNING"] = "Увага: гэты блёк можа быць выкарыстаны толькі ў цыклі.";
messages["CONTROLS_FOREACH_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
messages["CONTROLS_FOREACH_TITLE"] = "для кожнага элемэнта %1 у сьпісе %2";
messages["CONTROLS_FOREACH_TOOLTIP"] = "Для кожнага элемэнту сьпісу прысвойвае зьменнай '%1' ягонае значэньне і выконвае пэўныя апэрацыі.";
messages["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
messages["CONTROLS_FOR_TITLE"] = "лічыць з %1 ад %2 да %3 па %4";
messages["CONTROLS_FOR_TOOLTIP"] = "Прысвойвае зьменнай \"%1\" значэньні ад пачатковага да канчатковага значэньня, улічваючы зададзены крок, і выконвае абраныя блёкі.";
messages["CONTROLS_IF_ELSEIF_TOOLTIP"] = "Дадаць умову да блёку «калі».";
messages["CONTROLS_IF_ELSE_TOOLTIP"] = "Дадаць заключную ўмову для ўсіх астатніх варыянтаў блёку «калі».";
messages["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
messages["CONTROLS_IF_IF_TOOLTIP"] = "Дадаць, выдаліць ці пераставіць сэкцыі для пераканфігураваньня гэтага блёку «калі».";
messages["CONTROLS_IF_MSG_ELSE"] = "інакш";
messages["CONTROLS_IF_MSG_ELSEIF"] = "інакш, калі";
messages["CONTROLS_IF_MSG_IF"] = "калі";
messages["CONTROLS_IF_TOOLTIP_1"] = "Калі значэньне ісьціна, выканаць пэўныя апэрацыі.";
messages["CONTROLS_IF_TOOLTIP_2"] = "Калі значэньне ісьціна, выканаць першы блёк апэрацыяў, інакш выканаць другі блёк.";
messages["CONTROLS_IF_TOOLTIP_3"] = "Калі першае значэньне ісьціна, выканаць першы блёк апэрацыяў. Інакш, калі другое значэньне ісьціна, выканаць другі блёк апэрацыяў.";
messages["CONTROLS_IF_TOOLTIP_4"] = "Калі першае значэньне ісьціна, выканаць першы блёк апэрацыяў. Інакш, калі другое значэньне ісьціна, выканаць другі блёк апэрацыяў. Калі ніводнае з значэньняў не сапраўднае, выканаць апошні блёк апэрацыяў.";
messages["CONTROLS_REPEAT_HELPURL"] = "https://en.wikipedia.org/wiki/For_loop";
messages["CONTROLS_REPEAT_INPUT_DO"] = "выканаць";
messages["CONTROLS_REPEAT_TITLE"] = "паўтарыць %1 раз(ы)";
messages["CONTROLS_REPEAT_TOOLTIP"] = "Выконвае апэрацыі некалькі разоў.";
messages["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
messages["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "паўтараць, пакуль не";
messages["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "паўтараць, пакуль";
messages["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "Пакуль значэньне хлусьня, выконваць пэўныя апэрацыі.";
messages["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "Пакуль значэньне ісьціна, выконваць пэўныя апэрацыі.";
messages["DELETE_ALL_BLOCKS"] = "Выдаліць усе блёкі %1?";
messages["DELETE_BLOCK"] = "Выдаліць блёк";
messages["DELETE_VARIABLE"] = "Выдаліць зьменную «%1»";
messages["DELETE_VARIABLE_CONFIRMATION"] = "Выдаліць %1 выкарыстаньняў зьменнай «%2»?";
messages["DELETE_X_BLOCKS"] = "Выдаліць %1 блёкі";
messages["DIALOG_CANCEL"] = "Скасаваць";
messages["DIALOG_OK"] = "OK";
messages["DISABLE_BLOCK"] = "Адключыць блёк";
messages["DUPLICATE_BLOCK"] = "Капіяваць";
messages["DUPLICATE_COMMENT"] = "Прадубляваць камэнтар";
messages["ENABLE_BLOCK"] = "Уключыць блёк";
messages["EXPAND_ALL"] = "Разгарнуць блёкі";
messages["EXPAND_BLOCK"] = "Разгарнуць блёк";
messages["EXTERNAL_INPUTS"] = "Зьнешнія ўваходы";
messages["HELP"] = "Дапамога";
messages["INLINE_INPUTS"] = "Унутраныя ўваходы";
messages["LISTS_CREATE_EMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
messages["LISTS_CREATE_EMPTY_TITLE"] = "стварыць пусты сьпіс";
messages["LISTS_CREATE_EMPTY_TOOLTIP"] = "Вяртае сьпіс даўжынёй 0, які ня ўтрымлівае запісаў зьвестак";
messages["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "сьпіс";
messages["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "Дадаць, выдаліць ці пераставіць сэкцыі для пераканфігураваньня гэтага блёку.";
messages["LISTS_CREATE_WITH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
messages["LISTS_CREATE_WITH_INPUT_WITH"] = "стварыць сьпіс з";
messages["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "Дадаць элемэнт да сьпісу.";
messages["LISTS_CREATE_WITH_TOOLTIP"] = "Ставарае сьпіс зь любой колькасьцю элемэнтаў.";
messages["LISTS_GET_INDEX_FIRST"] = "першы";
messages["LISTS_GET_INDEX_FROM_END"] = "№ з канца";
messages["LISTS_GET_INDEX_FROM_START"] = "#";  // untranslated
messages["LISTS_GET_INDEX_GET"] = "атрымаць";
messages["LISTS_GET_INDEX_GET_REMOVE"] = "атрымаць і выдаліць";
messages["LISTS_GET_INDEX_LAST"] = "апошні";
messages["LISTS_GET_INDEX_RANDOM"] = "выпадковы";
messages["LISTS_GET_INDEX_REMOVE"] = "выдаліць";
messages["LISTS_GET_INDEX_TAIL"] = "";  // untranslated
messages["LISTS_GET_INDEX_TOOLTIP_GET_FIRST"] = "Вяртае першы элемэнт у сьпісе.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_FROM"] = "Вяртае элемэнт у пазначанай пазыцыі ў сьпісе.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_LAST"] = "Вяртае апошні элемэнт у сьпісе.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_RANDOM"] = "Вяртае выпадковы элемэнт у сьпісе.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST"] = "Выдаляе і вяртае першы элемэнт у сьпісе.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM"] = "Выдаляе і вяртае элемэнт у пазначанай пазыцыі ў сьпісе.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST"] = "Выдаляе і вяртае апошні элемэнт у сьпісе.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM"] = "Выдаляе і вяртае выпадковы элемэнт у сьпісе.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST"] = "Выдаляе першы элемэнт у сьпісе.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM"] = "Выдаляе элемэнт у пазначанай пазыцыі ў сьпісе.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST"] = "Выдаляе апошні элемэнт у сьпісе.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM"] = "Выдаляе выпадковы элемэнт у сьпісе.";
messages["LISTS_GET_SUBLIST_END_FROM_END"] = "па № з канца";
messages["LISTS_GET_SUBLIST_END_FROM_START"] = "да #";
messages["LISTS_GET_SUBLIST_END_LAST"] = "да апошняга";
messages["LISTS_GET_SUBLIST_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
messages["LISTS_GET_SUBLIST_START_FIRST"] = "атрымаць падсьпіс зь першага";
messages["LISTS_GET_SUBLIST_START_FROM_END"] = "атрымаць падсьпіс з № з канца";
messages["LISTS_GET_SUBLIST_START_FROM_START"] = "атрымаць падсьпіс з №";
messages["LISTS_GET_SUBLIST_TAIL"] = "";  // untranslated
messages["LISTS_GET_SUBLIST_TOOLTIP"] = "Стварае копію пазначанай часткі сьпісу.";
messages["LISTS_INDEX_FROM_END_TOOLTIP"] = "№%1 — апошні элемэнт.";
messages["LISTS_INDEX_FROM_START_TOOLTIP"] = "№%1 — першы элемэнт.";
messages["LISTS_INDEX_OF_FIRST"] = "знайсьці першае ўваходжаньне элемэнту";
messages["LISTS_INDEX_OF_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
messages["LISTS_INDEX_OF_LAST"] = "знайсьці апошняе ўваходжаньне элемэнту";
messages["LISTS_INDEX_OF_TOOLTIP"] = "Вяртае індэкс першага/апошняга ўваходжаньня элемэнту ў сьпіс. Вяртае %1, калі элемэнт ня знойдзены.";
messages["LISTS_INLIST"] = "у сьпісе";
messages["LISTS_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
messages["LISTS_ISEMPTY_TITLE"] = "%1 пусты";
messages["LISTS_ISEMPTY_TOOLTIP"] = "Вяртае значэньне ісьціна, калі сьпіс пусты.";
messages["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
messages["LISTS_LENGTH_TITLE"] = "даўжыня %1";
messages["LISTS_LENGTH_TOOLTIP"] = "Вяртае даўжыню сьпісу.";
messages["LISTS_REPEAT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
messages["LISTS_REPEAT_TITLE"] = "стварыць сьпіс з элемэнту %1, які паўтараецца %2 разоў";
messages["LISTS_REPEAT_TOOLTIP"] = "Стварае сьпіс, які ўтрымлівае пададзеную колькасьць копіяў элемэнту.";
messages["LISTS_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";
messages["LISTS_REVERSE_MESSAGE0"] = "адваротна %1";
messages["LISTS_REVERSE_TOOLTIP"] = "Зьмяняе парадак копіі сьпісу на адваротны.";
messages["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
messages["LISTS_SET_INDEX_INPUT_TO"] = "як";
messages["LISTS_SET_INDEX_INSERT"] = "уставіць у";
messages["LISTS_SET_INDEX_SET"] = "усталяваць";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST"] = "Устаўляе элемэнт у пачатак сьпісу.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_FROM"] = "Устаўляе элемэнт у пазначанай пазыцыі ў сьпісе.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_LAST"] = "Дадае элемэнт у канец сьпісу.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM"] = "Выпадковым чынам устаўляе элемэнт у сьпіс.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_FIRST"] = "Задае першы элемэнт у сьпісе.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_FROM"] = "Задае элемэнт у пазначанай пазыцыі ў сьпісе.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_LAST"] = "Задае апошні элемэнт у сьпісе.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_RANDOM"] = "Задае выпадковы элемэнт у сьпісе.";
messages["LISTS_SORT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
messages["LISTS_SORT_ORDER_ASCENDING"] = "па павелічэньні";
messages["LISTS_SORT_ORDER_DESCENDING"] = "па зьмяншэньні";
messages["LISTS_SORT_TITLE"] = "сартаваць %1 %2 %3";
messages["LISTS_SORT_TOOLTIP"] = "Сартаваць копію сьпісу.";
messages["LISTS_SORT_TYPE_IGNORECASE"] = "паводле альфабэту, ігнараваць рэгістар";
messages["LISTS_SORT_TYPE_NUMERIC"] = "як лікі";
messages["LISTS_SORT_TYPE_TEXT"] = "паводле альфабэту";
messages["LISTS_SPLIT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
messages["LISTS_SPLIT_LIST_FROM_TEXT"] = "стварыць сьпіс з тэксту";
messages["LISTS_SPLIT_TEXT_FROM_LIST"] = "стварыць тэкст са сьпісу";
messages["LISTS_SPLIT_TOOLTIP_JOIN"] = "Аб’ядноўвае сьпіс тэкстаў у адзін тэкст па падзяляльніках.";
messages["LISTS_SPLIT_TOOLTIP_SPLIT"] = "Падзяліць тэкст у сьпіс тэкстаў, па падзяляльніках.";
messages["LISTS_SPLIT_WITH_DELIMITER"] = "з падзяляльнікам";
messages["LOGIC_BOOLEAN_FALSE"] = "хлусьня";
messages["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
messages["LOGIC_BOOLEAN_TOOLTIP"] = "Вяртае «ісьціна» ці «хлусьня».";
messages["LOGIC_BOOLEAN_TRUE"] = "ісьціна";
messages["LOGIC_COMPARE_HELPURL"] = "https://be-x-old.wikipedia.org/wiki/%D0%9D%D1%8F%D1%80%D0%BE%D1%9E%D0%BD%D0%B0%D1%81%D1%8C%D1%86%D1%8C";
messages["LOGIC_COMPARE_TOOLTIP_EQ"] = "Вяртае «ісьціна», калі абодва ўводы роўныя.";
messages["LOGIC_COMPARE_TOOLTIP_GT"] = "Вяртае «ісьціна», калі першы ўвод большы за другі.";
messages["LOGIC_COMPARE_TOOLTIP_GTE"] = "Вяртае «ісьціна», калі першы ўвод большы ці роўны другому.";
messages["LOGIC_COMPARE_TOOLTIP_LT"] = "Вяртае «ісьціна», калі першы ўвод меншы за другі.";
messages["LOGIC_COMPARE_TOOLTIP_LTE"] = "Вяртае «ісьціна», калі першы ўвод меншы ці роўны другому.";
messages["LOGIC_COMPARE_TOOLTIP_NEQ"] = "Вяртае «ісьціна», калі абодва ўводы ня роўныя.";
messages["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
messages["LOGIC_NEGATE_TITLE"] = "не %1";
messages["LOGIC_NEGATE_TOOLTIP"] = "Вяртае «ісьціна», калі ўвод непраўдзівы. Вяртае «хлусьня», калі ўвод праўдзівы.";
messages["LOGIC_NULL"] = "нічога";
messages["LOGIC_NULL_HELPURL"] = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
messages["LOGIC_NULL_TOOLTIP"] = "Вяртае нічога.";
messages["LOGIC_OPERATION_AND"] = "і";
messages["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
messages["LOGIC_OPERATION_OR"] = "ці";
messages["LOGIC_OPERATION_TOOLTIP_AND"] = "Вяртае «ісьціна», калі абодва ўводы праўдзівыя.";
messages["LOGIC_OPERATION_TOOLTIP_OR"] = "Вяртае «ісьціна», калі прынамсі адзін з уводаў праўдзівы.";
messages["LOGIC_TERNARY_CONDITION"] = "тэст";
messages["LOGIC_TERNARY_HELPURL"] = "https://en.wikipedia.org/wiki/%3F:";  // untranslated
messages["LOGIC_TERNARY_IF_FALSE"] = "калі хлусьня";
messages["LOGIC_TERNARY_IF_TRUE"] = "калі ісьціна";
messages["LOGIC_TERNARY_TOOLTIP"] = "Праверыць умову ў 'тэст'. Калі ўмова праўдзівая, будзе вернутае значэньне «калі ісьціна»; інакш будзе вернутае «калі хлусьня».";
messages["MATH_ADDITION_SYMBOL"] = "+";  // untranslated
messages["MATH_ARITHMETIC_HELPURL"] = "https://be-x-old.wikipedia.org/wiki/%D0%90%D1%80%D1%8B%D1%82%D0%BC%D1%8D%D1%82%D1%8B%D0%BA%D0%B0";
messages["MATH_ARITHMETIC_TOOLTIP_ADD"] = "Вяртае суму двух лікаў.";
messages["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "Вяртае дзель двух лікаў.";
messages["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "Вяртае рознасьць двух лікаў.";
messages["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "Вяртае здабытак двух лікаў.";
messages["MATH_ARITHMETIC_TOOLTIP_POWER"] = "Вяртае першы лік у ступені другога ліку.";
messages["MATH_ATAN2_HELPURL"] = "https://en.wikipedia.org/wiki/Atan2";
messages["MATH_ATAN2_TITLE"] = "atan2 ад X:%1 Y:%2";
messages["MATH_ATAN2_TOOLTIP"] = "Вяртае арктангенс пункту (X, Y) у градусах ад -180 да 180.";
messages["MATH_CHANGE_HELPURL"] = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
messages["MATH_CHANGE_TITLE"] = "зьмяніць %1 на %2";
messages["MATH_CHANGE_TOOLTIP"] = "Дадае лічбу да зьменнай '%1'.";
messages["MATH_CONSTANT_HELPURL"] = "https://be-x-old.wikipedia.org/wiki/%D0%9C%D0%B0%D1%82%D1%8D%D0%BC%D0%B0%D1%82%D1%8B%D1%87%D0%BD%D0%B0%D1%8F_%D0%BA%D0%B0%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B0";
messages["MATH_CONSTANT_TOOLTIP"] = "Вяртае адну з агульных канстантаў: π (3.141...), e (2.718...), φ (1.618...), sqrt(2) (1.414...), sqrt(½) (0,707...) або ∞ (бясконцасьць).";
messages["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
messages["MATH_CONSTRAIN_TITLE"] = "абмежаваць %1 зьнізу %2 зьверху %3";
messages["MATH_CONSTRAIN_TOOLTIP"] = "Абмяжоўвае колькасьць ніжняй і верхняй межамі (уключна).";
messages["MATH_DIVISION_SYMBOL"] = "÷";  // untranslated
messages["MATH_IS_DIVISIBLE_BY"] = "дзеліцца на";
messages["MATH_IS_EVEN"] = "парная";
messages["MATH_IS_NEGATIVE"] = "адмоўная";
messages["MATH_IS_ODD"] = "няпарная";
messages["MATH_IS_POSITIVE"] = "дадатная";
messages["MATH_IS_PRIME"] = "простая";
messages["MATH_IS_TOOLTIP"] = "Правярае, ці зьяўляецца лік парным, няпарным, простым, станоўчым, адмоўным, ці ён дзеліцца на пэўны лік без астатку. Вяртае значэньне ісьціна або няпраўда.";
messages["MATH_IS_WHOLE"] = "цэлая";
messages["MATH_MODULO_HELPURL"] = "https://en.wikipedia.org/wiki/Modulo_operation";
messages["MATH_MODULO_TITLE"] = "рэшта дзяленьня %1 ÷ %2";
messages["MATH_MODULO_TOOLTIP"] = "Вяртае рэшту дзяленьня двух лікаў.";
messages["MATH_MULTIPLICATION_SYMBOL"] = "×";  // untranslated
messages["MATH_NUMBER_HELPURL"] = "https://be-x-old.wikipedia.org/wiki/%D0%9B%D1%96%D0%BA";
messages["MATH_NUMBER_TOOLTIP"] = "Лік.";
messages["MATH_ONLIST_HELPURL"] = "";  // untranslated
messages["MATH_ONLIST_OPERATOR_AVERAGE"] = "сярэдняя ў сьпісе";
messages["MATH_ONLIST_OPERATOR_MAX"] = "мінімальная ў сьпісе";
messages["MATH_ONLIST_OPERATOR_MEDIAN"] = "мэдыяна сьпісу";
messages["MATH_ONLIST_OPERATOR_MIN"] = "мінімальная ў сьпісе";
messages["MATH_ONLIST_OPERATOR_MODE"] = "рэжымы сьпісу";
messages["MATH_ONLIST_OPERATOR_RANDOM"] = "выпадковы элемэнт сьпісу";
messages["MATH_ONLIST_OPERATOR_STD_DEV"] = "стандартнае адхіленьне сьпісу";
messages["MATH_ONLIST_OPERATOR_SUM"] = "Сума сьпісу";
messages["MATH_ONLIST_TOOLTIP_AVERAGE"] = "Вяртае сярэднеарытмэтычнае значэньне лікавых значэньняў у сьпісе.";
messages["MATH_ONLIST_TOOLTIP_MAX"] = "Вяртае найменшы лік у сьпісе.";
messages["MATH_ONLIST_TOOLTIP_MEDIAN"] = "Вяртае мэдыяну сьпісу.";
messages["MATH_ONLIST_TOOLTIP_MIN"] = "Вяртае найменшы лік у сьпісе.";
messages["MATH_ONLIST_TOOLTIP_MODE"] = "Вяртае сьпіс самых распаўсюджаных элемэнтаў у сьпісе.";
messages["MATH_ONLIST_TOOLTIP_RANDOM"] = "Вяртае выпадковы элемэнт сьпісу.";
messages["MATH_ONLIST_TOOLTIP_STD_DEV"] = "Вяртае стандартнае адхіленьне сьпісу.";
messages["MATH_ONLIST_TOOLTIP_SUM"] = "Вяртае суму ўсіх лікаў у сьпісе.";
messages["MATH_POWER_SYMBOL"] = "^";  // untranslated
messages["MATH_RANDOM_FLOAT_HELPURL"] = "https://en.wikipedia.org/wiki/Random_number_generation";
messages["MATH_RANDOM_FLOAT_TITLE_RANDOM"] = "выпадковая дроб";
messages["MATH_RANDOM_FLOAT_TOOLTIP"] = "Вяртае выпадковую дроб у дыяпазоне ад 0,0 (уключна) да 1,0.";
messages["MATH_RANDOM_INT_HELPURL"] = "https://en.wikipedia.org/wiki/Random_number_generation";
messages["MATH_RANDOM_INT_TITLE"] = "выпадковая цэлая з %1 для %2";
messages["MATH_RANDOM_INT_TOOLTIP"] = "Вяртае выпадковы цэлы лік паміж двума зададзенымі абмежаваньнямі ўключна.";
messages["MATH_ROUND_HELPURL"] = "https://en.wikipedia.org/wiki/Rounding";
messages["MATH_ROUND_OPERATOR_ROUND"] = "акругліць";
messages["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "акругліць да меншага";
messages["MATH_ROUND_OPERATOR_ROUNDUP"] = "акругліць да большага";
messages["MATH_ROUND_TOOLTIP"] = "Акругленьне ліку да большага ці меншага.";
messages["MATH_SINGLE_HELPURL"] = "https://be-x-old.wikipedia.org/wiki/%D0%9A%D0%B2%D0%B0%D0%B4%D1%80%D0%B0%D1%82%D0%BD%D1%8B_%D0%BA%D0%BE%D1%80%D0%B0%D0%BD%D1%8C";
messages["MATH_SINGLE_OP_ABSOLUTE"] = "модуль";
messages["MATH_SINGLE_OP_ROOT"] = "квадратны корань";
messages["MATH_SINGLE_TOOLTIP_ABS"] = "Вяртае модуль ліку.";
messages["MATH_SINGLE_TOOLTIP_EXP"] = "Вяртае e ў ступені ліку.";
messages["MATH_SINGLE_TOOLTIP_LN"] = "Вяртае натуральны лягарытм ліку.";
messages["MATH_SINGLE_TOOLTIP_LOG10"] = "Вяртае дзесятковы лягарытм ліку.";
messages["MATH_SINGLE_TOOLTIP_NEG"] = "Вяртае супрацьлеглы лік.";
messages["MATH_SINGLE_TOOLTIP_POW10"] = "Вяртае 10 у ступені ліку.";
messages["MATH_SINGLE_TOOLTIP_ROOT"] = "Вяртае квадратны корань ліку.";
messages["MATH_SUBTRACTION_SYMBOL"] = "-";  // untranslated
messages["MATH_TRIG_ACOS"] = "acos";  // untranslated
messages["MATH_TRIG_ASIN"] = "asin";  // untranslated
messages["MATH_TRIG_ATAN"] = "atan";  // untranslated
messages["MATH_TRIG_COS"] = "cos";  // untranslated
messages["MATH_TRIG_HELPURL"] = "https://be-x-old.wikipedia.org/wiki/%D0%A2%D1%80%D1%8B%D0%B3%D0%B0%D0%BD%D0%B0%D0%BC%D1%8D%D1%82%D1%80%D1%8B%D1%8F#.D0.A2.D1.80.D1.8B.D0.B3.D0.B0.D0.BD.D0.B0.D0.BC.D1.8D.D1.82.D1.80.D1.8B.D1.87.D0.BD.D1.8B.D1.8F_.D1.84.D1.83.D0.BD.D0.BA.D1.86.D1.8B.D1.96";
messages["MATH_TRIG_SIN"] = "sin";  // untranslated
messages["MATH_TRIG_TAN"] = "tan";  // untranslated
messages["MATH_TRIG_TOOLTIP_ACOS"] = "Вяртае арккосынус ліку.";
messages["MATH_TRIG_TOOLTIP_ASIN"] = "Вяртае арксынус ліку.";
messages["MATH_TRIG_TOOLTIP_ATAN"] = "Вяртае арктангэнс ліку.";
messages["MATH_TRIG_TOOLTIP_COS"] = "Вяртае косынус кута ў градусах.";
messages["MATH_TRIG_TOOLTIP_SIN"] = "Вяртае сынус кута ў градусах.";
messages["MATH_TRIG_TOOLTIP_TAN"] = "Вяртае тангэнс кута ў градусах.";
messages["NEW_COLOUR_VARIABLE"] = "Стварыць зьменную колеру…";
messages["NEW_NUMBER_VARIABLE"] = "Стварыць лікавую зьменную…";
messages["NEW_STRING_VARIABLE"] = "Стварыць радковую зьменную…";
messages["NEW_VARIABLE"] = "Стварыць зьменную…";
messages["NEW_VARIABLE_TITLE"] = "Імя новай зьменнай:";
messages["NEW_VARIABLE_TYPE_TITLE"] = "Новы тып зьменнай:";
messages["ORDINAL_NUMBER_SUFFIX"] = "";  // untranslated
messages["PROCEDURES_ALLOW_STATEMENTS"] = "дазволіць зацьвярджэньне";
messages["PROCEDURES_BEFORE_PARAMS"] = "з:";
messages["PROCEDURES_CALLNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
messages["PROCEDURES_CALLNORETURN_TOOLTIP"] = "Запусьціць функцыю вызначаную карыстальнікам '%1'.";
messages["PROCEDURES_CALLRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
messages["PROCEDURES_CALLRETURN_TOOLTIP"] = "Запусьціць функцыю вызначаную карыстальнікам '%1' і выкарыстаць яе вынік.";
messages["PROCEDURES_CALL_BEFORE_PARAMS"] = "з:";
messages["PROCEDURES_CREATE_DO"] = "Стварыць '%1'";
messages["PROCEDURES_DEFNORETURN_COMMENT"] = "Апішыце гэтую функцыю…";
messages["PROCEDURES_DEFNORETURN_DO"] = "";  // untranslated
messages["PROCEDURES_DEFNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
messages["PROCEDURES_DEFNORETURN_PROCEDURE"] = "зрабіць што-небудзь";
messages["PROCEDURES_DEFNORETURN_TITLE"] = "да";
messages["PROCEDURES_DEFNORETURN_TOOLTIP"] = "Стварае функцыю бяз выніку.";
messages["PROCEDURES_DEFRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
messages["PROCEDURES_DEFRETURN_RETURN"] = "вярнуць";
messages["PROCEDURES_DEFRETURN_TOOLTIP"] = "Стварае функцыю з вынікам.";
messages["PROCEDURES_DEF_DUPLICATE_WARNING"] = "Увага: гэтая функцыя мае парамэтры-дублікаты.";
messages["PROCEDURES_HIGHLIGHT_DEF"] = "Падсьвяціць вызначэньне функцыі";
messages["PROCEDURES_IFRETURN_HELPURL"] = "http://c2.com/cgi/wiki?GuardClause";
messages["PROCEDURES_IFRETURN_TOOLTIP"] = "Калі значэньне ісьціна, вярнуць другое значэньне.";
messages["PROCEDURES_IFRETURN_WARNING"] = "Папярэджаньне: гэты блёк можа выкарыстоўвацца толькі ў вызначанай функцыі.";
messages["PROCEDURES_MUTATORARG_TITLE"] = "назва парамэтру:";
messages["PROCEDURES_MUTATORARG_TOOLTIP"] = "Дадаць уваходныя парамэтры ў функцыю.";
messages["PROCEDURES_MUTATORCONTAINER_TITLE"] = "парамэтры";
messages["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "Дадаць, выдаліць ці запісаць чаргу ўваходных парамэтраў для гэтай функцыі.";
messages["REDO"] = "Паўтарыць";
messages["REMOVE_COMMENT"] = "Выдаліць камэнтар";
messages["RENAME_VARIABLE"] = "Перайменаваць зьменную…";
messages["RENAME_VARIABLE_TITLE"] = "Перайменаваць усе назвы зьменных '%1' на:";
messages["TEXT_APPEND_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
messages["TEXT_APPEND_TITLE"] = "да %1 дадаць тэкст %2";
messages["TEXT_APPEND_TOOLTIP"] = "Дадаць які-небудзь тэкст да зьменнай '%1'.";
messages["TEXT_CHANGECASE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
messages["TEXT_CHANGECASE_OPERATOR_LOWERCASE"] = "да ніжняга рэгістру";
messages["TEXT_CHANGECASE_OPERATOR_TITLECASE"] = "Вялікія Першыя Літары";
messages["TEXT_CHANGECASE_OPERATOR_UPPERCASE"] = "да ВЕРХНЯГА РЭГІСТРУ";
messages["TEXT_CHANGECASE_TOOLTIP"] = "Вярнуць копію тэксту зь іншай велічынёй літар.";
messages["TEXT_CHARAT_FIRST"] = "узяць першую літару";
messages["TEXT_CHARAT_FROM_END"] = "узяць літару № з канца";
messages["TEXT_CHARAT_FROM_START"] = "узяць літару №";
messages["TEXT_CHARAT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
messages["TEXT_CHARAT_LAST"] = "узяць апошнюю літару";
messages["TEXT_CHARAT_RANDOM"] = "узяць выпадковую літару";
messages["TEXT_CHARAT_TAIL"] = "";  // untranslated
messages["TEXT_CHARAT_TITLE"] = "у тэксьце %1 %2";
messages["TEXT_CHARAT_TOOLTIP"] = "Вяртае літару ў пазначанай пазыцыі.";
messages["TEXT_COUNT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#counting-substrings";
messages["TEXT_COUNT_MESSAGE0"] = "падлічыць %1 сярод %2";
messages["TEXT_COUNT_TOOLTIP"] = "Падлічвае колькі разоў нейкі тэкст сустракаецца ўнутры нейкага іншага тэксту.";
messages["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "Дадаць элемэнт да тэксту.";
messages["TEXT_CREATE_JOIN_TITLE_JOIN"] = "далучыць";
messages["TEXT_CREATE_JOIN_TOOLTIP"] = "Дадайце, выдаліце ці зьмяніце парадак разьдзелаў для перадачы тэкставага блёку.";
messages["TEXT_GET_SUBSTRING_END_FROM_END"] = "да літары № з канца";
messages["TEXT_GET_SUBSTRING_END_FROM_START"] = "да літары №";
messages["TEXT_GET_SUBSTRING_END_LAST"] = "да апошняй літары";
messages["TEXT_GET_SUBSTRING_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
messages["TEXT_GET_SUBSTRING_INPUT_IN_TEXT"] = "у тэксьце";
messages["TEXT_GET_SUBSTRING_START_FIRST"] = "атрымаць падрадок зь першай літары";
messages["TEXT_GET_SUBSTRING_START_FROM_END"] = "узяць падрадок зь літары № з канца";
messages["TEXT_GET_SUBSTRING_START_FROM_START"] = "узяць падрадок зь літары №";
messages["TEXT_GET_SUBSTRING_TAIL"] = "";  // untranslated
messages["TEXT_GET_SUBSTRING_TOOLTIP"] = "Вяртае пазначаную частку тэксту.";
messages["TEXT_INDEXOF_HELPURL"] = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
messages["TEXT_INDEXOF_OPERATOR_FIRST"] = "знайсьці першае ўваходжаньне тэксту";
messages["TEXT_INDEXOF_OPERATOR_LAST"] = "знайсьці апошняе ўваходжаньне тэксту";
messages["TEXT_INDEXOF_TITLE"] = "у тэксьце %1 %2 %3";
messages["TEXT_INDEXOF_TOOLTIP"] = "Вяртае індэкс першага/апошняга ўваходжаньня першага тэксту ў другі тэкст. Вяртае %1, калі тэкст ня знойдзены.";
messages["TEXT_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
messages["TEXT_ISEMPTY_TITLE"] = "%1 пусты";
messages["TEXT_ISEMPTY_TOOLTIP"] = "Вяртае значэньне ісьціна, калі тэкст пусты.";
messages["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
messages["TEXT_JOIN_TITLE_CREATEWITH"] = "стварыць тэкст з";
messages["TEXT_JOIN_TOOLTIP"] = "Стварае фрагмэнт тэксту аб’яднаньнем любой колькасьці элемэнтаў.";
messages["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
messages["TEXT_LENGTH_TITLE"] = "даўжыня %1";
messages["TEXT_LENGTH_TOOLTIP"] = "Вяртае колькасьць літараў (у тым ліку прабелы) у пададзеным тэксьце.";
messages["TEXT_PRINT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
messages["TEXT_PRINT_TITLE"] = "друкаваць %1";
messages["TEXT_PRINT_TOOLTIP"] = "Надрукаваць пазначаны тэкст, лічбу ці іншыя сымбалі.";
messages["TEXT_PROMPT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
messages["TEXT_PROMPT_TOOLTIP_NUMBER"] = "Запытаць у карыстальніка лічбу.";
messages["TEXT_PROMPT_TOOLTIP_TEXT"] = "Запытаць у карыстальніка тэкст.";
messages["TEXT_PROMPT_TYPE_NUMBER"] = "запытаць лічбу з падказкай";
messages["TEXT_PROMPT_TYPE_TEXT"] = "запытаць тэкст з падказкай";
messages["TEXT_REPLACE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#replacing-substrings";
messages["TEXT_REPLACE_MESSAGE0"] = "замяніць %1 на %2 у %3";
messages["TEXT_REPLACE_TOOLTIP"] = "Замяняе ўсе выпадкі нейкага тэксту на іншы тэкст.";
messages["TEXT_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#reversing-text";
messages["TEXT_REVERSE_MESSAGE0"] = "адваротна %1";
messages["TEXT_REVERSE_TOOLTIP"] = "Мяняе парадак сымбаляў у тэксьце на адваротны.";
messages["TEXT_TEXT_HELPURL"] = "https://en.wikipedia.org/wiki/String_(computer_science)";
messages["TEXT_TEXT_TOOLTIP"] = "Літара, слова ці радок тэксту.";
messages["TEXT_TRIM_HELPURL"] = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
messages["TEXT_TRIM_OPERATOR_BOTH"] = "абрэзаць прабелы з абодвух бакоў";
messages["TEXT_TRIM_OPERATOR_LEFT"] = "абрэзаць прабелы зь левага боку";
messages["TEXT_TRIM_OPERATOR_RIGHT"] = "абрэзаць прабелы з правага боку";
messages["TEXT_TRIM_TOOLTIP"] = "Вяртае копію тэксту з прабеламі, выдаленымі ад аднаго ці абодвух бакоў.";
messages["TODAY"] = "Сёньня";
messages["UNDO"] = "Скасаваць";
messages["UNNAMED_KEY"] = "безназоўны";
messages["VARIABLES_DEFAULT_NAME"] = "аб’ект";
messages["VARIABLES_GET_CREATE_SET"] = "Стварыць блёк «усталяваць %1»";
messages["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
messages["VARIABLES_GET_TOOLTIP"] = "Вяртае значэньне гэтай зьменнай.";
messages["VARIABLES_SET"] = "усталяваць %1 да %2";
messages["VARIABLES_SET_CREATE_GET"] = "Стварыць блёк «атрымаць %1»";
messages["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
messages["VARIABLES_SET_TOOLTIP"] = "Надаць гэтай зьменнай значэньне ўстаўкі.";
messages["VARIABLE_ALREADY_EXISTS"] = "Зьменная з назвай «%1» ужо існуе.";
messages["VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE"] = "Зьменная з назвай «%1» ужо існуе зь іншым тыпам: «%2».";
messages["WORKSPACE_ARIA_LABEL"] = "Працоўная прастора Blockly";
messages["WORKSPACE_COMMENT_DEFAULT_TEXT"] = "Напішыце што-небудзь…";
messages["CONTROLS_FOREACH_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_FOR_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = messages["CONTROLS_IF_MSG_ELSEIF"];
messages["CONTROLS_IF_ELSE_TITLE_ELSE"] = messages["CONTROLS_IF_MSG_ELSE"];
messages["CONTROLS_IF_IF_TITLE_IF"] = messages["CONTROLS_IF_MSG_IF"];
messages["CONTROLS_IF_MSG_THEN"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_WHILEUNTIL_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["LISTS_CREATE_WITH_ITEM_TITLE"] = messages["VARIABLES_DEFAULT_NAME"];
messages["LISTS_GET_INDEX_HELPURL"] = messages["LISTS_INDEX_OF_HELPURL"];
messages["LISTS_GET_INDEX_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_GET_SUBLIST_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_INDEX_OF_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_SET_INDEX_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["MATH_CHANGE_TITLE_ITEM"] = messages["VARIABLES_DEFAULT_NAME"];
messages["PROCEDURES_DEFRETURN_COMMENT"] = messages["PROCEDURES_DEFNORETURN_COMMENT"];
messages["PROCEDURES_DEFRETURN_DO"] = messages["PROCEDURES_DEFNORETURN_DO"];
messages["PROCEDURES_DEFRETURN_PROCEDURE"] = messages["PROCEDURES_DEFNORETURN_PROCEDURE"];
messages["PROCEDURES_DEFRETURN_TITLE"] = messages["PROCEDURES_DEFNORETURN_TITLE"];
messages["TEXT_APPEND_VARIABLE"] = messages["VARIABLES_DEFAULT_NAME"];
messages["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = messages["VARIABLES_DEFAULT_NAME"];

messages["MATH_HUE"] = "230";
messages["LOOPS_HUE"] = "120";
messages["LISTS_HUE"] = "260";
messages["LOGIC_HUE"] = "210";
messages["VARIABLES_HUE"] = "330";
messages["TEXTS_HUE"] = "160";
messages["PROCEDURES_HUE"] = "290";
messages["COLOUR_HUE"] = "20";
messages["VARIABLES_DYNAMIC_HUE"] = "310";