// This file was automatically generated.  Do not modify.

'use strict';

const messages = Object.create(null);

messages["ADD_COMMENT"] = "Přidat komentář";
messages["CANNOT_DELETE_VARIABLE_PROCEDURE"] = "Proměnnou '%1' není možné odstranit, protože je součástí definice funkce '%2'";
messages["CHANGE_VALUE_TITLE"] = "Změnit hodnotu:";
messages["CLEAN_UP"] = "Uspořádat bloky";
messages["COLLAPSED_WARNINGS_WARNING"] = "Collapsed blocks contain warnings.";  // untranslated
messages["COLLAPSE_ALL"] = "Sbalit bloky";
messages["COLLAPSE_BLOCK"] = "Sbalit blok";
messages["COLOUR_BLEND_COLOUR1"] = "barva 1";
messages["COLOUR_BLEND_COLOUR2"] = "barva 2";
messages["COLOUR_BLEND_HELPURL"] = "https://meyerweb.com/eric/tools/color-blend/#:::rgbp";  // untranslated
messages["COLOUR_BLEND_RATIO"] = "poměr";
messages["COLOUR_BLEND_TITLE"] = "smíchat";
messages["COLOUR_BLEND_TOOLTIP"] = "Smíchá dvě barvy v daném poměru (0.0–1.0).";
messages["COLOUR_PICKER_HELPURL"] = "https://cs.wikipedia.org/wiki/Barva";
messages["COLOUR_PICKER_TOOLTIP"] = "Vyberte barvu z palety.";
messages["COLOUR_RANDOM_HELPURL"] = "http://randomcolour.com";  // untranslated
messages["COLOUR_RANDOM_TITLE"] = "náhodná barva";
messages["COLOUR_RANDOM_TOOLTIP"] = "Zvolte barvu náhodně.";
messages["COLOUR_RGB_BLUE"] = "modrá";
messages["COLOUR_RGB_GREEN"] = "zelená";
messages["COLOUR_RGB_HELPURL"] = "https://www.december.com/html/spec/colorpercompact.html";  // untranslated
messages["COLOUR_RGB_RED"] = "červená";
messages["COLOUR_RGB_TITLE"] = "obarvěte barvou";
messages["COLOUR_RGB_TOOLTIP"] = "Vytvoř barvu se zadaným množstvím červené, zelené a modré.  Všechny hodnoty musí být mezi 0 a 100.";
messages["CONTROLS_FLOW_STATEMENTS_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
messages["CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK"] = "vyskočit ze smyčky";
messages["CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE"] = "pokračuj dalším opakováním smyčky";
messages["CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK"] = "Vyskoč z vnitřní smyčky.";
messages["CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE"] = "Přeskoč zbytek této smyčky a pokračuj dalším opakováním.";
messages["CONTROLS_FLOW_STATEMENTS_WARNING"] = "Upozornění: Tento blok může být použit pouze uvnitř smyčky.";
messages["CONTROLS_FOREACH_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
messages["CONTROLS_FOREACH_TITLE"] = "pro každou položku %1 v seznamu %2";
messages["CONTROLS_FOREACH_TOOLTIP"] = "Pro každou položku v seznamu nastavte do proměnné '%1' danou položku a proveďte nějaké operace.";
messages["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
messages["CONTROLS_FOR_TITLE"] = "počítat s %1 od %2 do %3 po %4";
messages["CONTROLS_FOR_TOOLTIP"] = "Nechá proměnnou '%1' nabývat hodnot od počátečního do koncového čísla po daném přírůstku a provádí příslušné bloky.";
messages["CONTROLS_IF_ELSEIF_TOOLTIP"] = "Přidat podmínku do \"pokud\" bloku.";
messages["CONTROLS_IF_ELSE_TOOLTIP"] = "Přidej konečnou podmínku zahrnující ostatní případy do bloku \"pokud\".";
messages["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
messages["CONTROLS_IF_IF_TOOLTIP"] = "Přidej, odstraň či uspořádej sekce k přenastavení tohoto bloku \"pokud\".";
messages["CONTROLS_IF_MSG_ELSE"] = "jinak";
messages["CONTROLS_IF_MSG_ELSEIF"] = "nebo pokud";
messages["CONTROLS_IF_MSG_IF"] = "pokud";
messages["CONTROLS_IF_TOOLTIP_1"] = "Je-li hodnota pravda, proveď určité příkazy.";
messages["CONTROLS_IF_TOOLTIP_2"] = "Je-li hodnota pravda, proveď první blok příkazů.  V opačném případě proveď druhý blok příkazů.";
messages["CONTROLS_IF_TOOLTIP_3"] = "Je-li první hodnota pravdivá, proveď první blok příkazů. V opačném případě, je-li pravdivá druhá hodnota, proveď druhý blok příkazů.";
messages["CONTROLS_IF_TOOLTIP_4"] = "Je-li první hodnota pravda, proveď první blok příkazů.  Je-li druhá hodnota pravda, proveď druhý blok příkazů.  Pokud žádná hodnota není pravda, proveď poslední blok příkazů.";
messages["CONTROLS_REPEAT_HELPURL"] = "https://cs.wikipedia.org/wiki/Cyklus_for";
messages["CONTROLS_REPEAT_INPUT_DO"] = "dělej";
messages["CONTROLS_REPEAT_TITLE"] = "opakuj %1 krát";
messages["CONTROLS_REPEAT_TOOLTIP"] = "Proveď určité příkazy několikrát.";
messages["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
messages["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "opakovat dokud";
messages["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "opakovat když";
messages["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "Dokud je hodnota nepravdivá, prováděj určité příkazy.";
messages["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "Dokud je hodnota pravdivá, prováděj určité příkazy.";
messages["DELETE_ALL_BLOCKS"] = "Smazat všech %1 bloků?";
messages["DELETE_BLOCK"] = "Smazat blok";
messages["DELETE_VARIABLE"] = "Odstranit proměnnou '%1'";
messages["DELETE_VARIABLE_CONFIRMATION"] = "Odstranit %1 použití proměnné '%2'";
messages["DELETE_X_BLOCKS"] = "Smazat %1 bloků";
messages["DIALOG_CANCEL"] = "Zrušit";
messages["DIALOG_OK"] = "OK";
messages["DISABLE_BLOCK"] = "Deaktivovat blok";
messages["DUPLICATE_BLOCK"] = "Duplikovat";
messages["DUPLICATE_COMMENT"] = "Duplikovat komentář";
messages["ENABLE_BLOCK"] = "Povolit blok";
messages["EXPAND_ALL"] = "Rozbalit bloky";
messages["EXPAND_BLOCK"] = "Rozbalit blok";
messages["EXTERNAL_INPUTS"] = "vnější vstupy";
messages["HELP"] = "Nápověda";
messages["INLINE_INPUTS"] = "Vložené vstupy";
messages["LISTS_CREATE_EMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
messages["LISTS_CREATE_EMPTY_TITLE"] = "vytvořit prázdný seznam";
messages["LISTS_CREATE_EMPTY_TOOLTIP"] = "Vrátí seznam nulové délky, který neobsahuje žádné datové záznamy";
messages["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "seznam";
messages["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "Přidat, odebrat nebo změnit pořadí oddílů tohoto seznamu bloku.";
messages["LISTS_CREATE_WITH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
messages["LISTS_CREATE_WITH_INPUT_WITH"] = "vytvořit seznam s";
messages["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "Přidat položku do seznamu.";
messages["LISTS_CREATE_WITH_TOOLTIP"] = "Vytvoř seznam s libovolným počtem položek.";
messages["LISTS_GET_INDEX_FIRST"] = "první";
messages["LISTS_GET_INDEX_FROM_END"] = "# od konce";
messages["LISTS_GET_INDEX_FROM_START"] = "#";
messages["LISTS_GET_INDEX_GET"] = "získat";
messages["LISTS_GET_INDEX_GET_REMOVE"] = "získat a odstranit";
messages["LISTS_GET_INDEX_LAST"] = "poslední";
messages["LISTS_GET_INDEX_RANDOM"] = "náhodné";
messages["LISTS_GET_INDEX_REMOVE"] = "odstranit";
messages["LISTS_GET_INDEX_TAIL"] = "";  // untranslated
messages["LISTS_GET_INDEX_TOOLTIP_GET_FIRST"] = "Vrátí první položku v seznamu.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_FROM"] = "Získá položku z určené pozice v seznamu.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_LAST"] = "Vrátí poslední položku v seznamu.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_RANDOM"] = "Vrátí náhodnou položku ze seznamu.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST"] = "Odstraní a vrátí první položku v seznamu.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM"] = "Odstraní a získá položku z určené pozice v seznamu.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST"] = "Odstraní a vrátí poslední položku v seznamu.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM"] = "Odstraní a vrátí náhodnou položku v seznamu.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST"] = "Odstraní první položku v seznamu.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM"] = "Odebere položku na konkrétním místě v seznamu.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST"] = "Odstraní poslední položku v seznamu.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM"] = "Odstraní náhodou položku v seznamu.";
messages["LISTS_GET_SUBLIST_END_FROM_END"] = "do # od konce";
messages["LISTS_GET_SUBLIST_END_FROM_START"] = "do #";
messages["LISTS_GET_SUBLIST_END_LAST"] = "jako poslední";
messages["LISTS_GET_SUBLIST_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
messages["LISTS_GET_SUBLIST_START_FIRST"] = "získat podseznam od první položky";
messages["LISTS_GET_SUBLIST_START_FROM_END"] = "získat podseznam od # od konce";
messages["LISTS_GET_SUBLIST_START_FROM_START"] = "získat podseznam od #";
messages["LISTS_GET_SUBLIST_TAIL"] = "";  // untranslated
messages["LISTS_GET_SUBLIST_TOOLTIP"] = "Vytvoří kopii určené části seznamu.";
messages["LISTS_INDEX_FROM_END_TOOLTIP"] = "%1 je poslední položka.";
messages["LISTS_INDEX_FROM_START_TOOLTIP"] = "%1 je první položka.";
messages["LISTS_INDEX_OF_FIRST"] = "najít první výskyt položky";
messages["LISTS_INDEX_OF_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
messages["LISTS_INDEX_OF_LAST"] = "najít poslední výskyt položky";
messages["LISTS_INDEX_OF_TOOLTIP"] = "Vrací index prvního/posledního výskytu položky v seznamu. Vrací %1, pokud položka nebyla nalezena.";
messages["LISTS_INLIST"] = "v seznamu";
messages["LISTS_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
messages["LISTS_ISEMPTY_TITLE"] = "%1 je prázdné";
messages["LISTS_ISEMPTY_TOOLTIP"] = "Vrátí hodnotu pravda, pokud je seznam prázdný.";
messages["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
messages["LISTS_LENGTH_TITLE"] = "délka %1";
messages["LISTS_LENGTH_TOOLTIP"] = "Vrací počet položek v seznamu.";
messages["LISTS_REPEAT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
messages["LISTS_REPEAT_TITLE"] = "vytvoř seznam s položkou %1 opakovanou %2 krát";
messages["LISTS_REPEAT_TOOLTIP"] = "Vytváří seznam obsahující danou hodnotu n-krát.";
messages["LISTS_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";  // untranslated
messages["LISTS_REVERSE_MESSAGE0"] = "reverse %1";  // untranslated
messages["LISTS_REVERSE_TOOLTIP"] = "Reverse a copy of a list.";  // untranslated
messages["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
messages["LISTS_SET_INDEX_INPUT_TO"] = "jako";
messages["LISTS_SET_INDEX_INSERT"] = "vložit na";
messages["LISTS_SET_INDEX_SET"] = "nastavit";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST"] = "Vložit položku na začátek seznamu.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_FROM"] = "Vloží položku na určenou pozici v seznamu.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_LAST"] = "Připojí položku na konec seznamu.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM"] = "Připojí položku náhodně do seznamu.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_FIRST"] = "Nastaví první položku v seznamu.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_FROM"] = "Nastaví položku na konkrétní místo v seznamu.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_LAST"] = "Nastaví poslední položku v seznamu.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_RANDOM"] = "Nastaví náhodnou položku v seznamu.";
messages["LISTS_SORT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
messages["LISTS_SORT_ORDER_ASCENDING"] = "vzestupně";
messages["LISTS_SORT_ORDER_DESCENDING"] = "sestupně";
messages["LISTS_SORT_TITLE"] = "seřadit %1 %2 %3";
messages["LISTS_SORT_TOOLTIP"] = "Seřadit kopii seznamu.";
messages["LISTS_SORT_TYPE_IGNORECASE"] = "abecedně, na velikosti písmen nezáleží";
messages["LISTS_SORT_TYPE_NUMERIC"] = "číselné";
messages["LISTS_SORT_TYPE_TEXT"] = "abecedně";
messages["LISTS_SPLIT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
messages["LISTS_SPLIT_LIST_FROM_TEXT"] = "udělat z textu seznam";
messages["LISTS_SPLIT_TEXT_FROM_LIST"] = "udělat ze seznamu text";
messages["LISTS_SPLIT_TOOLTIP_JOIN"] = "Spojit seznam textů do jednoho textu, rozdělaného oddělovači.";
messages["LISTS_SPLIT_TOOLTIP_SPLIT"] = "Rozdělit text do seznamu textů, lámání na oddělovačích.";
messages["LISTS_SPLIT_WITH_DELIMITER"] = "s oddělovačem";
messages["LOGIC_BOOLEAN_FALSE"] = "nepravda";
messages["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
messages["LOGIC_BOOLEAN_TOOLTIP"] = "Vrací pravda nebo nepravda.";
messages["LOGIC_BOOLEAN_TRUE"] = "pravda";
messages["LOGIC_COMPARE_HELPURL"] = "https://cs.wikipedia.org/wiki/Nerovnost_(matematika)";
messages["LOGIC_COMPARE_TOOLTIP_EQ"] = "Vrátí hodnotu pravda, pokud se oba vstupy rovnají jeden druhému.";
messages["LOGIC_COMPARE_TOOLTIP_GT"] = "Navrátí hodnotu pravda, pokud první vstup je větší než druhý vstup.";
messages["LOGIC_COMPARE_TOOLTIP_GTE"] = "Navrátí hodnotu pravda, pokud je první vstup větší a nebo rovný druhému vstupu.";
messages["LOGIC_COMPARE_TOOLTIP_LT"] = "Navrátí hodnotu pravda, pokud je první vstup menší než druhý vstup.";
messages["LOGIC_COMPARE_TOOLTIP_LTE"] = "Navrátí hodnotu pravda, pokud je první vstup menší a nebo rovný druhému vstupu.";
messages["LOGIC_COMPARE_TOOLTIP_NEQ"] = "Vrátí hodnotu pravda, pokud se oba vstupy nerovnají sobě navzájem.";
messages["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
messages["LOGIC_NEGATE_TITLE"] = "ne %1";
messages["LOGIC_NEGATE_TOOLTIP"] = "Navrátí hodnotu pravda, pokud je vstup nepravda. Navrátí hodnotu nepravda, pokud je vstup pravda.";
messages["LOGIC_NULL"] = "prázdný";
messages["LOGIC_NULL_HELPURL"] = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
messages["LOGIC_NULL_TOOLTIP"] = "Vrátí prázdnou hodnotu";
messages["LOGIC_OPERATION_AND"] = "a";
messages["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
messages["LOGIC_OPERATION_OR"] = "nebo";
messages["LOGIC_OPERATION_TOOLTIP_AND"] = "Vrátí hodnotu pravda, pokud oba dva vstupy jsou pravdivé.";
messages["LOGIC_OPERATION_TOOLTIP_OR"] = "Vrátí hodnotu pravda, pokud alespoň jeden ze vstupů má hodnotu pravda.";
messages["LOGIC_TERNARY_CONDITION"] = "test";
messages["LOGIC_TERNARY_HELPURL"] = "https://cs.wikipedia.org/wiki/Ternární operátor (programování)";
messages["LOGIC_TERNARY_IF_FALSE"] = "pokud nepravda";
messages["LOGIC_TERNARY_IF_TRUE"] = "pokud pravda";
messages["LOGIC_TERNARY_TOOLTIP"] = "Zkontroluje podmínku v \"testu\". Když je podmínka pravda, vrátí hodnotu \"pokud pravda\"; v opačném případě vrátí hodnotu \"pokud nepravda\".";
messages["MATH_ADDITION_SYMBOL"] = "+";  // untranslated
messages["MATH_ARITHMETIC_HELPURL"] = "https://cs.wikipedia.org/wiki/Aritmetika";
messages["MATH_ARITHMETIC_TOOLTIP_ADD"] = "Vrátí součet dvou čísel.";
messages["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "Vrátí podíl dvou čísel.";
messages["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "Vrátí rozdíl dvou čísel.";
messages["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "Vrátí součin dvou čísel.";
messages["MATH_ARITHMETIC_TOOLTIP_POWER"] = "Vrátí první číslo umocněné na druhé číslo.";
messages["MATH_ATAN2_HELPURL"] = "https://cs.wikipedia.org/wiki/Atan2";
messages["MATH_ATAN2_TITLE"] = "atan2 z X:%1 Y:%2";
messages["MATH_ATAN2_TOOLTIP"] = "Vrací arkustangens bodu (X, Y) ve stupních od -180 do 180.";
messages["MATH_CHANGE_HELPURL"] = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
messages["MATH_CHANGE_TITLE"] = "zaměň %1 za %2";
messages["MATH_CHANGE_TOOLTIP"] = "Přičti číslo k proměnné '%1'.";
messages["MATH_CONSTANT_HELPURL"] = "https://en.wikipedia.org/wiki/Mathematical_constant";
messages["MATH_CONSTANT_TOOLTIP"] = "Vraťte jednu z následujících konstant: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (nekonečno).";
messages["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
messages["MATH_CONSTRAIN_TITLE"] = "omez %1 na rozmezí od %2 do %3";
messages["MATH_CONSTRAIN_TOOLTIP"] = "Omezí číslo tak, aby bylo ve stanovených mezích (včetně).";
messages["MATH_DIVISION_SYMBOL"] = "÷";
messages["MATH_IS_DIVISIBLE_BY"] = "je dělitelné číslem";
messages["MATH_IS_EVEN"] = "je sudé";
messages["MATH_IS_NEGATIVE"] = "je záporné";
messages["MATH_IS_ODD"] = "je liché";
messages["MATH_IS_POSITIVE"] = "je kladné";
messages["MATH_IS_PRIME"] = "je prvočíslo";
messages["MATH_IS_TOOLTIP"] = "Kontrola, zda je číslo sudé, liché, prvočíslo, celé, kladné, záporné nebo zda je dělitelné daným číslem. Vrací pravdu nebo nepravdu.";
messages["MATH_IS_WHOLE"] = "je celé";
messages["MATH_MODULO_HELPURL"] = "https://cs.wikipedia.org/wiki/Modul%C3%A1rn%C3%AD_aritmetika";
messages["MATH_MODULO_TITLE"] = "zbytek po dělení %1 ÷ %2";
messages["MATH_MODULO_TOOLTIP"] = "Vrátí zbytek po dělení dvou čísel.";
messages["MATH_MULTIPLICATION_SYMBOL"] = "×";
messages["MATH_NUMBER_HELPURL"] = "https://cs.wikipedia.org/wiki/Číslo";
messages["MATH_NUMBER_TOOLTIP"] = "Číslo.";
messages["MATH_ONLIST_HELPURL"] = "";  // untranslated
messages["MATH_ONLIST_OPERATOR_AVERAGE"] = "průměr v seznamu";
messages["MATH_ONLIST_OPERATOR_MAX"] = "největší v seznamu";
messages["MATH_ONLIST_OPERATOR_MEDIAN"] = "medián v seznamu";
messages["MATH_ONLIST_OPERATOR_MIN"] = "nejmenší v seznamu";
messages["MATH_ONLIST_OPERATOR_MODE"] = "nejčastější ze seznamu";
messages["MATH_ONLIST_OPERATOR_RANDOM"] = "náhodná položka seznamu";
messages["MATH_ONLIST_OPERATOR_STD_DEV"] = "směrodatná odchylka ze seznamu";
messages["MATH_ONLIST_OPERATOR_SUM"] = "suma seznamu";
messages["MATH_ONLIST_TOOLTIP_AVERAGE"] = "Vrátí průměr (aritmetický průměr) číselných hodnot v seznamu.";
messages["MATH_ONLIST_TOOLTIP_MAX"] = "Vrátí největší číslo v seznamu.";
messages["MATH_ONLIST_TOOLTIP_MEDIAN"] = "Vrátí medián seznamu.";
messages["MATH_ONLIST_TOOLTIP_MIN"] = "Vrátí nejmenší číslo v seznamu.";
messages["MATH_ONLIST_TOOLTIP_MODE"] = "Vrátí seznam nejčastějších položek seznamu.";
messages["MATH_ONLIST_TOOLTIP_RANDOM"] = "Vrátí náhodnou položku ze seznamu.";
messages["MATH_ONLIST_TOOLTIP_STD_DEV"] = "Vrátí směrodatnou odchylku seznamu.";
messages["MATH_ONLIST_TOOLTIP_SUM"] = "Vrátí součet všech čísel v seznamu.";
messages["MATH_POWER_SYMBOL"] = "^";
messages["MATH_RANDOM_FLOAT_HELPURL"] = "https://cs.wikipedia.org/wiki/Gener%C3%A1tor_n%C3%A1hodn%C3%BDch_%C4%8D%C3%ADsel";
messages["MATH_RANDOM_FLOAT_TITLE_RANDOM"] = "náhodné číslo mezi 0 (včetně) do 1";
messages["MATH_RANDOM_FLOAT_TOOLTIP"] = "Vrátí náhodné číslo mezi 0,0 (včetně) až 1,0";
messages["MATH_RANDOM_INT_HELPURL"] = "https://cs.wikipedia.org/wiki/Gener%C3%A1tor_n%C3%A1hodn%C3%BDch_%C4%8D%C3%ADsel";
messages["MATH_RANDOM_INT_TITLE"] = "náhodné celé číslo od %1 do %2";
messages["MATH_RANDOM_INT_TOOLTIP"] = "Vrací náhodné celé číslo mezi dvěma určenými mezemi, včetně mezních hodnot.";
messages["MATH_ROUND_HELPURL"] = "https://en.wikipedia.org/wiki/Rounding";
messages["MATH_ROUND_OPERATOR_ROUND"] = "zaokrouhlit";
messages["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "zaokrouhlit dolů";
messages["MATH_ROUND_OPERATOR_ROUNDUP"] = "zaokrouhlit nahoru";
messages["MATH_ROUND_TOOLTIP"] = "Zaokrouhlit číslo nahoru nebo dolů.";
messages["MATH_SINGLE_HELPURL"] = "https://cs.wikipedia.org/wiki/Druhá_odmocnina";
messages["MATH_SINGLE_OP_ABSOLUTE"] = "absolutní hodnota";
messages["MATH_SINGLE_OP_ROOT"] = "druhá odmocnina";
messages["MATH_SINGLE_TOOLTIP_ABS"] = "Vrátí absolutní hodnotu čísla.";
messages["MATH_SINGLE_TOOLTIP_EXP"] = "Vrátí mocninu čísla e.";
messages["MATH_SINGLE_TOOLTIP_LN"] = "Vrátí přirozený logaritmus čísla.";
messages["MATH_SINGLE_TOOLTIP_LOG10"] = "Vrátí desítkový logaritmus čísla.";
messages["MATH_SINGLE_TOOLTIP_NEG"] = "Vrátí zápornou hodnotu čísla.";
messages["MATH_SINGLE_TOOLTIP_POW10"] = "Vrátí mocninu čísla 10.";
messages["MATH_SINGLE_TOOLTIP_ROOT"] = "Vrátí druhou odmocninu čísla.";
messages["MATH_SUBTRACTION_SYMBOL"] = "-";
messages["MATH_TRIG_ACOS"] = "acos";
messages["MATH_TRIG_ASIN"] = "arcsin";
messages["MATH_TRIG_ATAN"] = "arctan";
messages["MATH_TRIG_COS"] = "cos";
messages["MATH_TRIG_HELPURL"] = "https://en.wikipedia.org/wiki/Trigonometric_functions";
messages["MATH_TRIG_SIN"] = "sin";
messages["MATH_TRIG_TAN"] = "tan";
messages["MATH_TRIG_TOOLTIP_ACOS"] = "Vrátí arkus kosinus čísla.";
messages["MATH_TRIG_TOOLTIP_ASIN"] = "Vrátí arkus sinus čísla.";
messages["MATH_TRIG_TOOLTIP_ATAN"] = "Vrátí arkus tangens čísla.";
messages["MATH_TRIG_TOOLTIP_COS"] = "Vrátí kosinus úhlu ve stupních.";
messages["MATH_TRIG_TOOLTIP_SIN"] = "Vrátí sinus úhlu ve stupních.";
messages["MATH_TRIG_TOOLTIP_TAN"] = "Vrátí tangens úhlu ve stupních.";
messages["NEW_COLOUR_VARIABLE"] = "Vytvořit proměnnou pro barvu...";
messages["NEW_NUMBER_VARIABLE"] = "Vytvořit číselnou proměnnou...";
messages["NEW_STRING_VARIABLE"] = "Vytvořit textovou proměnnou...";
messages["NEW_VARIABLE"] = "Vytvořit proměnnou...";
messages["NEW_VARIABLE_TITLE"] = "Nový název proměnné:";
messages["NEW_VARIABLE_TYPE_TITLE"] = "Nový typ proměnné:";
messages["ORDINAL_NUMBER_SUFFIX"] = "";  // untranslated
messages["PROCEDURES_ALLOW_STATEMENTS"] = "povolit příkazy";
messages["PROCEDURES_BEFORE_PARAMS"] = "s:";
messages["PROCEDURES_CALLNORETURN_HELPURL"] = "https://cs.wikipedia.org/wiki/Podprogram";
messages["PROCEDURES_CALLNORETURN_TOOLTIP"] = "Spustí uživatelem definovanou funkci '%1'.";
messages["PROCEDURES_CALLRETURN_HELPURL"] = "https://cs.wikipedia.org/wiki/Podprogram";
messages["PROCEDURES_CALLRETURN_TOOLTIP"] = "Spustí uživatelem definovanou funkci '%1' a použije její výstup.";
messages["PROCEDURES_CALL_BEFORE_PARAMS"] = "s:";
messages["PROCEDURES_CREATE_DO"] = "Vytvořit '%1'";
messages["PROCEDURES_DEFNORETURN_COMMENT"] = "Popište tuto funkci...";
messages["PROCEDURES_DEFNORETURN_DO"] = "";  // untranslated
messages["PROCEDURES_DEFNORETURN_HELPURL"] = "https://cs.wikipedia.org/w/index.php?title=Funkce_(programování)";
messages["PROCEDURES_DEFNORETURN_PROCEDURE"] = "proveď něco";
messages["PROCEDURES_DEFNORETURN_TITLE"] = "k provedení";
messages["PROCEDURES_DEFNORETURN_TOOLTIP"] = "Vytvořit funkci bez výstupu.";
messages["PROCEDURES_DEFRETURN_HELPURL"] = "https://cs.wikipedia.org/w/index.php?title=Funkce_(programování)";
messages["PROCEDURES_DEFRETURN_RETURN"] = "navrátit";
messages["PROCEDURES_DEFRETURN_TOOLTIP"] = "Vytvořit funkci s výstupem.";
messages["PROCEDURES_DEF_DUPLICATE_WARNING"] = "Upozornění: Tato funkce má duplicitní parametry.";
messages["PROCEDURES_HIGHLIGHT_DEF"] = "Zvýraznit definici funkce";
messages["PROCEDURES_IFRETURN_HELPURL"] = "http://c2.com/cgi/wiki?GuardClause";
messages["PROCEDURES_IFRETURN_TOOLTIP"] = "Je-li hodnota pravda, pak vrátí druhou hodnotu.";
messages["PROCEDURES_IFRETURN_WARNING"] = "Varování: Tento blok může být použit pouze uvnitř definici funkce.";
messages["PROCEDURES_MUTATORARG_TITLE"] = "vstupní jméno:";
messages["PROCEDURES_MUTATORARG_TOOLTIP"] = "Přidat vstupy do funkce.";
messages["PROCEDURES_MUTATORCONTAINER_TITLE"] = "vstupy";
messages["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "Přidat, odebrat nebo změnit pořadí vstupů této funkce.";
messages["REDO"] = "Znovu";
messages["REMOVE_COMMENT"] = "Odstranit komentář";
messages["RENAME_VARIABLE"] = "Přejmenovat proměnnou...";
messages["RENAME_VARIABLE_TITLE"] = "Přejmenuj všech '%1' proměnných na:";
messages["TEXT_APPEND_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
messages["TEXT_APPEND_TITLE"] = "do %1 přidat text %2";
messages["TEXT_APPEND_TOOLTIP"] = "Přidá určitý text k proměnné '%1'.";
messages["TEXT_CHANGECASE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
messages["TEXT_CHANGECASE_OPERATOR_LOWERCASE"] = "na malá písmena";
messages["TEXT_CHANGECASE_OPERATOR_TITLECASE"] = "na Počáteční Velká Písmena";
messages["TEXT_CHANGECASE_OPERATOR_UPPERCASE"] = "na VELKÁ PÍSMENA";
messages["TEXT_CHANGECASE_TOOLTIP"] = "Vrátí kopii textu s jinou velikostí písmen.";
messages["TEXT_CHARAT_FIRST"] = "získat první písmeno";
messages["TEXT_CHARAT_FROM_END"] = "získat # písmeno od konce";
messages["TEXT_CHARAT_FROM_START"] = "získat písmeno #";
messages["TEXT_CHARAT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
messages["TEXT_CHARAT_LAST"] = "získat poslední písmeno";
messages["TEXT_CHARAT_RANDOM"] = "získat náhodné písmeno";
messages["TEXT_CHARAT_TAIL"] = "";  // untranslated
messages["TEXT_CHARAT_TITLE"] = "v textu %1 %2";
messages["TEXT_CHARAT_TOOLTIP"] = "Získat písmeno na konkrétní pozici.";
messages["TEXT_COUNT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#counting-substrings";  // untranslated
messages["TEXT_COUNT_MESSAGE0"] = "count %1 in %2";  // untranslated
messages["TEXT_COUNT_TOOLTIP"] = "Count how many times some text occurs within some other text.";  // untranslated
messages["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "Přidat položku do textu.";
messages["TEXT_CREATE_JOIN_TITLE_JOIN"] = "spojit";
messages["TEXT_CREATE_JOIN_TOOLTIP"] = "Přidat, odebrat nebo změnit pořadí oddílů tohoto textového bloku.";
messages["TEXT_GET_SUBSTRING_END_FROM_END"] = "do # písmene od konce";
messages["TEXT_GET_SUBSTRING_END_FROM_START"] = "do písmene #";
messages["TEXT_GET_SUBSTRING_END_LAST"] = "do posledního písmene";
messages["TEXT_GET_SUBSTRING_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
messages["TEXT_GET_SUBSTRING_INPUT_IN_TEXT"] = "v textu";
messages["TEXT_GET_SUBSTRING_START_FIRST"] = "získat podřetězec od prvního písmene";
messages["TEXT_GET_SUBSTRING_START_FROM_END"] = "získat podřetězec od písmene # od konce";
messages["TEXT_GET_SUBSTRING_START_FROM_START"] = "získat podřetězec od písmene #";
messages["TEXT_GET_SUBSTRING_TAIL"] = "";  // untranslated
messages["TEXT_GET_SUBSTRING_TOOLTIP"] = "Získat zadanou část textu.";
messages["TEXT_INDEXOF_HELPURL"] = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
messages["TEXT_INDEXOF_OPERATOR_FIRST"] = "najít první výskyt textu";
messages["TEXT_INDEXOF_OPERATOR_LAST"] = "najít poslední výskyt textu";
messages["TEXT_INDEXOF_TITLE"] = "v textu %1 %2 %3";
messages["TEXT_INDEXOF_TOOLTIP"] = "Vrátí index prvního/posledního výskytu prvního textu v druhém textu.  Pokud text není nalezen, vypíše %1.";
messages["TEXT_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
messages["TEXT_ISEMPTY_TITLE"] = "%1 je prázdný";
messages["TEXT_ISEMPTY_TOOLTIP"] = "Vrátí pravda pokud je zadaný text prázdný.";
messages["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
messages["TEXT_JOIN_TITLE_CREATEWITH"] = "vytvořit text s";
messages["TEXT_JOIN_TOOLTIP"] = "Vytvoří kousek textu spojením libovolného počtu položek.";
messages["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
messages["TEXT_LENGTH_TITLE"] = "délka %1";
messages["TEXT_LENGTH_TOOLTIP"] = "Vrátí počet písmen (včetně mezer) v zadaném textu.";
messages["TEXT_PRINT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
messages["TEXT_PRINT_TITLE"] = "tisk %1";
messages["TEXT_PRINT_TOOLTIP"] = "Tisk zadaného textu, čísla nebo jiné hodnoty.";
messages["TEXT_PROMPT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
messages["TEXT_PROMPT_TOOLTIP_NUMBER"] = "Výzva pro uživatele k zadání čísla.";
messages["TEXT_PROMPT_TOOLTIP_TEXT"] = "Výzva pro uživatele k zadání nějakého textu.";
messages["TEXT_PROMPT_TYPE_NUMBER"] = "výzva k zadání čísla se zprávou";
messages["TEXT_PROMPT_TYPE_TEXT"] = "výzva k zadání textu se zprávou";
messages["TEXT_REPLACE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#replacing-substrings";  // untranslated
messages["TEXT_REPLACE_MESSAGE0"] = "replace %1 with %2 in %3";  // untranslated
messages["TEXT_REPLACE_TOOLTIP"] = "Replace all occurances of some text within some other text.";  // untranslated
messages["TEXT_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#reversing-text";  // untranslated
messages["TEXT_REVERSE_MESSAGE0"] = "reverse %1";  // untranslated
messages["TEXT_REVERSE_TOOLTIP"] = "Reverses the order of the characters in the text.";  // untranslated
messages["TEXT_TEXT_HELPURL"] = "https://cs.wikipedia.org/wiki/Textov%C3%BD_%C5%99et%C4%9Bzec";
messages["TEXT_TEXT_TOOLTIP"] = "Písmeno, slovo nebo řádek textu.";
messages["TEXT_TRIM_HELPURL"] = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
messages["TEXT_TRIM_OPERATOR_BOTH"] = "odstranit mezery z obou stran";
messages["TEXT_TRIM_OPERATOR_LEFT"] = "odstranit mezery z levé strany";
messages["TEXT_TRIM_OPERATOR_RIGHT"] = "odstranit mezery z pravé strany";
messages["TEXT_TRIM_TOOLTIP"] = "Vrátí kopii textu s odstraněnými mezerami z jednoho nebo obou konců.";
messages["TODAY"] = "Dnes";
messages["UNDO"] = "Zpět";
messages["UNNAMED_KEY"] = "nepojmenovaný";
messages["VARIABLES_DEFAULT_NAME"] = "položka";
messages["VARIABLES_GET_CREATE_SET"] = "Vytvořit \"nastavit %1\"";
messages["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
messages["VARIABLES_GET_TOOLTIP"] = "Vrátí hodnotu této proměnné.";
messages["VARIABLES_SET"] = "nastavit %1 na %2";
messages["VARIABLES_SET_CREATE_GET"] = "Vytvořit \"získat %1\"";
messages["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
messages["VARIABLES_SET_TOOLTIP"] = "Nastaví tuto proměnnou, aby se rovnala vstupu.";
messages["VARIABLE_ALREADY_EXISTS"] = "Proměnná jménem '%1' již existuje";
messages["VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE"] = "Proměnná pojmenovaná jako '%1' již existuje pro jiný typ: '%2'.";
messages["WORKSPACE_ARIA_LABEL"] = "Blockly Workspace";  // untranslated
messages["WORKSPACE_COMMENT_DEFAULT_TEXT"] = "Say something...";  // untranslated
messages["CONTROLS_FOREACH_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_FOR_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = messages["CONTROLS_IF_MSG_ELSEIF"];
messages["CONTROLS_IF_ELSE_TITLE_ELSE"] = messages["CONTROLS_IF_MSG_ELSE"];
messages["CONTROLS_IF_IF_TITLE_IF"] = messages["CONTROLS_IF_MSG_IF"];
messages["CONTROLS_IF_MSG_THEN"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_WHILEUNTIL_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["LISTS_CREATE_WITH_ITEM_TITLE"] = messages["VARIABLES_DEFAULT_NAME"];
messages["LISTS_GET_INDEX_HELPURL"] = messages["LISTS_INDEX_OF_HELPURL"];
messages["LISTS_GET_INDEX_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_GET_SUBLIST_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_INDEX_OF_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_SET_INDEX_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["MATH_CHANGE_TITLE_ITEM"] = messages["VARIABLES_DEFAULT_NAME"];
messages["PROCEDURES_DEFRETURN_COMMENT"] = messages["PROCEDURES_DEFNORETURN_COMMENT"];
messages["PROCEDURES_DEFRETURN_DO"] = messages["PROCEDURES_DEFNORETURN_DO"];
messages["PROCEDURES_DEFRETURN_PROCEDURE"] = messages["PROCEDURES_DEFNORETURN_PROCEDURE"];
messages["PROCEDURES_DEFRETURN_TITLE"] = messages["PROCEDURES_DEFNORETURN_TITLE"];
messages["TEXT_APPEND_VARIABLE"] = messages["VARIABLES_DEFAULT_NAME"];
messages["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = messages["VARIABLES_DEFAULT_NAME"];

messages["MATH_HUE"] = "230";
messages["LOOPS_HUE"] = "120";
messages["LISTS_HUE"] = "260";
messages["LOGIC_HUE"] = "210";
messages["VARIABLES_HUE"] = "330";
messages["TEXTS_HUE"] = "160";
messages["PROCEDURES_HUE"] = "290";
messages["COLOUR_HUE"] = "20";
messages["VARIABLES_DYNAMIC_HUE"] = "310";