// This file was automatically generated.  Do not modify.

'use strict';

const messages = Object.create(null);

messages["ADD_COMMENT"] = "Aldoni komenton";
messages["CANNOT_DELETE_VARIABLE_PROCEDURE"] = "Ne povas forigi la variablon '%1' ĉar ĝi estas parto de la difino de la funkcio '%2'";
messages["CHANGE_VALUE_TITLE"] = "Ŝangi valoron:";
messages["CLEAN_UP"] = "Purigi blokojn";
messages["COLLAPSED_WARNINGS_WARNING"] = "Falditaj blokoj enhavas avertojn.";
messages["COLLAPSE_ALL"] = "Faldi blokojn";
messages["COLLAPSE_BLOCK"] = "Faldi blokon";
messages["COLOUR_BLEND_COLOUR1"] = "koloro 1";
messages["COLOUR_BLEND_COLOUR2"] = "koloro 2";
messages["COLOUR_BLEND_HELPURL"] = "https://meyerweb.com/eric/tools/color-blend/#:::rgbp";  // untranslated
messages["COLOUR_BLEND_RATIO"] = "proporcio";
messages["COLOUR_BLEND_TITLE"] = "miksi";
messages["COLOUR_BLEND_TOOLTIP"] = "Kunmiksas du kolorojn laŭ specifita proporcio (0,0 - 1,0).";
messages["COLOUR_PICKER_HELPURL"] = "https://eo.wikipedia.org/wiki/Koloro";
messages["COLOUR_PICKER_TOOLTIP"] = "Elekti koloron el la paletro.";
messages["COLOUR_RANDOM_HELPURL"] = "http://randomcolour.com";  // untranslated
messages["COLOUR_RANDOM_TITLE"] = "hazarda koloro";
messages["COLOUR_RANDOM_TOOLTIP"] = "Elekti hazardan koloron.";
messages["COLOUR_RGB_BLUE"] = "blua";
messages["COLOUR_RGB_GREEN"] = "verda";
messages["COLOUR_RGB_HELPURL"] = "https://www.december.com/html/spec/colorpercompact.html";  // untranslated
messages["COLOUR_RGB_RED"] = "ruĝa";
messages["COLOUR_RGB_TITLE"] = "kolorigi per";
messages["COLOUR_RGB_TOOLTIP"] = "Kreas koloron kun specifita kvanto de ruĝo, verdo, kaj bluo. Ĉiuj valoroj devas esti inter 0 kaj 100.";
messages["CONTROLS_FLOW_STATEMENTS_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
messages["CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK"] = "eliri el la ciklo";
messages["CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE"] = "daŭrigi je la venonta ripeto de la ciklo";
messages["CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK"] = "Eliri el la enhava ciklo.";
messages["CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE"] = "Pretersalti la ceteron de tiu ĉi ciklo kaj daŭrigi je la venonta ripeto.";
messages["CONTROLS_FLOW_STATEMENTS_WARNING"] = "Averto: tiu ĉi bloko uzeblas nur ene de ciklo.";
messages["CONTROLS_FOREACH_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
messages["CONTROLS_FOREACH_TITLE"] = "por ĉiu elemento %1 en la listo %2";
messages["CONTROLS_FOREACH_TOOLTIP"] = "Pri ĉiu elemento en listo, difinas la variablon '%1' al la elemento, kaj faras kelkajn ordonojn.";
messages["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
messages["CONTROLS_FOR_TITLE"] = "kalkuli kun variablo %1 ekde %2 ĝis %3 per diferenco %4";
messages["CONTROLS_FOR_TOOLTIP"] = "Varias la variablon '%1', ekde la komenca nombro ĝis la fina nombro, laŭ la specifita diferenco; dume rulas la specifitajn blokojn.";
messages["CONTROLS_IF_ELSEIF_TOOLTIP"] = "Aldoni kondiĉon al la bloko 'se'";
messages["CONTROLS_IF_ELSE_TOOLTIP"] = "Aldoni 'aliokaze' kondiĉon al la 'se' bloko.";
messages["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
messages["CONTROLS_IF_IF_TOOLTIP"] = "Aldoni, forigi aŭ reorganizi partojn por reagordi la 'se'-blokon.";
messages["CONTROLS_IF_MSG_ELSE"] = "alie";
messages["CONTROLS_IF_MSG_ELSEIF"] = "alie se";
messages["CONTROLS_IF_MSG_IF"] = "se";
messages["CONTROLS_IF_TOOLTIP_1"] = "Plenumi ordonojn se la valoro estas vero.";
messages["CONTROLS_IF_TOOLTIP_2"] = "Plenumi la unuan blokon de ordonoj se la valoro estas vero, se ne, la duan.";
messages["CONTROLS_IF_TOOLTIP_3"] = "Se la unua valoro estas vero, do faras la unuan blokon de ordonoj. Alie, se la dua valoro estas vero, do faras la duan blokon de ordonoj.";
messages["CONTROLS_IF_TOOLTIP_4"] = "Se la unua valoro estas vero, do faras la unuan blokon de ordonoj. Alie, se la dua valoro estas vero, do faras la duan blokon de ordonoj. Se neniu el la du valoroj estas vero, do faras la lastan blokon de ordonoj.";
messages["CONTROLS_REPEAT_HELPURL"] = "https://eo.wikipedia.org/wiki/Iteracio";
messages["CONTROLS_REPEAT_INPUT_DO"] = "fari";
messages["CONTROLS_REPEAT_TITLE"] = "ripeti %1 fojojn";
messages["CONTROLS_REPEAT_TOOLTIP"] = "Plenumas kelkajn ordonojn plurfoje.";
messages["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
messages["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "ripeti ĝis";
messages["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "ripeti dum";
messages["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "Plenumi ordonojn dum valoro egalas malvero.";
messages["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "Plenumi ordonojn dum la valoro egalas veron.";
messages["DELETE_ALL_BLOCKS"] = "Ĉu forigi ĉiujn %1 blokojn?";
messages["DELETE_BLOCK"] = "Forigi blokon";
messages["DELETE_VARIABLE"] = "Forigi la variablon '%1'";
messages["DELETE_VARIABLE_CONFIRMATION"] = "Ĉu forigi %1 uzojn de la variablo '%2'?";
messages["DELETE_X_BLOCKS"] = "Forigi %1 blokojn";
messages["DIALOG_CANCEL"] = "Nuligi";
messages["DIALOG_OK"] = "Bone";
messages["DISABLE_BLOCK"] = "Malŝalti blokon";
messages["DUPLICATE_BLOCK"] = "Duobligi";
messages["DUPLICATE_COMMENT"] = "Duobligi Komenton";
messages["ENABLE_BLOCK"] = "Ŝalti blokon";
messages["EXPAND_ALL"] = "Malfaldi blokojn";
messages["EXPAND_BLOCK"] = "Malfaldi blokon";
messages["EXTERNAL_INPUTS"] = "Eksteraj eniroj";
messages["HELP"] = "Helpo";
messages["INLINE_INPUTS"] = "Entekstaj eniroj";
messages["LISTS_CREATE_EMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
messages["LISTS_CREATE_EMPTY_TITLE"] = "krei malplenan liston";
messages["LISTS_CREATE_EMPTY_TOOLTIP"] = "Liveri liston, de longo 0, sen datenaj rikordoj";
messages["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "listo";
messages["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "Aldoni, forigi aŭ ordigi partojn por reagordi la listan blokon.";
messages["LISTS_CREATE_WITH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
messages["LISTS_CREATE_WITH_INPUT_WITH"] = "krei liston kun";
messages["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "Aldoni elementon al la listo.";
messages["LISTS_CREATE_WITH_TOOLTIP"] = "Krei liston kun ajna nombro de elementoj.";
messages["LISTS_GET_INDEX_FIRST"] = "unuan";
messages["LISTS_GET_INDEX_FROM_END"] = "#el la fino";
messages["LISTS_GET_INDEX_FROM_START"] = "#";  // untranslated
messages["LISTS_GET_INDEX_GET"] = "akiri";
messages["LISTS_GET_INDEX_GET_REMOVE"] = "akiri kaj forigi";
messages["LISTS_GET_INDEX_LAST"] = "lastan";
messages["LISTS_GET_INDEX_RANDOM"] = "hazardan";
messages["LISTS_GET_INDEX_REMOVE"] = "forigi";
messages["LISTS_GET_INDEX_TAIL"] = "";  // untranslated
messages["LISTS_GET_INDEX_TOOLTIP_GET_FIRST"] = "La unua elemento en la listo esto liverita.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_FROM"] = "Liveri la elementon ĉe la specifita pozicio en listo.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_LAST"] = "Liveri la lastan elementon en la listo.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_RANDOM"] = "Hazarda elemento en la listo estos liverita.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST"] = "La unua elemento en la listo estos liverita kaj forigita.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM"] = "Liveri kaj forigi la elementon en la specifita pozicio de la listo.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST"] = "Forigi kaj liveri la lastan elementon en listo.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM"] = "Hazarda elemento en la listo estos liverita kaj forigita.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST"] = "La unua elemento en la listo estos forigita.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM"] = "La elemento en la specifita pozicio en la listo estos forigita.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST"] = "La lasta elemento en la listo estos forigita.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM"] = "Hazarda elemento en la listo estos forigita.";
messages["LISTS_GET_SUBLIST_END_FROM_END"] = "ĝis elemento de inversa numero";
messages["LISTS_GET_SUBLIST_END_FROM_START"] = "ĝis elemento de numero";
messages["LISTS_GET_SUBLIST_END_LAST"] = "ĝis la lasta elemento";
messages["LISTS_GET_SUBLIST_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
messages["LISTS_GET_SUBLIST_START_FIRST"] = "akiri subliston ekde la unua elemento";
messages["LISTS_GET_SUBLIST_START_FROM_END"] = "akiri subliston ekde elemento de inversa numero";
messages["LISTS_GET_SUBLIST_START_FROM_START"] = "akiri subliston ekde elemento de numero";
messages["LISTS_GET_SUBLIST_TAIL"] = "";  // untranslated
messages["LISTS_GET_SUBLIST_TOOLTIP"] = "Kreas kopion de la specifita parto de listo.";
messages["LISTS_INDEX_FROM_END_TOOLTIP"] = "%1 estas la lasta elemento.";
messages["LISTS_INDEX_FROM_START_TOOLTIP"] = "%1 estas la unua elemento.";
messages["LISTS_INDEX_OF_FIRST"] = "trovi la unuan aperon de elemento";
messages["LISTS_INDEX_OF_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
messages["LISTS_INDEX_OF_LAST"] = "trovi la lastan aperon de elemento";
messages["LISTS_INDEX_OF_TOOLTIP"] = "La indekso de la unua/lasta apero de la elemento en la listo estos liverita. %1 estos liverita se la elemento ne estas trovita.";
messages["LISTS_INLIST"] = "en la listo";
messages["LISTS_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
messages["LISTS_ISEMPTY_TITLE"] = "%1 malplenas";
messages["LISTS_ISEMPTY_TOOLTIP"] = "Liveri veron, se la listo malplenas.";
messages["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
messages["LISTS_LENGTH_TITLE"] = "longo de %1";
messages["LISTS_LENGTH_TOOLTIP"] = "Liveri la longon de listo.";
messages["LISTS_REPEAT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
messages["LISTS_REPEAT_TITLE"] = "krei liston kun elemento %1 ripetita %2 fojojn";
messages["LISTS_REPEAT_TOOLTIP"] = "Listo kun la specifita nombro de elementoj, kiuj havos la donitan valoron, estos kreita.";
messages["LISTS_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";  // untranslated
messages["LISTS_REVERSE_MESSAGE0"] = "inversigi liston %1";
messages["LISTS_REVERSE_TOOLTIP"] = "Inversigi kopion de listo.";
messages["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
messages["LISTS_SET_INDEX_INPUT_TO"] = "kiel";
messages["LISTS_SET_INDEX_INSERT"] = "enmeti je";
messages["LISTS_SET_INDEX_SET"] = "difini";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST"] = "Antaŭaldonas la elementon ĉe la komenco de listo.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_FROM"] = "Enigas la elementon ĉe specifita pozicio en listo.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_LAST"] = "Postaldonas la elementon ĉe la fino de listo.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM"] = "Enigas la elementon hazarde en listo.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_FIRST"] = "Difinas la unua elementon en listo.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_FROM"] = "Difinas la elementon ĉe la specifita pozicio en listo";
messages["LISTS_SET_INDEX_TOOLTIP_SET_LAST"] = "Difinas la lastan elementon en listo.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_RANDOM"] = "Difinas hazardan elementon en listo.";
messages["LISTS_SORT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
messages["LISTS_SORT_ORDER_ASCENDING"] = "kreskante";
messages["LISTS_SORT_ORDER_DESCENDING"] = "malkreskante";
messages["LISTS_SORT_TITLE"] = "ordigi %1 %2 liston %3";
messages["LISTS_SORT_TOOLTIP"] = "Ordigas kopion de listo.";
messages["LISTS_SORT_TYPE_IGNORECASE"] = "alfabete, ignorante usklon";
messages["LISTS_SORT_TYPE_NUMERIC"] = "nombre";
messages["LISTS_SORT_TYPE_TEXT"] = "alfabete";
messages["LISTS_SPLIT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
messages["LISTS_SPLIT_LIST_FROM_TEXT"] = "fari liston el teksto";
messages["LISTS_SPLIT_TEXT_FROM_LIST"] = "fari tekston el listo";
messages["LISTS_SPLIT_TOOLTIP_JOIN"] = "Kunigas liston de tekstoj en unu tekston, kun apartigilo inter la elementoj.";
messages["LISTS_SPLIT_TOOLTIP_SPLIT"] = "Disdividas tekston en liston da tekstoj, laŭ apartigilo.";
messages["LISTS_SPLIT_WITH_DELIMITER"] = "kun apartigilo";
messages["LOGIC_BOOLEAN_FALSE"] = "falsa";
messages["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
messages["LOGIC_BOOLEAN_TOOLTIP"] = "Liveri ĉu veron ĉu malveron.";
messages["LOGIC_BOOLEAN_TRUE"] = "vera";
messages["LOGIC_COMPARE_HELPURL"] = "https://eo.wikipedia.org/wiki/Neegala%C4%B5o_(pli_granda,_malpli_granda)";
messages["LOGIC_COMPARE_TOOLTIP_EQ"] = "Liveri veron, se la du eniroj egalas.";
messages["LOGIC_COMPARE_TOOLTIP_GT"] = "Liveri veron, se la unua eniro estas pli granda ol la dua.";
messages["LOGIC_COMPARE_TOOLTIP_GTE"] = "Vero estos liverita, se la unua eniro estas pli granda aŭ egala al la dua.";
messages["LOGIC_COMPARE_TOOLTIP_LT"] = "Liveri veron, se la unua eniro estas pli malgranda ol la dua.";
messages["LOGIC_COMPARE_TOOLTIP_LTE"] = "Vero estos liverita, se la unua eniro estas pli eta aŭ egala al la dua.";
messages["LOGIC_COMPARE_TOOLTIP_NEQ"] = "Liveri veron, se la du eniroj ne egalas.";
messages["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
messages["LOGIC_NEGATE_TITLE"] = "maligi %1";
messages["LOGIC_NEGATE_TOOLTIP"] = "Liveri veron, se la eniro egalas malveron. Liveri malveron, se la eniro egalas veron.";
messages["LOGIC_NULL"] = "senvalora";
messages["LOGIC_NULL_HELPURL"] = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
messages["LOGIC_NULL_TOOLTIP"] = "Liveras senvaloron.";
messages["LOGIC_OPERATION_AND"] = "kaj";
messages["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
messages["LOGIC_OPERATION_OR"] = "aŭ";
messages["LOGIC_OPERATION_TOOLTIP_AND"] = "Liveri veron, se la du eniroj egalas veron.";
messages["LOGIC_OPERATION_TOOLTIP_OR"] = "Liveri veron, se almenaŭ unu el la eniroj egalas veron.";
messages["LOGIC_TERNARY_CONDITION"] = "testi";
messages["LOGIC_TERNARY_HELPURL"] = "https://en.wikipedia.org/wiki/%3F:";  // untranslated
messages["LOGIC_TERNARY_IF_FALSE"] = "se estas malvero";
messages["LOGIC_TERNARY_IF_TRUE"] = "se estas vero";
messages["LOGIC_TERNARY_TOOLTIP"] = "Kontroli la kondiĉon en 'testo'. Se la kondiĉo egalas veron, liveri la valoron 'se estas vero', aliokaze liveri la valoron 'se estas malvero'.";
messages["MATH_ADDITION_SYMBOL"] = "+";  // untranslated
messages["MATH_ARITHMETIC_HELPURL"] = "https://eo.wikipedia.org/wiki/Aritmetiko";
messages["MATH_ARITHMETIC_TOOLTIP_ADD"] = "Liveri la sumon de la du nombroj.";
messages["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "Liveri la kvocienton de la du nombroj.";
messages["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "Liveri la diferencon inter la du nombroj.";
messages["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "La produto de la du numeroj estos liverita.";
messages["MATH_ARITHMETIC_TOOLTIP_POWER"] = "Livero la tian potencon de la unua nombro, kia la dua nombro estas";
messages["MATH_ATAN2_HELPURL"] = "https://eo.wikipedia.org/wiki/Inversa_trigonometria_funkcio#Duargumenta_varianto_de_tangentarko";
messages["MATH_ATAN2_TITLE"] = "atan2 de X:%1 Y:%2";
messages["MATH_ATAN2_TOOLTIP"] = "Liveras la arkotangenton de punkto (X, Y) en gradoj inter -180 kaj 180.";
messages["MATH_CHANGE_HELPURL"] = "https://eo.wikipedia.org/wiki/Kremento";
messages["MATH_CHANGE_TITLE"] = "krementi %1 per %2";
messages["MATH_CHANGE_TOOLTIP"] = "Aldoni nombron al variablo '%1'.";
messages["MATH_CONSTANT_HELPURL"] = "https://eo.wikipedia.org/wiki/Matematika_konstanto";
messages["MATH_CONSTANT_TOOLTIP"] = "Liveras unu el la ofte uzataj konstantoj: π (3,141…), e (2,718…), φ (1,618…), √2 (1,414…), √½ (0,707…), aŭ ∞ (malfinio).";
messages["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
messages["MATH_CONSTRAIN_TITLE"] = "limigi %1 inter %2 kaj %3";
messages["MATH_CONSTRAIN_TOOLTIP"] = "La nombro estos limigita tiel ke ĝi egalas la limojn aŭ troviĝas inter ili.";
messages["MATH_DIVISION_SYMBOL"] = "÷";  // untranslated
messages["MATH_IS_DIVISIBLE_BY"] = "estas dividebla de";
messages["MATH_IS_EVEN"] = "estas para";
messages["MATH_IS_NEGATIVE"] = "estas negativa";
messages["MATH_IS_ODD"] = "estas nepara";
messages["MATH_IS_POSITIVE"] = "estas pozitiva";
messages["MATH_IS_PRIME"] = "estas primo";
messages["MATH_IS_TOOLTIP"] = "Vero aŭ malvero estos liverita, depende de la rezulto de kontrolo, ĉu nombro estas para, nepara, pozitiva, negativa, aŭ dividebla de iu nombro.";
messages["MATH_IS_WHOLE"] = "estas entjero";
messages["MATH_MODULO_HELPURL"] = "https://eo.wikipedia.org/wiki/Resto";
messages["MATH_MODULO_TITLE"] = "resto de %1 ÷ %2";
messages["MATH_MODULO_TOOLTIP"] = "Liveri la reston de la divido de la du nombroj.";
messages["MATH_MULTIPLICATION_SYMBOL"] = "×";  // untranslated
messages["MATH_NUMBER_HELPURL"] = "https://eo.wikipedia.org/wiki/Nombro";
messages["MATH_NUMBER_TOOLTIP"] = "Nombro.";
messages["MATH_ONLIST_HELPURL"] = "";  // untranslated
messages["MATH_ONLIST_OPERATOR_AVERAGE"] = "listmezumo";
messages["MATH_ONLIST_OPERATOR_MAX"] = "listmaksimumo";
messages["MATH_ONLIST_OPERATOR_MEDIAN"] = "mediano de listo";
messages["MATH_ONLIST_OPERATOR_MIN"] = "listminimumo";
messages["MATH_ONLIST_OPERATOR_MODE"] = "modoj de listo";
messages["MATH_ONLIST_OPERATOR_RANDOM"] = "hazarda elemento el la listo";
messages["MATH_ONLIST_OPERATOR_STD_DEV"] = "Norma devio de la listo";
messages["MATH_ONLIST_OPERATOR_SUM"] = "sumo de listo";
messages["MATH_ONLIST_TOOLTIP_AVERAGE"] = "Liveri la aritmetikan meznombron de la nombroj en la listo.";
messages["MATH_ONLIST_TOOLTIP_MAX"] = "Liveri la plej grandan nombron en la listo.";
messages["MATH_ONLIST_TOOLTIP_MEDIAN"] = "Liveras la medianan nombron en la listo.";
messages["MATH_ONLIST_TOOLTIP_MIN"] = "Liveri la plej malgrandan nombron en la listo.";
messages["MATH_ONLIST_TOOLTIP_MODE"] = "Liveras liston de la plej ofta(j) elemento(j) en la listo.";
messages["MATH_ONLIST_TOOLTIP_RANDOM"] = "Liveri hazardan elementon el la listo.";
messages["MATH_ONLIST_TOOLTIP_STD_DEV"] = "Liveri la norman devion de la listo.";
messages["MATH_ONLIST_TOOLTIP_SUM"] = "Liveri la sumon de ĉiuj nombroj en la listo.";
messages["MATH_POWER_SYMBOL"] = "^";  // untranslated
messages["MATH_RANDOM_FLOAT_HELPURL"] = "https://eo.wikipedia.org/wiki/Hazardo";
messages["MATH_RANDOM_FLOAT_TITLE_RANDOM"] = "hazarda frakcio";
messages["MATH_RANDOM_FLOAT_TOOLTIP"] = "Liveras hazardan frakcion inter 0,0 (inkluzive) kaj 1,0 (ekskluzive).";
messages["MATH_RANDOM_INT_HELPURL"] = "https://en.wikipedia.org/wiki/Random_number_generation";
messages["MATH_RANDOM_INT_TITLE"] = "hazarda entjero inter %1 kaj %2";
messages["MATH_RANDOM_INT_TOOLTIP"] = "Nombro estos hazarde liverita, tiel ke ĝi egalas la limojn aŭ troviĝas inter ili.";
messages["MATH_ROUND_HELPURL"] = "https://en.wikipedia.org/wiki/Rounding";
messages["MATH_ROUND_OPERATOR_ROUND"] = "rondigi";
messages["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "rondigi malsupren";
messages["MATH_ROUND_OPERATOR_ROUNDUP"] = "Rondigi supren";
messages["MATH_ROUND_TOOLTIP"] = "Rondigi nombroj, supren aŭ malsupren.";
messages["MATH_SINGLE_HELPURL"] = "https://eo.wikipedia.org/wiki/Kvadrata_radiko";
messages["MATH_SINGLE_OP_ABSOLUTE"] = "absoluta";
messages["MATH_SINGLE_OP_ROOT"] = "kvadrata radiko";
messages["MATH_SINGLE_TOOLTIP_ABS"] = "Liveri la absolutan valoron de nombro.";
messages["MATH_SINGLE_TOOLTIP_EXP"] = "Liveri potencon de e.";
messages["MATH_SINGLE_TOOLTIP_LN"] = "Liveri la naturan logaritmon de nombro.";
messages["MATH_SINGLE_TOOLTIP_LOG10"] = "La dekbaza logaritmo de numero estos liverita.";
messages["MATH_SINGLE_TOOLTIP_NEG"] = "La negativigo de numero estos liverita.";
messages["MATH_SINGLE_TOOLTIP_POW10"] = "Liveri tian potencon de 10, kia la eniro estas.";
messages["MATH_SINGLE_TOOLTIP_ROOT"] = "Liveri la kvadratan radikon de nombro.";
messages["MATH_SUBTRACTION_SYMBOL"] = "-";  // untranslated
messages["MATH_TRIG_ACOS"] = "acos";  // untranslated
messages["MATH_TRIG_ASIN"] = "asin";  // untranslated
messages["MATH_TRIG_ATAN"] = "atan";  // untranslated
messages["MATH_TRIG_COS"] = "cos";  // untranslated
messages["MATH_TRIG_HELPURL"] = "https://eo.wikipedia.org/wiki/Trigonometria_funkcio";
messages["MATH_TRIG_SIN"] = "sin";  // untranslated
messages["MATH_TRIG_TAN"] = "tan";  // untranslated
messages["MATH_TRIG_TOOLTIP_ACOS"] = "Liveras la arkokosinuson de nombro.";
messages["MATH_TRIG_TOOLTIP_ASIN"] = "La sinusarko de nombro estos liverita.";
messages["MATH_TRIG_TOOLTIP_ATAN"] = "La targentarko de nombro estos liverita.";
messages["MATH_TRIG_TOOLTIP_COS"] = "Liveras la kosinuson de angulo en gradoj (ne radianoj).";
messages["MATH_TRIG_TOOLTIP_SIN"] = "Liveras la sinuson de angulo en gradoj (ne radianoj).";
messages["MATH_TRIG_TOOLTIP_TAN"] = "Liveras la tangenton de angulo en gradoj (ne radianoj).";
messages["NEW_COLOUR_VARIABLE"] = "Krei koloran variablon...";
messages["NEW_NUMBER_VARIABLE"] = "Krei nombran variablon...";
messages["NEW_STRING_VARIABLE"] = "Krei signoĉenan variablon...";
messages["NEW_VARIABLE"] = "Nova variablo...";
messages["NEW_VARIABLE_TITLE"] = "Nova nomo de variablo:";
messages["NEW_VARIABLE_TYPE_TITLE"] = "Tipo de nova variablo:";
messages["ORDINAL_NUMBER_SUFFIX"] = "";  // untranslated
messages["PROCEDURES_ALLOW_STATEMENTS"] = "permesi ordonojn";
messages["PROCEDURES_BEFORE_PARAMS"] = "kun:";
messages["PROCEDURES_CALLNORETURN_HELPURL"] = "https://eo.wikipedia.org/wiki/Subprogramo";
messages["PROCEDURES_CALLNORETURN_TOOLTIP"] = "Ruli la uzanto-difinitan funkcion '%1'.";
messages["PROCEDURES_CALLRETURN_HELPURL"] = "https://eo.wikipedia.org/wiki/Subprogramo";
messages["PROCEDURES_CALLRETURN_TOOLTIP"] = "Ruli la uzanto-difinitan funkcion '%1' kaj uzi ĝian eliron.";
messages["PROCEDURES_CALL_BEFORE_PARAMS"] = "kun:";
messages["PROCEDURES_CREATE_DO"] = "Krei '%1'";
messages["PROCEDURES_DEFNORETURN_COMMENT"] = "Priskribi ĉi tiun funkcion...";
messages["PROCEDURES_DEFNORETURN_DO"] = "";  // untranslated
messages["PROCEDURES_DEFNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
messages["PROCEDURES_DEFNORETURN_PROCEDURE"] = "fari ion";
messages["PROCEDURES_DEFNORETURN_TITLE"] = "por";
messages["PROCEDURES_DEFNORETURN_TOOLTIP"] = "Krei funkcion sen eliro.";
messages["PROCEDURES_DEFRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
messages["PROCEDURES_DEFRETURN_RETURN"] = "liveri";
messages["PROCEDURES_DEFRETURN_TOOLTIP"] = "Krei funkcion kun unu eliro.";
messages["PROCEDURES_DEF_DUPLICATE_WARNING"] = "Averto: la funkcio havas du parametrojn kun la sama nomo.";
messages["PROCEDURES_HIGHLIGHT_DEF"] = "Emfazi difinon de funkcio";
messages["PROCEDURES_IFRETURN_HELPURL"] = "http://c2.com/cgi/wiki?GuardClause";  // untranslated
messages["PROCEDURES_IFRETURN_TOOLTIP"] = "Se valoro estas vero, do liveras duan valoron.";
messages["PROCEDURES_IFRETURN_WARNING"] = "Averto: Ĉi tiu bloko estas uzebla nur en difino de funkcio.";
messages["PROCEDURES_MUTATORARG_TITLE"] = "nomo de enigo:";
messages["PROCEDURES_MUTATORARG_TOOLTIP"] = "Aldoni eniron al la funkcio.";
messages["PROCEDURES_MUTATORCONTAINER_TITLE"] = "eniroj";
messages["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "Aldoni, forigi, aŭ reorganizi enirojn je ĉi tiu funkcio.";
messages["REDO"] = "Refari";
messages["REMOVE_COMMENT"] = "Forigi komenton";
messages["RENAME_VARIABLE"] = "Renomi variablon...";
messages["RENAME_VARIABLE_TITLE"] = "Renomi ĉiujn '%1' variablojn kiel:";
messages["TEXT_APPEND_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
messages["TEXT_APPEND_TITLE"] = "al %1 postaldoni tekston %2";
messages["TEXT_APPEND_TOOLTIP"] = "Postapendi iom da teksto al variablo '%1'.";
messages["TEXT_CHANGECASE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
messages["TEXT_CHANGECASE_OPERATOR_LOWERCASE"] = "minuskligi";
messages["TEXT_CHANGECASE_OPERATOR_TITLECASE"] = "Nomuskligi";
messages["TEXT_CHANGECASE_OPERATOR_UPPERCASE"] = "MAJUSKLIGI";
messages["TEXT_CHANGECASE_TOOLTIP"] = "Liveras kopion de la teksto je alia usklo.";
messages["TEXT_CHARAT_FIRST"] = "akiri unuan literon";
messages["TEXT_CHARAT_FROM_END"] = "akiri literon de inversa numero";
messages["TEXT_CHARAT_FROM_START"] = "akiri literon de numero";
messages["TEXT_CHARAT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
messages["TEXT_CHARAT_LAST"] = "akiri lastan literon";
messages["TEXT_CHARAT_RANDOM"] = "akiri hazardan literon";
messages["TEXT_CHARAT_TAIL"] = "";  // untranslated
messages["TEXT_CHARAT_TITLE"] = "en la teksto %1, %2";
messages["TEXT_CHARAT_TOOLTIP"] = "Liveras literon ĉe specifita loko.";
messages["TEXT_COUNT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#counting-substrings";  // untranslated
messages["TEXT_COUNT_MESSAGE0"] = "kalkuli la okazojn de %1 en %2";
messages["TEXT_COUNT_TOOLTIP"] = "Kalkuli kiomfoje iu teksto okazas en iu alia teksto.";
messages["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "Aldoni eron al la teksto.";
messages["TEXT_CREATE_JOIN_TITLE_JOIN"] = "kunigi";
messages["TEXT_CREATE_JOIN_TOOLTIP"] = "Aldonu, forigu, aŭ reorganizu partojn por reagordi la tekstan blokon.";
messages["TEXT_GET_SUBSTRING_END_FROM_END"] = "ĝis litero de inversa numero";
messages["TEXT_GET_SUBSTRING_END_FROM_START"] = "ĝis litero de numero";
messages["TEXT_GET_SUBSTRING_END_LAST"] = "ĝis lasta litero";
messages["TEXT_GET_SUBSTRING_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
messages["TEXT_GET_SUBSTRING_INPUT_IN_TEXT"] = "en la teksto";
messages["TEXT_GET_SUBSTRING_START_FIRST"] = "akiri subsignoĉenon ekde la unua litero";
messages["TEXT_GET_SUBSTRING_START_FROM_END"] = "akiri subsignoĉenon ekde litero de inversa numero";
messages["TEXT_GET_SUBSTRING_START_FROM_START"] = "akiri subsignoĉenon ekde litero de numero";
messages["TEXT_GET_SUBSTRING_TAIL"] = "";  // untranslated
messages["TEXT_GET_SUBSTRING_TOOLTIP"] = "Liveri specifitan parto de la teksto.";
messages["TEXT_INDEXOF_HELPURL"] = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
messages["TEXT_INDEXOF_OPERATOR_FIRST"] = "trovi la unuan okazon de teksto";
messages["TEXT_INDEXOF_OPERATOR_LAST"] = "trovi la lastan okazon de teksto";
messages["TEXT_INDEXOF_TITLE"] = "en la teksto %1 %2 %3";
messages["TEXT_INDEXOF_TOOLTIP"] = "Liveras indekson de la unua/lasta okazo de la unua teksto en la dua teksto. Liveras %1 se la unua teksto ne okazas en la dua teksto.";
messages["TEXT_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
messages["TEXT_ISEMPTY_TITLE"] = "%1 malplenas";
messages["TEXT_ISEMPTY_TOOLTIP"] = "Liveras veron, se la provizita teksto estas malplena.";
messages["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
messages["TEXT_JOIN_TITLE_CREATEWITH"] = "krei tekston kun";
messages["TEXT_JOIN_TOOLTIP"] = "Krei pecon de teksto per kunigi ajnan nombron de eroj.";
messages["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
messages["TEXT_LENGTH_TITLE"] = "longo de %1";
messages["TEXT_LENGTH_TOOLTIP"] = "Liveras la nombron de literoj (inkluzive de spacetoj) en la provizita teksto.";
messages["TEXT_PRINT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
messages["TEXT_PRINT_TITLE"] = "presi %1";
messages["TEXT_PRINT_TOOLTIP"] = "Presi la specifitan tekston, nombron aŭ alian valoron.";
messages["TEXT_PROMPT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
messages["TEXT_PROMPT_TOOLTIP_NUMBER"] = "Peti nombron al uzanto.";
messages["TEXT_PROMPT_TOOLTIP_TEXT"] = "Peti tekston al uzanto.";
messages["TEXT_PROMPT_TYPE_NUMBER"] = "ricevi nombron per mesaĝo";
messages["TEXT_PROMPT_TYPE_TEXT"] = "ricevi tekston per mesaĝo";
messages["TEXT_REPLACE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#replacing-substrings";  // untranslated
messages["TEXT_REPLACE_MESSAGE0"] = "anstataŭigi tekston %1 per %2 en %3";
messages["TEXT_REPLACE_TOOLTIP"] = "Anstataŭigi ĉiujn okazojn de iu teksto en alia teksto.";
messages["TEXT_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#reversing-text";  // untranslated
messages["TEXT_REVERSE_MESSAGE0"] = "inversigi tekston %1";
messages["TEXT_REVERSE_TOOLTIP"] = "Inversigi la ordon de la skribsignoj en la teksto.";
messages["TEXT_TEXT_HELPURL"] = "https://eo.wikipedia.org/wiki/Signoĉeno";
messages["TEXT_TEXT_TOOLTIP"] = "Litero, vorto, aŭ linio da teksto.";
messages["TEXT_TRIM_HELPURL"] = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
messages["TEXT_TRIM_OPERATOR_BOTH"] = "forigi spacetojn for de ambaŭ finoj de";
messages["TEXT_TRIM_OPERATOR_LEFT"] = "forigi spacetojn for de maldekstra fino de";
messages["TEXT_TRIM_OPERATOR_RIGHT"] = "forigi spacetojn for de dekstra fino de";
messages["TEXT_TRIM_TOOLTIP"] = "Liveras kopion de teksto, de kies fino(j) spacetoj foriĝis.";
messages["TODAY"] = "Hodiaŭ";
messages["UNDO"] = "Malfari";
messages["UNNAMED_KEY"] = "nenomita";
messages["VARIABLES_DEFAULT_NAME"] = "elemento";
messages["VARIABLES_GET_CREATE_SET"] = "Krei blokon 'difini variablon %1'";
messages["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
messages["VARIABLES_GET_TOOLTIP"] = "Liveras la valoron de ĉi tiu variablo.";
messages["VARIABLES_SET"] = "difini %1 kiel %2";
messages["VARIABLES_SET_CREATE_GET"] = "Krei blokon 'akiri variablon %1'";
messages["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
messages["VARIABLES_SET_TOOLTIP"] = "Difinas ĉi tiun variablon kiel la eniron.";
messages["VARIABLE_ALREADY_EXISTS"] = "Jam ekzistas variablo kun la nomo '%1'.";
messages["VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE"] = "Jam ekzistas variablo kun la nomo '%1' por alia tipo: '%2'.";
messages["WORKSPACE_ARIA_LABEL"] = "Laborspaco de Blockly";
messages["WORKSPACE_COMMENT_DEFAULT_TEXT"] = "Diru ion…";
messages["CONTROLS_FOREACH_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_FOR_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = messages["CONTROLS_IF_MSG_ELSEIF"];
messages["CONTROLS_IF_ELSE_TITLE_ELSE"] = messages["CONTROLS_IF_MSG_ELSE"];
messages["CONTROLS_IF_IF_TITLE_IF"] = messages["CONTROLS_IF_MSG_IF"];
messages["CONTROLS_IF_MSG_THEN"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_WHILEUNTIL_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["LISTS_CREATE_WITH_ITEM_TITLE"] = messages["VARIABLES_DEFAULT_NAME"];
messages["LISTS_GET_INDEX_HELPURL"] = messages["LISTS_INDEX_OF_HELPURL"];
messages["LISTS_GET_INDEX_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_GET_SUBLIST_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_INDEX_OF_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_SET_INDEX_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["MATH_CHANGE_TITLE_ITEM"] = messages["VARIABLES_DEFAULT_NAME"];
messages["PROCEDURES_DEFRETURN_COMMENT"] = messages["PROCEDURES_DEFNORETURN_COMMENT"];
messages["PROCEDURES_DEFRETURN_DO"] = messages["PROCEDURES_DEFNORETURN_DO"];
messages["PROCEDURES_DEFRETURN_PROCEDURE"] = messages["PROCEDURES_DEFNORETURN_PROCEDURE"];
messages["PROCEDURES_DEFRETURN_TITLE"] = messages["PROCEDURES_DEFNORETURN_TITLE"];
messages["TEXT_APPEND_VARIABLE"] = messages["VARIABLES_DEFAULT_NAME"];
messages["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = messages["VARIABLES_DEFAULT_NAME"];

messages["MATH_HUE"] = "230";
messages["LOOPS_HUE"] = "120";
messages["LISTS_HUE"] = "260";
messages["LOGIC_HUE"] = "210";
messages["VARIABLES_HUE"] = "330";
messages["TEXTS_HUE"] = "160";
messages["PROCEDURES_HUE"] = "290";
messages["COLOUR_HUE"] = "20";
messages["VARIABLES_DYNAMIC_HUE"] = "310";