// This file was automatically generated.  Do not modify.

'use strict';

const messages = Object.create(null);

messages["ADD_COMMENT"] = "Tambahkan Komentar";
messages["CANNOT_DELETE_VARIABLE_PROCEDURE"] = "Tidak bisa menghapus variabel '%1' karena variabel ini bagian dari sebuah definisi dari fungsi '%2'";
messages["CHANGE_VALUE_TITLE"] = "Ubah nilai:";
messages["CLEAN_UP"] = "Bersihkan Blok";
messages["COLLAPSED_WARNINGS_WARNING"] = "Blok yang diciutkan memiliki peringatan.";
messages["COLLAPSE_ALL"] = "Ciutkan Blok";
messages["COLLAPSE_BLOCK"] = "Ciutkan Blok";
messages["COLOUR_BLEND_COLOUR1"] = "warna 1";
messages["COLOUR_BLEND_COLOUR2"] = "warna 2";
messages["COLOUR_BLEND_HELPURL"] = "http://meyerweb.com/eric/tools/color-blend/";
messages["COLOUR_BLEND_RATIO"] = "rasio";
messages["COLOUR_BLEND_TITLE"] = "campur";
messages["COLOUR_BLEND_TOOLTIP"] = "Campur dua warna secara bersamaan dengan perbandingan (0.0 - 1.0).";
messages["COLOUR_PICKER_HELPURL"] = "https://en.wikipedia.org/wiki/Color";
messages["COLOUR_PICKER_TOOLTIP"] = "Pilih warna dari daftar warna.";
messages["COLOUR_RANDOM_HELPURL"] = "http://randomcolour.com";  // untranslated
messages["COLOUR_RANDOM_TITLE"] = "Warna acak";
messages["COLOUR_RANDOM_TOOLTIP"] = "Pilih warna secara acak.";
messages["COLOUR_RGB_BLUE"] = "biru";
messages["COLOUR_RGB_GREEN"] = "hijau";
messages["COLOUR_RGB_HELPURL"] = "http://www.december.com/html/spec/colorper.html";
messages["COLOUR_RGB_RED"] = "merah";
messages["COLOUR_RGB_TITLE"] = "Dengan warna";
messages["COLOUR_RGB_TOOLTIP"] = "Buatlah warna dengan jumlah yang ditentukan dari merah, hijau dan biru. Semua nilai harus antarai 0 sampai 100.";
messages["CONTROLS_FLOW_STATEMENTS_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
messages["CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK"] = "keluar dari perulangan";
messages["CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE"] = "lanjutkan dengan langkah perulangan berikutnya";
messages["CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK"] = "Keluar dari perulangan.";
messages["CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE"] = "Abaikan sisa dari perulangan ini, dan lanjutkan dengan langkah berikutnya.";
messages["CONTROLS_FLOW_STATEMENTS_WARNING"] = "Peringatan: Blok ini hanya dapat digunakan dalam perulangan.";
messages["CONTROLS_FOREACH_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
messages["CONTROLS_FOREACH_TITLE"] = "untuk setiap item %1 di dalam list %2";
messages["CONTROLS_FOREACH_TOOLTIP"] = "Untuk tiap-tiap item di dalam list, tetapkan variabel '%1' ke dalam item, selanjutnya kerjakan beberapa statement.";
messages["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
messages["CONTROLS_FOR_TITLE"] = "Cacah dengan %1 dari %2 ke %3 dengan step / penambahan %4";
messages["CONTROLS_FOR_TOOLTIP"] = "Menggunakan variabel \"%1\" dengan mengambil nilai dari batas awal hingga ke batas akhir, dengan interval tertentu, dan mengerjakan block tertentu.";
messages["CONTROLS_IF_ELSEIF_TOOLTIP"] = "Tambahkan prasyarat ke dalam blok IF.";
messages["CONTROLS_IF_ELSE_TOOLTIP"] = "Terakhir, tambahkan kondisi tangkap-semua kedalam blok IF.";
messages["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
messages["CONTROLS_IF_IF_TOOLTIP"] = "Tambahkan, hapus, atau susun kembali bagian untuk mengkonfigurasi blok IF ini.";
messages["CONTROLS_IF_MSG_ELSE"] = "lainnya";
messages["CONTROLS_IF_MSG_ELSEIF"] = "atau jika";
messages["CONTROLS_IF_MSG_IF"] = "jika";
messages["CONTROLS_IF_TOOLTIP_1"] = "Jika nilainya benar, maka lakukan beberapa perintah.";
messages["CONTROLS_IF_TOOLTIP_2"] = "Jika nilainya benar, maka kerjakan perintah blok pertama. Jika tidak, kerjakan perintah blok kedua.";
messages["CONTROLS_IF_TOOLTIP_3"] = "Jika nilai pertama benar, maka kerjakan perintah blok pertama. Sebaliknya, jika nilai kedua benar, kerjakan perintah blok kedua.";
messages["CONTROLS_IF_TOOLTIP_4"] = "Jika nilai pertama benar, maka kerjakan perintah blok pertama. Sebaliknya, jika nilai kedua benar, kerjakan perintah blok kedua. Jika dua-duanya tidak benar, kerjakan perintah blok terakhir.";
messages["CONTROLS_REPEAT_HELPURL"] = "https://en.wikipedia.org/wiki/For_loop";
messages["CONTROLS_REPEAT_INPUT_DO"] = "kerjakan";
messages["CONTROLS_REPEAT_TITLE"] = "ulangi %1 kali";
messages["CONTROLS_REPEAT_TOOLTIP"] = "Lakukan beberapa perintah beberapa kali.";
messages["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
messages["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "ulangi sampai";
messages["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "ulangi jika";
messages["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "Selagi nilainya salah, maka lakukan beberapa perintah.";
messages["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "Selagi nilainya benar, maka lakukan beberapa perintah.";
messages["DELETE_ALL_BLOCKS"] = "Hapus semua %1 blok?";
messages["DELETE_BLOCK"] = "Hapus Blok";
messages["DELETE_VARIABLE"] = "Hapus variabel '%1'";
messages["DELETE_VARIABLE_CONFIRMATION"] = "Hapus %1 yang digunakan pada variabel '%2'?";
messages["DELETE_X_BLOCKS"] = "Hapus %1 Blok";
messages["DIALOG_CANCEL"] = "Batal";
messages["DIALOG_OK"] = "Oke";
messages["DISABLE_BLOCK"] = "Nonaktifkan Blok";
messages["DUPLICATE_BLOCK"] = "Duplikat";
messages["DUPLICATE_COMMENT"] = "Duplikat Komentar";
messages["ENABLE_BLOCK"] = "Aktifkan Blok";
messages["EXPAND_ALL"] = "Kembangkan Blok";
messages["EXPAND_BLOCK"] = "Kembangkan Blok";
messages["EXTERNAL_INPUTS"] = "Input Eksternal";
messages["HELP"] = "Bantuan";
messages["INLINE_INPUTS"] = "Input Inline";
messages["LISTS_CREATE_EMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-empty-list";
messages["LISTS_CREATE_EMPTY_TITLE"] = "buat list kosong";
messages["LISTS_CREATE_EMPTY_TOOLTIP"] = "Kembalikan list, dengan panjang 0, tidak berisi data";
messages["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "list";
messages["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "Tambahkan, hapus, atau susun ulang bagian untuk mengkonfigurasi blok list ini.";
messages["LISTS_CREATE_WITH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
messages["LISTS_CREATE_WITH_INPUT_WITH"] = "buat list dengan";
messages["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "Tambahkan sebuah item ke list.";
messages["LISTS_CREATE_WITH_TOOLTIP"] = "Buat sebuah list dengan sejumlah item.";
messages["LISTS_GET_INDEX_FIRST"] = "pertama";
messages["LISTS_GET_INDEX_FROM_END"] = "# dari akhir";
messages["LISTS_GET_INDEX_FROM_START"] = "#";
messages["LISTS_GET_INDEX_GET"] = "dapatkan";
messages["LISTS_GET_INDEX_GET_REMOVE"] = "dapatkan dan hapus";
messages["LISTS_GET_INDEX_LAST"] = "terakhir";
messages["LISTS_GET_INDEX_RANDOM"] = "acak";
messages["LISTS_GET_INDEX_REMOVE"] = "Hapus";
messages["LISTS_GET_INDEX_TAIL"] = "";  // untranslated
messages["LISTS_GET_INDEX_TOOLTIP_GET_FIRST"] = "Kembalikan item pertama dalam list.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_FROM"] = "Kembalikan item di posisi tertentu dalam list.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_LAST"] = "Kembalikan item terakhir dalam list.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_RANDOM"] = "Kembalikan item acak dalam list.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST"] = "Hapus dan kembalikan item pertama dalam list.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM"] = "Hapus dan kembalikan item di posisi tertentu dalam list.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST"] = "Hapus dan kembalikan item terakhir dalam list.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM"] = "Hapus dan kembalikan item acak dalam list.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST"] = "Hapus item pertama dalam list.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM"] = "Hapus item di posisi tertentu dalam list.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST"] = "Hapus item terakhir dalam list.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM"] = "Hapus sebuah item acak dalam list.";
messages["LISTS_GET_SUBLIST_END_FROM_END"] = "ke # dari akhir";
messages["LISTS_GET_SUBLIST_END_FROM_START"] = "ke #";
messages["LISTS_GET_SUBLIST_END_LAST"] = "ke yang paling akhir";
messages["LISTS_GET_SUBLIST_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
messages["LISTS_GET_SUBLIST_START_FIRST"] = "dapatkan sub-list dari pertama";
messages["LISTS_GET_SUBLIST_START_FROM_END"] = "dapatkan sub-list dari nomor # dari akhir";
messages["LISTS_GET_SUBLIST_START_FROM_START"] = "dapatkan sub-list dari #";
messages["LISTS_GET_SUBLIST_TAIL"] = "";  // untranslated
messages["LISTS_GET_SUBLIST_TOOLTIP"] = "Buat salinan bagian tertentu dari list.";
messages["LISTS_INDEX_FROM_END_TOOLTIP"] = "%1 adalah item terakhir.";
messages["LISTS_INDEX_FROM_START_TOOLTIP"] = "%1 adalah item pertama.";
messages["LISTS_INDEX_OF_FIRST"] = "cari kejadian pertama item";
messages["LISTS_INDEX_OF_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
messages["LISTS_INDEX_OF_LAST"] = "cari kejadian terakhir item";
messages["LISTS_INDEX_OF_TOOLTIP"] = "Kembalikan indeks dari item pertama/terakhir kali muncul dalam list. Kembalikan %1 jika item tidak ditemukan.";
messages["LISTS_INLIST"] = "dalam list";
messages["LISTS_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
messages["LISTS_ISEMPTY_TITLE"] = "%1 kosong";
messages["LISTS_ISEMPTY_TOOLTIP"] = "Kembalikan benar jika list kosong.";
messages["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
messages["LISTS_LENGTH_TITLE"] = "panjang dari %1";
messages["LISTS_LENGTH_TOOLTIP"] = "Kembalikan panjang list.";
messages["LISTS_REPEAT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
messages["LISTS_REPEAT_TITLE"] = "buat list dengan item %1 diulang %2 kali";
messages["LISTS_REPEAT_TOOLTIP"] = "Buat sebuah list yang terdiri dari nilai yang diberikan diulang sebanyak jumlah yang ditentukan.";
messages["LISTS_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";  // untranslated
messages["LISTS_REVERSE_MESSAGE0"] = "balikkan %1";
messages["LISTS_REVERSE_TOOLTIP"] = "Balikkan salinan dari daftar.";
messages["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
messages["LISTS_SET_INDEX_INPUT_TO"] = "sebagai";
messages["LISTS_SET_INDEX_INSERT"] = "sisipkan di";
messages["LISTS_SET_INDEX_SET"] = "tetapkan";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST"] = "Sisipkan item di bagian awal dari list.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_FROM"] = "Sisipkan item ke dalam posisi yang telah ditentukan di dalam list.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_LAST"] = "Tambahkan item ke bagian akhir list.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM"] = "Sisipkan item secara acak ke dalam list.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_FIRST"] = "Tetapkan item pertama di dalam list.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_FROM"] = "Tetapkan item ke dalam posisi yang telah ditentukan di dalam list.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_LAST"] = "Menetapkan item terakhir dalam list.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_RANDOM"] = "Tetapkan secara acak sebuah item dalam list.";
messages["LISTS_SORT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
messages["LISTS_SORT_ORDER_ASCENDING"] = "menaik";
messages["LISTS_SORT_ORDER_DESCENDING"] = "menurun";
messages["LISTS_SORT_TITLE"] = "urutkan %1 %2 %3";
messages["LISTS_SORT_TOOLTIP"] = "Urutkan salinan dari daftar";
messages["LISTS_SORT_TYPE_IGNORECASE"] = "sesuai abjad, abaikan kasus";
messages["LISTS_SORT_TYPE_NUMERIC"] = "sesuai nomor";
messages["LISTS_SORT_TYPE_TEXT"] = "sesuai abjad";
messages["LISTS_SPLIT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
messages["LISTS_SPLIT_LIST_FROM_TEXT"] = "buat list dari teks";
messages["LISTS_SPLIT_TEXT_FROM_LIST"] = "buat teks dari list";
messages["LISTS_SPLIT_TOOLTIP_JOIN"] = "Gabung daftar teks menjadi satu teks, yang dipisahkan oleh pembatas.";
messages["LISTS_SPLIT_TOOLTIP_SPLIT"] = "Membagi teks ke dalam daftar teks, pisahkan pada setiap pembatas.";
messages["LISTS_SPLIT_WITH_DELIMITER"] = "dengan pembatas";
messages["LOGIC_BOOLEAN_FALSE"] = "salah";
messages["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
messages["LOGIC_BOOLEAN_TOOLTIP"] = "Kembalikan benar atau salah.";
messages["LOGIC_BOOLEAN_TRUE"] = "benar";
messages["LOGIC_COMPARE_HELPURL"] = "https://en.wikipedia.org/wiki/Inequality_(mathematics)";
messages["LOGIC_COMPARE_TOOLTIP_EQ"] = "Kembalikan benar jika kedua input sama satu dengan lainnya.";
messages["LOGIC_COMPARE_TOOLTIP_GT"] = "Kembalikan benar jika input pertama lebih besar dari input kedua.";
messages["LOGIC_COMPARE_TOOLTIP_GTE"] = "Kembalikan benar jika input pertama lebih besar dari atau sama dengan input kedua.";
messages["LOGIC_COMPARE_TOOLTIP_LT"] = "Kembalikan benar jika input pertama lebih kecil dari input kedua.";
messages["LOGIC_COMPARE_TOOLTIP_LTE"] = "Kembalikan benar jika input pertama lebih kecil atau sama dengan input kedua .";
messages["LOGIC_COMPARE_TOOLTIP_NEQ"] = "Kembalikan benar jika kedua input tidak sama satu dengan lainnya.";
messages["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
messages["LOGIC_NEGATE_TITLE"] = "bukan (not) %1";
messages["LOGIC_NEGATE_TOOLTIP"] = "Kembalikan benar jika input salah. Kembalikan salah jika input benar.";
messages["LOGIC_NULL"] = "null";
messages["LOGIC_NULL_HELPURL"] = "https://en.wikipedia.org/wiki/Nullable_type";
messages["LOGIC_NULL_TOOLTIP"] = "Kembalikan null.";
messages["LOGIC_OPERATION_AND"] = "dan";
messages["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
messages["LOGIC_OPERATION_OR"] = "atau";
messages["LOGIC_OPERATION_TOOLTIP_AND"] = "Kembalikan benar jika kedua input adalah benar.";
messages["LOGIC_OPERATION_TOOLTIP_OR"] = "Kembalikan benar jika minimal satu input nilainya benar.";
messages["LOGIC_TERNARY_CONDITION"] = "test";
messages["LOGIC_TERNARY_HELPURL"] = "https://en.wikipedia.org/wiki/%3F:";
messages["LOGIC_TERNARY_IF_FALSE"] = "jika salah";
messages["LOGIC_TERNARY_IF_TRUE"] = "jika benar";
messages["LOGIC_TERNARY_TOOLTIP"] = "Periksa kondisi di 'test'. Jika kondisi benar, kembalikan nilai 'if true'; jika sebaliknya kembalikan nilai 'if false'.";
messages["MATH_ADDITION_SYMBOL"] = "+";
messages["MATH_ARITHMETIC_HELPURL"] = "https://id.wikipedia.org/wiki/Aritmetika";
messages["MATH_ARITHMETIC_TOOLTIP_ADD"] = "Kembalikan jumlah dari kedua angka.";
messages["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "Kembalikan hasil bagi dari kedua angka.";
messages["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "Kembalikan selisih dari kedua angka.";
messages["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "Kembalikan perkalian dari kedua angka.";
messages["MATH_ARITHMETIC_TOOLTIP_POWER"] = "Kembalikan angka pertama pangkat angka kedua.";
messages["MATH_ATAN2_HELPURL"] = "https://en.wikipedia.org/wiki/Atan2";
messages["MATH_ATAN2_TITLE"] = "atan2 of X:%1 Y:%2";
messages["MATH_ATAN2_TOOLTIP"] = "Kembalikan arctangen titik (X, Y) dalam derajat dari -180 hingga 180.";
messages["MATH_CHANGE_HELPURL"] = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
messages["MATH_CHANGE_TITLE"] = "ubah %1 oleh %2";
messages["MATH_CHANGE_TOOLTIP"] = "Tambahkan angka kedalam variabel '%1'.";
messages["MATH_CONSTANT_HELPURL"] = "https://en.wikipedia.org/wiki/Mathematical_constant";
messages["MATH_CONSTANT_TOOLTIP"] = "Kembalikan salah satu konstanta: π (3,141…), e (2,718…), φ (1,618…), akar(2) (1,414…), akar(½) (0.707…), atau ∞ (tak terhingga).";
messages["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
messages["MATH_CONSTRAIN_TITLE"] = "Batasi %1 rendah %2 tinggi %3";
messages["MATH_CONSTRAIN_TOOLTIP"] = "Batasi angka antara batas yang ditentukan (inklusif).";
messages["MATH_DIVISION_SYMBOL"] = "÷";
messages["MATH_IS_DIVISIBLE_BY"] = "dapat dibagi oleh";
messages["MATH_IS_EVEN"] = "adalah bilangan genap";
messages["MATH_IS_NEGATIVE"] = "adalah bilangan negatif";
messages["MATH_IS_ODD"] = "adalah bilangan ganjil";
messages["MATH_IS_POSITIVE"] = "adalah bilangan positif";
messages["MATH_IS_PRIME"] = "adalah bilangan pokok";
messages["MATH_IS_TOOLTIP"] = "Periksa apakah angka adalah bilangan genap, bilangan ganjil, bilangan pokok, bilangan bulat, bilangan positif, bilangan negatif, atau apakan bisa dibagi oleh angka tertentu. Kembalikan benar atau salah.";
messages["MATH_IS_WHOLE"] = "adalah bilangan bulat";
messages["MATH_MODULO_HELPURL"] = "https://en.wikipedia.org/wiki/Modulo_operation";
messages["MATH_MODULO_TITLE"] = "sisa dari %1 ÷ %2";
messages["MATH_MODULO_TOOLTIP"] = "Kembalikan sisa dari pembagian ke dua angka.";
messages["MATH_MULTIPLICATION_SYMBOL"] = "×";
messages["MATH_NUMBER_HELPURL"] = "https://en.wikipedia.org/wiki/Number";
messages["MATH_NUMBER_TOOLTIP"] = "Suatu angka.";
messages["MATH_ONLIST_HELPURL"] = "";  // untranslated
messages["MATH_ONLIST_OPERATOR_AVERAGE"] = "rata-rata dari list";
messages["MATH_ONLIST_OPERATOR_MAX"] = "maksimum dari list";
messages["MATH_ONLIST_OPERATOR_MEDIAN"] = "median dari list";
messages["MATH_ONLIST_OPERATOR_MIN"] = "minimum dari list";
messages["MATH_ONLIST_OPERATOR_MODE"] = "mode-mode dari list";
messages["MATH_ONLIST_OPERATOR_RANDOM"] = "item acak dari list";
messages["MATH_ONLIST_OPERATOR_STD_DEV"] = "deviasi standar dari list";
messages["MATH_ONLIST_OPERATOR_SUM"] = "jumlah dari list";
messages["MATH_ONLIST_TOOLTIP_AVERAGE"] = "Kembalikan rata-rata (mean aritmetik) dari nilai numerik dari list.";
messages["MATH_ONLIST_TOOLTIP_MAX"] = "Kembalikan angka terbesar dari list.";
messages["MATH_ONLIST_TOOLTIP_MEDIAN"] = "Kembalikan median dari list.";
messages["MATH_ONLIST_TOOLTIP_MIN"] = "Kembalikan angka terkecil dari list.";
messages["MATH_ONLIST_TOOLTIP_MODE"] = "Kembalikan list berisi item yang paling umum dari dalam list.";
messages["MATH_ONLIST_TOOLTIP_RANDOM"] = "Kembalikan elemen acak dari list.";
messages["MATH_ONLIST_TOOLTIP_STD_DEV"] = "Kembalikan standard deviasi dari list.";
messages["MATH_ONLIST_TOOLTIP_SUM"] = "Kembalikan jumlah dari seluruh bilangan dari list.";
messages["MATH_POWER_SYMBOL"] = "^";
messages["MATH_RANDOM_FLOAT_HELPURL"] = "https://en.wikipedia.org/wiki/Random_number_generation";
messages["MATH_RANDOM_FLOAT_TITLE_RANDOM"] = "nilai pecahan acak";
messages["MATH_RANDOM_FLOAT_TOOLTIP"] = "Kembalikan nilai pecahan acak antara 0.0 (inklusif) dan 1.0 (eksklusif).";
messages["MATH_RANDOM_INT_HELPURL"] = "https://en.wikipedia.org/wiki/Random_number_generation";
messages["MATH_RANDOM_INT_TITLE"] = "acak bulat dari %1 sampai %2";
messages["MATH_RANDOM_INT_TOOLTIP"] = "Kembalikan bilangan acak antara dua batas yang ditentukan, inklusif.";
messages["MATH_ROUND_HELPURL"] = "https://en.wikipedia.org/wiki/Rounding";
messages["MATH_ROUND_OPERATOR_ROUND"] = "membulatkan";
messages["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "membulatkan kebawah";
messages["MATH_ROUND_OPERATOR_ROUNDUP"] = "membulatkan keatas";
messages["MATH_ROUND_TOOLTIP"] = "Bulatkan suatu bilangan naik atau turun.";
messages["MATH_SINGLE_HELPURL"] = "https://en.wikipedia.org/wiki/Square_root";
messages["MATH_SINGLE_OP_ABSOLUTE"] = "mutlak";
messages["MATH_SINGLE_OP_ROOT"] = "akar";
messages["MATH_SINGLE_TOOLTIP_ABS"] = "Kembalikan nilai absolut angka.";
messages["MATH_SINGLE_TOOLTIP_EXP"] = "Kembalikan 10 pangkat angka.";
messages["MATH_SINGLE_TOOLTIP_LN"] = "Kembalikan logaritma natural dari angka.";
messages["MATH_SINGLE_TOOLTIP_LOG10"] = "Kembalikan dasar logaritma 10 dari angka.";
messages["MATH_SINGLE_TOOLTIP_NEG"] = "Kembalikan penyangkalan terhadap angka.";
messages["MATH_SINGLE_TOOLTIP_POW10"] = "Kembalikan 10 pangkat angka.";
messages["MATH_SINGLE_TOOLTIP_ROOT"] = "Kembalikan akar dari angka.";
messages["MATH_SUBTRACTION_SYMBOL"] = "-";
messages["MATH_TRIG_ACOS"] = "acos";
messages["MATH_TRIG_ASIN"] = "asin";
messages["MATH_TRIG_ATAN"] = "atan";
messages["MATH_TRIG_COS"] = "cos";
messages["MATH_TRIG_HELPURL"] = "https://en.wikipedia.org/wiki/Trigonometric_functions";
messages["MATH_TRIG_SIN"] = "sin";
messages["MATH_TRIG_TAN"] = "tan";
messages["MATH_TRIG_TOOLTIP_ACOS"] = "Kembalikan acosine dari angka.";
messages["MATH_TRIG_TOOLTIP_ASIN"] = "Kembalikan asin dari angka.";
messages["MATH_TRIG_TOOLTIP_ATAN"] = "Kembalikan atan dari angka.";
messages["MATH_TRIG_TOOLTIP_COS"] = "Kembalikan cosinus dari derajat (bukan radian).";
messages["MATH_TRIG_TOOLTIP_SIN"] = "Kembalikan sinus dari derajat (bukan radian).";
messages["MATH_TRIG_TOOLTIP_TAN"] = "Kembalikan tangen dari derajat (bukan radian).";
messages["NEW_COLOUR_VARIABLE"] = "Buat variabel warna...";
messages["NEW_NUMBER_VARIABLE"] = "Buat variabel number...";
messages["NEW_STRING_VARIABLE"] = "Buat variabel string...";
messages["NEW_VARIABLE"] = "Buat variabel...";
messages["NEW_VARIABLE_TITLE"] = "Nama variabel baru:";
messages["NEW_VARIABLE_TYPE_TITLE"] = "Tipe variabel baru:";
messages["ORDINAL_NUMBER_SUFFIX"] = "";  // untranslated
messages["PROCEDURES_ALLOW_STATEMENTS"] = "memungkinkan pernyataan";
messages["PROCEDURES_BEFORE_PARAMS"] = "dengan:";
messages["PROCEDURES_CALLNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
messages["PROCEDURES_CALLNORETURN_TOOLTIP"] = "Menjalankan fungsi '%1' yang ditetapkan pengguna.";
messages["PROCEDURES_CALLRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
messages["PROCEDURES_CALLRETURN_TOOLTIP"] = "Menjalankan fungsi  '%1' yang ditetapkan pengguna dan menggunakan outputnya.";
messages["PROCEDURES_CALL_BEFORE_PARAMS"] = "dengan:";
messages["PROCEDURES_CREATE_DO"] = "Buat '%1'";
messages["PROCEDURES_DEFNORETURN_COMMENT"] = "Jelaskan fungsi ini...";
messages["PROCEDURES_DEFNORETURN_DO"] = "";  // untranslated
messages["PROCEDURES_DEFNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
messages["PROCEDURES_DEFNORETURN_PROCEDURE"] = "buat sesuatu";
messages["PROCEDURES_DEFNORETURN_TITLE"] = "untuk";
messages["PROCEDURES_DEFNORETURN_TOOLTIP"] = "Buat sebuah fungsi tanpa output.";
messages["PROCEDURES_DEFRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
messages["PROCEDURES_DEFRETURN_RETURN"] = "kembali";
messages["PROCEDURES_DEFRETURN_TOOLTIP"] = "Buat sebuah fungsi dengan satu output.";
messages["PROCEDURES_DEF_DUPLICATE_WARNING"] = "Peringatan: Fungsi ini memiliki parameter duplikat.";
messages["PROCEDURES_HIGHLIGHT_DEF"] = "Sorot definisi fungsi";
messages["PROCEDURES_IFRETURN_HELPURL"] = "http://c2.com/cgi/wiki?GuardClause";  // untranslated
messages["PROCEDURES_IFRETURN_TOOLTIP"] = "Jika nilai yang benar, kemudian kembalikan nilai kedua.";
messages["PROCEDURES_IFRETURN_WARNING"] = "Peringatan: Blok ini dapat digunakan hanya dalam definisi fungsi.";
messages["PROCEDURES_MUTATORARG_TITLE"] = "masukan Nama:";
messages["PROCEDURES_MUTATORARG_TOOLTIP"] = "Tambahkan masukan ke fungsi.";
messages["PROCEDURES_MUTATORCONTAINER_TITLE"] = "input";
messages["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "Menambah, menghapus, atau menyusun ulang masukan untuk fungsi ini.";
messages["REDO"] = "Lakukan ulang";
messages["REMOVE_COMMENT"] = "Hapus Komentar";
messages["RENAME_VARIABLE"] = "Ubah nama variabel...";
messages["RENAME_VARIABLE_TITLE"] = "Ubah nama semua variabel '%1' menjadi:";
messages["TEXT_APPEND_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
messages["TEXT_APPEND_TITLE"] = "untuk %1 tambahkan teks %2";
messages["TEXT_APPEND_TOOLTIP"] = "Tambahkan beberapa teks ke variabel '%1'.";
messages["TEXT_CHANGECASE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
messages["TEXT_CHANGECASE_OPERATOR_LOWERCASE"] = "menjadi huruf kecil";
messages["TEXT_CHANGECASE_OPERATOR_TITLECASE"] = "menjadi huruf pertama kapital";
messages["TEXT_CHANGECASE_OPERATOR_UPPERCASE"] = "menjadi huruf kapital";
messages["TEXT_CHANGECASE_TOOLTIP"] = "Kembalikan kopi dari text dengan kapitalisasi yang berbeda.";
messages["TEXT_CHARAT_FIRST"] = "ambil  huruf pertama";
messages["TEXT_CHARAT_FROM_END"] = "ambil  huruf nomor # dari belakang";
messages["TEXT_CHARAT_FROM_START"] = "ambil huruf ke #";
messages["TEXT_CHARAT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
messages["TEXT_CHARAT_LAST"] = "ambil  huruf terakhir";
messages["TEXT_CHARAT_RANDOM"] = "ambil huruf secara acak";
messages["TEXT_CHARAT_TAIL"] = "";  // untranslated
messages["TEXT_CHARAT_TITLE"] = "dalam teks %1 %2";
messages["TEXT_CHARAT_TOOLTIP"] = "Kembalikan karakter dari posisi tertentu.";
messages["TEXT_COUNT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#counting-substrings";  // untranslated
messages["TEXT_COUNT_MESSAGE0"] = "hitung %1 dalam %2";
messages["TEXT_COUNT_TOOLTIP"] = "Hitung berapa banyak teks muncul dalam teks lain.";
messages["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "Tambahkan suatu item ke dalam teks.";
messages["TEXT_CREATE_JOIN_TITLE_JOIN"] = "join";
messages["TEXT_CREATE_JOIN_TOOLTIP"] = "Tambah, ambil, atau susun ulang teks blok.";
messages["TEXT_GET_SUBSTRING_END_FROM_END"] = "pada huruf nomer # dari terakhir";
messages["TEXT_GET_SUBSTRING_END_FROM_START"] = "pada huruf #";
messages["TEXT_GET_SUBSTRING_END_LAST"] = "pada huruf terakhir";
messages["TEXT_GET_SUBSTRING_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
messages["TEXT_GET_SUBSTRING_INPUT_IN_TEXT"] = "in teks";
messages["TEXT_GET_SUBSTRING_START_FIRST"] = "ambil bagian teks (substring) dari huruf pertama";
messages["TEXT_GET_SUBSTRING_START_FROM_END"] = "ambil bagian teks (substring) dari huruf ke # dari terakhir";
messages["TEXT_GET_SUBSTRING_START_FROM_START"] = "ambil bagian teks (substring) dari huruf no #";
messages["TEXT_GET_SUBSTRING_TAIL"] = "";  // untranslated
messages["TEXT_GET_SUBSTRING_TOOLTIP"] = "Kembalikan spesifik bagian dari teks.";
messages["TEXT_INDEXOF_HELPURL"] = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
messages["TEXT_INDEXOF_OPERATOR_FIRST"] = "temukan kejadian pertama dalam teks";
messages["TEXT_INDEXOF_OPERATOR_LAST"] = "temukan kejadian terakhir dalam teks";
messages["TEXT_INDEXOF_TITLE"] = "dalam teks %1 %2 %3";
messages["TEXT_INDEXOF_TOOLTIP"] = "Kembalikan indeks pertama dan terakhir dari kejadian pertama/terakhir dari teks pertama dalam teks kedua.  Kembalikan %1 jika teks tidak ditemukan.";
messages["TEXT_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
messages["TEXT_ISEMPTY_TITLE"] = "%1 kosong";
messages["TEXT_ISEMPTY_TOOLTIP"] = "Kembalikan benar jika teks yang disediakan kosong.";
messages["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
messages["TEXT_JOIN_TITLE_CREATEWITH"] = "buat teks dengan";
messages["TEXT_JOIN_TOOLTIP"] = "Buat teks dengan cara gabungkan sejumlah item.";
messages["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
messages["TEXT_LENGTH_TITLE"] = "panjang dari %1";
messages["TEXT_LENGTH_TOOLTIP"] = "Kembalikan sejumlah huruf (termasuk spasi) dari teks yang disediakan.";
messages["TEXT_PRINT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
messages["TEXT_PRINT_TITLE"] = "cetak %1";
messages["TEXT_PRINT_TOOLTIP"] = "Cetak teks yant ditentukan, angka atau ninlai lainnya.";
messages["TEXT_PROMPT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
messages["TEXT_PROMPT_TOOLTIP_NUMBER"] = "Meminta pengguna untuk memberi sebuah angka.";
messages["TEXT_PROMPT_TOOLTIP_TEXT"] = "Meminta pengguna untuk memberi beberapa teks.";
messages["TEXT_PROMPT_TYPE_NUMBER"] = "Meminta angka dengan pesan";
messages["TEXT_PROMPT_TYPE_TEXT"] = "meminta teks dengan pesan";
messages["TEXT_REPLACE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#replacing-substrings";  // untranslated
messages["TEXT_REPLACE_MESSAGE0"] = "ganti %1 dengan %2 dalam %3";
messages["TEXT_REPLACE_TOOLTIP"] = "Ganti semua kemunculan teks dalam teks lain.";
messages["TEXT_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#reversing-text";  // untranslated
messages["TEXT_REVERSE_MESSAGE0"] = "balikkan %1";
messages["TEXT_REVERSE_TOOLTIP"] = "Balikkan urutan huruf dalam teks.";
messages["TEXT_TEXT_HELPURL"] = "https://en.wikipedia.org/wiki/String_(computer_science)";
messages["TEXT_TEXT_TOOLTIP"] = "Huruf, kata atau baris teks.";
messages["TEXT_TRIM_HELPURL"] = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
messages["TEXT_TRIM_OPERATOR_BOTH"] = "pangkas ruang dari kedua belah sisi";
messages["TEXT_TRIM_OPERATOR_LEFT"] = "pangkas ruang dari sisi kiri";
messages["TEXT_TRIM_OPERATOR_RIGHT"] = "pangkas ruang dari sisi kanan";
messages["TEXT_TRIM_TOOLTIP"] = "Kembali salinan teks dengan spasi dihapus dari satu atau kedua ujungnya.";
messages["TODAY"] = "Hari ini";
messages["UNDO"] = "Urungkan";
messages["UNNAMED_KEY"] = "tanpa nama";
messages["VARIABLES_DEFAULT_NAME"] = "item";
messages["VARIABLES_GET_CREATE_SET"] = "Buat 'set %1'";
messages["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
messages["VARIABLES_GET_TOOLTIP"] = "Kembalikan nilai variabel ini.";
messages["VARIABLES_SET"] = "tetapkan %1 untuk %2";
messages["VARIABLES_SET_CREATE_GET"] = "Buat 'get %1'";
messages["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
messages["VARIABLES_SET_TOOLTIP"] = "tetapkan variabel ini dengan input yang sama.";
messages["VARIABLE_ALREADY_EXISTS"] = "Sebuah variabel dengan nama '%1' sudah ada.";
messages["VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE"] = "Variabel yg bernama '%1' sudah ada untuk tipe lain: '%2'.";
messages["WORKSPACE_ARIA_LABEL"] = "Ruang Kerja Blockly";
messages["WORKSPACE_COMMENT_DEFAULT_TEXT"] = "Ucapkan sesuatu...";
messages["CONTROLS_FOREACH_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_FOR_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = messages["CONTROLS_IF_MSG_ELSEIF"];
messages["CONTROLS_IF_ELSE_TITLE_ELSE"] = messages["CONTROLS_IF_MSG_ELSE"];
messages["CONTROLS_IF_IF_TITLE_IF"] = messages["CONTROLS_IF_MSG_IF"];
messages["CONTROLS_IF_MSG_THEN"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_WHILEUNTIL_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["LISTS_CREATE_WITH_ITEM_TITLE"] = messages["VARIABLES_DEFAULT_NAME"];
messages["LISTS_GET_INDEX_HELPURL"] = messages["LISTS_INDEX_OF_HELPURL"];
messages["LISTS_GET_INDEX_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_GET_SUBLIST_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_INDEX_OF_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_SET_INDEX_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["MATH_CHANGE_TITLE_ITEM"] = messages["VARIABLES_DEFAULT_NAME"];
messages["PROCEDURES_DEFRETURN_COMMENT"] = messages["PROCEDURES_DEFNORETURN_COMMENT"];
messages["PROCEDURES_DEFRETURN_DO"] = messages["PROCEDURES_DEFNORETURN_DO"];
messages["PROCEDURES_DEFRETURN_PROCEDURE"] = messages["PROCEDURES_DEFNORETURN_PROCEDURE"];
messages["PROCEDURES_DEFRETURN_TITLE"] = messages["PROCEDURES_DEFNORETURN_TITLE"];
messages["TEXT_APPEND_VARIABLE"] = messages["VARIABLES_DEFAULT_NAME"];
messages["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = messages["VARIABLES_DEFAULT_NAME"];

messages["MATH_HUE"] = "230";
messages["LOOPS_HUE"] = "120";
messages["LISTS_HUE"] = "260";
messages["LOGIC_HUE"] = "210";
messages["VARIABLES_HUE"] = "330";
messages["TEXTS_HUE"] = "160";
messages["PROCEDURES_HUE"] = "290";
messages["COLOUR_HUE"] = "20";
messages["VARIABLES_DYNAMIC_HUE"] = "310";