// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.kab');

goog.require('Blockly.Msg');

/** @export */ Blockly.Msg.ADD_COMMENT = "Rnu awennit";
/** @export */ Blockly.Msg.CANNOT_DELETE_VARIABLE_PROCEDURE = "Ur izmir ara ad yekkes amutti '%1' acku yedda di tbadut n twuri '%2'";
/** @export */ Blockly.Msg.CHANGE_VALUE_TITLE = "Beddel azal:";
/** @export */ Blockly.Msg.CLEAN_UP = "Sfeḍ iḥedran";
/** @export */ Blockly.Msg.COLLAPSE_ALL = "Fneẓ iḥedran";
/** @export */ Blockly.Msg.COLLAPSE_BLOCK = "Fneẓ iḥder";
/** @export */ Blockly.Msg.COLOUR_BLEND_COLOUR1 = "ini 1";
/** @export */ Blockly.Msg.COLOUR_BLEND_COLOUR2 = "ini 2";
/** @export */ Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
/** @export */ Blockly.Msg.COLOUR_BLEND_RATIO = "afmiḍi";
/** @export */ Blockly.Msg.COLOUR_BLEND_TITLE = "rkwec";
/** @export */ Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Sexleḍ sin n yiniten d tesmekta (gar 0.0 ar 1.0).";
/** @export */ Blockly.Msg.COLOUR_PICKER_HELPURL = "https://kab.wikipedia.org/wiki/Ini";
/** @export */ Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Fren ini seg ugalis.";
/** @export */ Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
/** @export */ Blockly.Msg.COLOUR_RANDOM_TITLE = "ini agacuran";
/** @export */ Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Fren ini s wudem agacuran.";
/** @export */ Blockly.Msg.COLOUR_RGB_BLUE = "anili";
/** @export */ Blockly.Msg.COLOUR_RGB_GREEN = "azegzaw";
/** @export */ Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
/** @export */ Blockly.Msg.COLOUR_RGB_RED = "azeggwaɣ";
/** @export */ Blockly.Msg.COLOUR_RGB_TITLE = "ini s";
/** @export */ Blockly.Msg.COLOUR_RGB_TOOLTIP = "Rnu ini s tnecta yettunefk s tesmekta n uzeggaɣ, azegzaw, akked unili. Yessefk akk azalen ad ilin gar 0 akked 100.";
/** @export */ Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
/** @export */ Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "ffeɣ seg tneddict";
/** @export */ Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "kemmel s wallus d tneddict d-iteddun";
/** @export */ Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Ffeɣ si tneddict tamagbart.";
/** @export */ Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Zgel ayen i d-yeqqimen di tneddict-agi, sakin kemmel allus d-iteddun.";
/** @export */ Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Ɣur-k: Iḥder-agi yessefk ad yettwaseqdec di tneddict.";
/** @export */ Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
/** @export */ Blockly.Msg.CONTROLS_FOREACH_TITLE = "i yal aferdis  %1 di tebdart %2";
/** @export */ Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "I yal aferdis n tebdart, mudd azal n uferdis i umutti '%1', sakin selkem tinaḍin.";
/** @export */ Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
/** @export */ Blockly.Msg.CONTROLS_FOR_TITLE = "siḍen akked %1 seg %2 ar %3 s %4";
/** @export */ Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Mudd i umutti '%1' azalen seg umḍan n tazwara arama d umḍan n tagara, stmerna n usurif yettunefken, sakin selkem tiaḍin yettunefken.";
/** @export */ Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Rni tawtilt i yiḥder ma.";
/** @export */ Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Rnu tawtilt taneggarut i yiḥder ma igebren akk tinaḍin.";
/** @export */ Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
/** @export */ Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Rnu, kkes, neq ales ales asmizzwer n tgezmiyin akken ad talseḍ tawila n iḥder-agi ma.";
/** @export */ Blockly.Msg.CONTROLS_IF_MSG_ELSE = "neɣ";
/** @export */ Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "neɣ ma";
/** @export */ Blockly.Msg.CONTROLS_IF_MSG_IF = "ma";
/** @export */ Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "ma yella azal d idetti, ihi selkem kra n tinaḍin.";
/** @export */ Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "Ma yella zal d idetti, selkem iḥder amezwaru. Neɣ ma ulac, selkem iḥder wis sin.";
/** @export */ Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Ma yella azal amezwaru d idetti, selkem iḥder amezwaru. Neɣ ma azal wis sin d ucciḍ, selkem iḥ€der wis sin.";
/** @export */ Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Ma yella azal amezwaru d idetti, selkem iḥeder amezwaru. Neɣ, ma yella azal wis sin d idetti, selkem iḥder wis sin. Ma yella ula d yisen seg-sen mačči d idetti, selkem iḥder aneggaru.";
/** @export */ Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://en.wikipedia.org/wiki/For_loop";
/** @export */ Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "eg";
/** @export */ Blockly.Msg.CONTROLS_REPEAT_TITLE = "Ales %1 n tikal";
/** @export */ Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Selkem ddeqs n tinaḍin ddeqs n tikal.";
/** @export */ Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
/** @export */ Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "ales arama";
/** @export */ Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "ales skud";
/** @export */ Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Skud azal d ucciḍ, selkem ihi tinadin.";
/** @export */ Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Skud azal d idetti, selkem ihi tinadin.";
/** @export */ Blockly.Msg.DELETE_ALL_BLOCKS = "Kkes akk %1 n yiḥedran?";
/** @export */ Blockly.Msg.DELETE_BLOCK = "Kkes iḥder";
/** @export */ Blockly.Msg.DELETE_VARIABLE = "Kkes amutti '%1'";
/** @export */ Blockly.Msg.DELETE_VARIABLE_CONFIRMATION = "Kkes %1 n useqdec n umutti '%2'?";
/** @export */ Blockly.Msg.DELETE_X_BLOCKS = "Kkes %1 n yiḥderan";
/** @export */ Blockly.Msg.DISABLE_BLOCK = "Sens iḥder";
/** @export */ Blockly.Msg.DUPLICATE_BLOCK = "Sleg";
/** @export */ Blockly.Msg.ENABLE_BLOCK = "Sens iḥedran";
/** @export */ Blockly.Msg.EXPAND_ALL = "Snefli iḥedran";
/** @export */ Blockly.Msg.EXPAND_BLOCK = "Snefli iḥder";
/** @export */ Blockly.Msg.EXTERNAL_INPUTS = "Inekcam izɣarayen";
/** @export */ Blockly.Msg.HELP = "Tallelt";
/** @export */ Blockly.Msg.INLINE_INPUTS = "Inekcam srid";
/** @export */ Blockly.Msg.IOS_CANCEL = "Sefsex";
/** @export */ Blockly.Msg.IOS_ERROR = "Tuccḍa";
/** @export */ Blockly.Msg.IOS_OK = "IH";
/** @export */ Blockly.Msg.IOS_PROCEDURES_ADD_INPUT = "+ Rnu anekcum";
/** @export */ Blockly.Msg.IOS_PROCEDURES_ALLOW_STATEMENTS = "Sireg asmizzwer";
/** @export */ Blockly.Msg.IOS_PROCEDURES_DUPLICATE_INPUTS_ERROR = "Tawuri-a ɣur-s inekcam imsinen.";
/** @export */ Blockly.Msg.IOS_PROCEDURES_INPUTS = "INEKCAM";
/** @export */ Blockly.Msg.IOS_VARIABLES_ADD_BUTTON = "Rnu";
/** @export */ Blockly.Msg.IOS_VARIABLES_ADD_VARIABLE = "+ Rnu amutti";
/** @export */ Blockly.Msg.IOS_VARIABLES_DELETE_BUTTON = "Kkes";
/** @export */ Blockly.Msg.IOS_VARIABLES_EMPTY_NAME_ERROR = "Ur tezmireḍ ara ad tesqedceḍ isem n umutti amaynut.";
/** @export */ Blockly.Msg.IOS_VARIABLES_RENAME_BUTTON = "Snifel isem";
/** @export */ Blockly.Msg.IOS_VARIABLES_VARIABLE_NAME = "Isem n umutti";
/** @export */ Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
/** @export */ Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "rnu tabdart tilemt";
/** @export */ Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Ad d-yerr tabdart n teɣzi 0 ur yegbiren ara ikalasen";
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "tabdart";
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Rnu, kkes, neɣ ales asmizzwer n tgezmiyin akken ad talseḍ tawila n iḥder-agi n tebdart.";
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "rnu tabdart s";
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Ad yernu aferdis ar tebdart.";
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Ad yernu tabdart s umḍan n iferdisen.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_FIRST = "amezwaru";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_FROM_END = "# si tagara";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";  // untranslated
/** @export */ Blockly.Msg.LISTS_GET_INDEX_GET = "awi";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "awi u kkes";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_LAST = "aneggaru";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_RANDOM = "agacuran";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_REMOVE = "kkes";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Ad d-yerr aferdis amezwaru n tebdart..";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM = "Ad d-yerr aferdis n wadig yettwammlen deg tabdart.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Ad d-yerr aferdis aneggaru di tebdart.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Ad yerr aferdis agacuran di tebdart.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Ad yekkes sakin ad -yerr aferdis amezwaru di tebdart.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM = "Ad yekkes sakin ad d-yerr aferdis n wadig yettwammlen deg tabdart.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Ad yekkes sakin ad -yerr aferdis aneggaru di tebdart.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Ad yekkes sakin ad d-yerr aferdis agacuran di tebdart.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Ad yekkes aferdis amezwaru n tebdart..";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM = "Ad yekkes aferdis n wadig yettwammlen deg tabdart.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Ad yekkes aferdis aneggaru di tebdart.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Ad yekkes aferdis agacuran di tebdart.";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "ar # si tagara";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "ar #";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "ar tagara";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "awi-d tabdart tasnawant si tazwara";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "awi-d tabdart tasnawant seg # si tagara";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "awi-d tabdart tasnawant seg #";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Ad yernu anɣel n uḥric yettwammlen n tebdart.";
/** @export */ Blockly.Msg.LISTS_INDEX_FROM_END_TOOLTIP = "%1 d aferdis aneggaru.";
/** @export */ Blockly.Msg.LISTS_INDEX_FROM_START_TOOLTIP = "%1 d aferdis amezwaru.";
/** @export */ Blockly.Msg.LISTS_INDEX_OF_FIRST = "aff-d timeḍriwt tamezwarut n uferdis";
/** @export */ Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
/** @export */ Blockly.Msg.LISTS_INDEX_OF_LAST = "af-d timeḍriwt taneggarut n uferdis";
/** @export */ Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Ad d-yerr amatar n tmeḍriwt tamezwarut/taneggarut n uferdis amewaru deg tebdart. Ad d-yerr %1 ma yella ulac aferdis.";
/** @export */ Blockly.Msg.LISTS_INLIST = "di tebdart";
/** @export */ Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
/** @export */ Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 d ilem";
/** @export */ Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "Ad d-yerr idetti ma yella tabdart d tilemt.";
/** @export */ Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
/** @export */ Blockly.Msg.LISTS_LENGTH_TITLE = "teɣzi n %1";
/** @export */ Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Ad d-yerr teɣzi n tebdart.";
/** @export */ Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
/** @export */ Blockly.Msg.LISTS_REPEAT_TITLE = "ad yernu tabdart s uferdis %1 s tmeḍriwt %2";
/** @export */ Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Ad yernu tabdart inetmen n wazal yettunefken ddeqs n tikal s umḍan yettwammlen.";
/** @export */ Blockly.Msg.LISTS_REVERSE_HELPURL = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";  // untranslated
/** @export */ Blockly.Msg.LISTS_REVERSE_MESSAGE0 = "tti %1";
/** @export */ Blockly.Msg.LISTS_REVERSE_TOOLTIP = "Tti anɣel n tebdart.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
/** @export */ Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "am";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_INSERT = "ger s";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_SET = "sbadu";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Ad iger aferdis di tazwara n tebdart.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM = "Ad iger aferdis n wadig yettwammlen deg tabdart.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Ad yernu aferdis ar tagara n  tebdart.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Ad iger aferdis s wudem agacuran deg tebdart.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Ad d-yerr aferdis amezwaru di tebdart.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM = "Ad yesbadu aferdis n wadig yettwammlen deg tabdart.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Ad d-yerr aferdis aneggaru di tebdart.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Ad yesbadu aferdis agacuran di tebdart.";
/** @export */ Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
/** @export */ Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "igemmen";
/** @export */ Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "amnusruy";
/** @export */ Blockly.Msg.LISTS_SORT_TITLE = "smizzwer %1 %2 %3";
/** @export */ Blockly.Msg.LISTS_SORT_TOOLTIP = "Smizzwer anɣel n tebdart.";
/** @export */ Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "agemmayan, anef i truẓi n usekkil";
/** @export */ Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "umḍin";
/** @export */ Blockly.Msg.LISTS_SORT_TYPE_TEXT = "agemmayan";
/** @export */ Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
/** @export */ Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "rnu tabdart seg uḍris";
/** @export */ Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "rnu aḍris si tebdart";
/** @export */ Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "ad yesdukel tabdart n yiḍrisen deg iwen s usnabraz.";
/** @export */ Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Ad yegzem aḍris ɣef ddeqs n tebdarin n yoiḍrisen, s unegzum yal anabraz.";
/** @export */ Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "s unabraz";
/** @export */ Blockly.Msg.LOGIC_BOOLEAN_FALSE = "ucciḍ";
/** @export */ Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
/** @export */ Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Ad d-yerr idetti neɣ ucciḍ";
/** @export */ Blockly.Msg.LOGIC_BOOLEAN_TRUE = "idetti";
/** @export */ Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://en.wikipedia.org/wiki/Inequality_(mathematics)";
/** @export */ Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Ad yerr idetti ma yella i sin n inekcam d imegduya.";
/** @export */ Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Ad d-yerr idetti ma yella anekcam amezwaru meqqeṛ ɣef wis sin.";
/** @export */ Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Ad d-yerr idetti ma yella anekcam amezwaru meqqeṛ neɣ yegda wis sin.";
/** @export */ Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Ad d-yerr idetti ma yella anekcam amezwaru meẓẓi ɣef wis sin.";
/** @export */ Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Ad d-yerr idetti ma yella anekcam amezwaru meẓẓi neɣ yegda wis sin.";
/** @export */ Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Ad d-yerr idetti ma yella i sin n inekcam mačči d imegduya.";
/** @export */ Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
/** @export */ Blockly.Msg.LOGIC_NEGATE_TITLE = "mačči %1";
/** @export */ Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Ad d-yerr idetti ma yella anekcam d ucciḍ. Ad d-yerr ucciḍ ma yella anekcam d idetti.";
/** @export */ Blockly.Msg.LOGIC_NULL = "Ilem";
/** @export */ Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
/** @export */ Blockly.Msg.LOGIC_NULL_TOOLTIP = "Ad d-yerr ilem";
/** @export */ Blockly.Msg.LOGIC_OPERATION_AND = "akked";
/** @export */ Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
/** @export */ Blockly.Msg.LOGIC_OPERATION_OR = "neɣ";
/** @export */ Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Ad d-yerr idetti ma yella inekcam d idettiyen.";
/** @export */ Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Ad d-yerr idetti ma yella ɣarsum yiwen seg inekcam d idetti.";
/** @export */ Blockly.Msg.LOGIC_TERNARY_CONDITION = "sekyed";
/** @export */ Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";  // untranslated
/** @export */ Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "ma ucciḍ";
/** @export */ Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "ma d idetti";
/** @export */ Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Senqed tawtilt deg 'sekyed'. Ma yella d idetti, ad d-yerr azal 'ma idetti', ma ulac ad d-yerr azam 'ma ucciḍ'.";
/** @export */ Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
/** @export */ Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://en.wikipedia.org/wiki/Arithmetic";
/** @export */ Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Ad d-yerr tmerni n sin n imiḍanen.";
/** @export */ Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Ad d-yerr aful n sin n imḍanen.";
/** @export */ Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Ad d-yerr tmernit n sin n imiḍanen.";
/** @export */ Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Ad d-yerr tukksa gar sin n imiḍanen.";
/** @export */ Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Ad d-yerr amḍan amezwaru uzmir wis sin.";
/** @export */ Blockly.Msg.MATH_CHANGE_HELPURL = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
/** @export */ Blockly.Msg.MATH_CHANGE_TITLE = "snifel %1 s %2";
/** @export */ Blockly.Msg.MATH_CHANGE_TOOLTIP = "Rnu amḍan i umutti '%1'.";
/** @export */ Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant";
/** @export */ Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Ad d-yerr yiwet seg tmezgiyin yettwasnen : π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), neɣ ∞ (ifeḍ).";
/** @export */ Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
/** @export */ Blockly.Msg.MATH_CONSTRAIN_TITLE = "Err tamara i %1 gar %2 akked %3";
/** @export */ Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Err tamara n umiḍan akken ad yili gar snat n tlisa (ddant).";
/** @export */ Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";  // untranslated
/** @export */ Blockly.Msg.MATH_IS_DIVISIBLE_BY = "d ubṭay ɣef";
/** @export */ Blockly.Msg.MATH_IS_EVEN = "d ayugan";
/** @export */ Blockly.Msg.MATH_IS_NEGATIVE = "d uzdir";
/** @export */ Blockly.Msg.MATH_IS_ODD = "d aryugan";
/** @export */ Blockly.Msg.MATH_IS_POSITIVE = "d ufrar";
/** @export */ Blockly.Msg.MATH_IS_PRIME = "d amenzu";
/** @export */ Blockly.Msg.MATH_IS_TOOLTIP = "Senqed ma yella amḍan d ayugan, d aryugan, d amenzu, d ummid, d ufrar, d uzdir, neɣ d ybṭay ɣef kra n umḍan. Ad d-yerr idettu neɣ ucciḍ.";
/** @export */ Blockly.Msg.MATH_IS_WHOLE = "d ummid";
/** @export */ Blockly.Msg.MATH_MODULO_HELPURL = "https://en.wikipedia.org/wiki/Modulo_operation";
/** @export */ Blockly.Msg.MATH_MODULO_TITLE = "tasagert n %1 ÷ %2";
/** @export */ Blockly.Msg.MATH_MODULO_TOOLTIP = "Ad d-yerr tasagert n beṭṭu n sin n imḍanen.";
/** @export */ Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";  // untranslated
/** @export */ Blockly.Msg.MATH_NUMBER_HELPURL = "https://en.wikipedia.org/wiki/Number";
/** @export */ Blockly.Msg.MATH_NUMBER_TOOLTIP = "Amḍan.";
/** @export */ Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "talemmast n tebdart";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "afellay n tebdart";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "tanammast n tebdart";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "adday n tebdart";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "Tigwtiwin n tebdart";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "aferdis agacuran n tebdart";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "azza n tebdart";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "Timernit n tebdart";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Ad d-yerr talemmas( tasnamḍant) n wazalen umḍinen di tebdart.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Ad d-yerr amḍan  ameqqran di tebdart.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Ad d-yerr amḍan n anammas n tebdart.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Ad d-yerr amḍan  ameẓẓyan di tebdart.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Ad d-yerr tabdart n iferdisen i d-yettuɣalen s waṭas di tebdart.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Ad d-yerr aferdis seg tebdart s wudem agacuran.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Ad d-yerr azza n tebdart.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Ad d-yerr timernit n imḍanen meṛṛa deg tebdart.";
/** @export */ Blockly.Msg.MATH_POWER_SYMBOL = "^";  // untranslated
/** @export */ Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
/** @export */ Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "tirẓi tagacurant";
/** @export */ Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Ad d-yerr tirẓi tagacurant gar 0.0 (yedda) akked 1.0 (ur yeddi ara).";
/** @export */ Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
/** @export */ Blockly.Msg.MATH_RANDOM_INT_TITLE = "ummid agacuran gar %1 akked %2";
/** @export */ Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Ad d-yerr ummid agacuran gar snat n tlisa, ddant.";
/** @export */ Blockly.Msg.MATH_ROUND_HELPURL = "https://en.wikipedia.org/wiki/Rounding";
/** @export */ Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "Saẓ";
/** @export */ Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "Saẓ d akesser";
/** @export */ Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "Saẓ d asawen";
/** @export */ Blockly.Msg.MATH_ROUND_TOOLTIP = "Saẓ amiḍan d asawen neɣ d akesser.";
/** @export */ Blockly.Msg.MATH_SINGLE_HELPURL = "https://en.wikipedia.org/wiki/Square_root";
/** @export */ Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "azal amagdez";
/** @export */ Blockly.Msg.MATH_SINGLE_OP_ROOT = "aẓar uzmir 2";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Ad d-yerr azal amagdez n umiḍan.";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Ad d-yerr e uzmir amiḍan.";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Ad d-yerr alugaritm agamawan n umiḍan.";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Ad d-yerr alugaritm 10 n umiḍan.";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Ad d-yerr ugmiḍ n umḍan.";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Ad d-yerr 10 uzmir amiḍan.";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Ad d-yerr aẓaṛ uzmir sin n umiḍan.";
/** @export */ Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
/** @export */ Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
/** @export */ Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
/** @export */ Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
/** @export */ Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
/** @export */ Blockly.Msg.MATH_TRIG_HELPURL = "https://en.wikipedia.org/wiki/Trigonometric_functions";
/** @export */ Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
/** @export */ Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
/** @export */ Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Ad d-yerr taganzi n ukusinus n umḍan.";
/** @export */ Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Ad d-yerr taganzi n usinus n umḍan.";
/** @export */ Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Ad d-yerr taganzi n teslayt n umiḍan.";
/** @export */ Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Ad d-yerr akusinus n teɣmert s tfesna (mačči aṛadyan).";
/** @export */ Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Ad d-yerr asinus n teɣmert s tfesna (mačči aṛadyan).";
/** @export */ Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Ad d-yerr taslayt n teɣmert s tfesna (mačči aṛadyan).";
/** @export */ Blockly.Msg.NEW_COLOUR_VARIABLE = "Create colour variable...";  // untranslated
/** @export */ Blockly.Msg.NEW_NUMBER_VARIABLE = "Create number variable...";  // untranslated
/** @export */ Blockly.Msg.NEW_STRING_VARIABLE = "Create string variable...";  // untranslated
/** @export */ Blockly.Msg.NEW_VARIABLE = "Rnu amutti...";
/** @export */ Blockly.Msg.NEW_VARIABLE_TITLE = "Isem amaynut n wazal:";
/** @export */ Blockly.Msg.NEW_VARIABLE_TYPE_TITLE = "New variable type:";  // untranslated
/** @export */ Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
/** @export */ Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "Sireg asmizzwer";
/** @export */ Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "s:";
/** @export */ Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";
/** @export */ Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Selkem tawuri '%1' yesbadu u seqdac.";
/** @export */ Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";
/** @export */ Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Selkem tawuri '%1' yesbadu useqdace sakin seqdec agmuḍ-is.";
/** @export */ Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "s:";
/** @export */ Blockly.Msg.PROCEDURES_CREATE_DO = "rnu '%1'";
/** @export */ Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "Seglem tawuri-agi...";
/** @export */ Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
/** @export */ Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
/** @export */ Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "eg kra";
/** @export */ Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "i";
/** @export */ Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Rnu tawuri s war anekcam.";
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "tuɣalin";
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "ad yernu tawuri s tuffɣa.";
/** @export */ Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Ɣur-k: Tawuri-agi ɣur-s iɣewwaṛen usligen.";
/** @export */ Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Sebruṛeq tabadut n twuri";
/** @export */ Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";  // untranslated
/** @export */ Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "ma yella azal d idetti, ad d-yerr azal-nniḍen wis sin.";
/** @export */ Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Ɣur-k: Iḥder-agi yezmer ur yettwaseqdac ara ala di tebadut n twuri-agi.";
/** @export */ Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "isem n unekcum:";
/** @export */ Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "rnu anekcam ar twuri-agi.";
/** @export */ Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "inekcam";
/** @export */ Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Rnu, kkes neɣ ales asmizzwer n inekcam i twuri-agi.";
/** @export */ Blockly.Msg.REDO = "Uɣal";
/** @export */ Blockly.Msg.REMOVE_COMMENT = "Kkes awennit";
/** @export */ Blockly.Msg.RENAME_VARIABLE = "Beddel isem n umutti...";
/** @export */ Blockly.Msg.RENAME_VARIABLE_TITLE = "Beddel akk isem n yimuttiyen '%1' ar:";
/** @export */ Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
/** @export */ Blockly.Msg.TEXT_APPEND_TITLE = "Rnu aḍris %2 ar %1";
/** @export */ Blockly.Msg.TEXT_APPEND_TOOLTIP = "Rnu aḍris ar umutti '%1'.";
/** @export */ Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
/** @export */ Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "s usekkil ameẓẓyan";
/** @export */ Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "s Umeqqran Di Tazwara n Yal Awal.";
/** @export */ Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "s USEKKIL AMEQQRAN";
/** @export */ Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Ad d-yerr anɣel n uḍris s truẓi-nniḍen.";
/** @export */ Blockly.Msg.TEXT_CHARAT_FIRST = "awi-d asekkil amezwaru";
/** @export */ Blockly.Msg.TEXT_CHARAT_FROM_END = "awi-d asekkil # si tagara";
/** @export */ Blockly.Msg.TEXT_CHARAT_FROM_START = "awi asekkel #";
/** @export */ Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
/** @export */ Blockly.Msg.TEXT_CHARAT_LAST = "awi-d asekkil aneggaru";
/** @export */ Blockly.Msg.TEXT_CHARAT_RANDOM = "awi-d asekkil s wudem agacuran";
/** @export */ Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
/** @export */ Blockly.Msg.TEXT_CHARAT_TITLE = "deg uḍris %1 %2";
/** @export */ Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Ad d-yerr asekkil deg wuṭṭun yettwammlen.";
/** @export */ Blockly.Msg.TEXT_COUNT_HELPURL = "https://github.com/google/blockly/wiki/Text#counting-substrings";  // untranslated
/** @export */ Blockly.Msg.TEXT_COUNT_MESSAGE0 = "amḍan %1 ɣef %2";
/** @export */ Blockly.Msg.TEXT_COUNT_TOOLTIP = "Ad isiḍen amḍan n tmeḍriwt n uḍris deg ayeḍ.";
/** @export */ Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "Rnu aferdis ar uḍris.";
/** @export */ Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "sdukkel";
/** @export */ Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Rnu, kkes, neɣ ales asmizzwer n tgezmiyin akken ad talseḍ tawila n iḥder-agi.";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "arama d asekkil # si tagara";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "arama d asekkil #";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "arama d asekkil aneggaru";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "deg uḍris";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "awi-d azrir asnawan seg usekkil amezwaru";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "awi-d azrir asnawan seg usekkil # si tagara";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "awi-d azrir asnawan seg usekkil #";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Ad d-yerr aḥric yettwammlen deg uḍris.";
/** @export */ Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
/** @export */ Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "af-d timeḍriwt tamezwarut n uḍris";
/** @export */ Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "af-d timeḍriwt taneggarut deg uḍris";
/** @export */ Blockly.Msg.TEXT_INDEXOF_TITLE = "deg uḍris %1 %2 %3";
/** @export */ Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Ad d-yerr amatar n tmeḍriwt tamezwarut/taneggarut n uḍris amewaru deg uḍris wis sin. Ad d-yerr %1 ma yella ulac adris.";
/** @export */ Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
/** @export */ Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 d ilem";
/** @export */ Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Add d-yerr idetti ma yella aḍris d ilem.";
/** @export */ Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
/** @export */ Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "rnu aḍṛis s";
/** @export */ Blockly.Msg.TEXT_JOIN_TOOLTIP = "Ad yernu taceqquft n uḍris s usdukel gar yal amḍan n iferdisen.";
/** @export */ Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
/** @export */ Blockly.Msg.TEXT_LENGTH_TITLE = "teɣzi n %1";
/** @export */ Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Ad d-yerr amḍan n isekkilen (ddab ula d imellalen) deg uḍris d-ittunefken.";
/** @export */ Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
/** @export */ Blockly.Msg.TEXT_PRINT_TITLE = "ad d-yesken %1";
/** @export */ Blockly.Msg.TEXT_PRINT_TOOLTIP = "Sken aḍris, amḍan neɣ azal-nniḍen d-ittunefken.";
/** @export */ Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
/** @export */ Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Suter amḍan i useqdac.";
/** @export */ Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Suter aḍris i useqdac.";
/** @export */ Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "aneftaɣ i umḍan s yizen";
/** @export */ Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "aneftaɣ i uḍris s yizen";
/** @export */ Blockly.Msg.TEXT_REPLACE_HELPURL = "https://github.com/google/blockly/wiki/Text#replacing-substrings";  // untranslated
/** @export */ Blockly.Msg.TEXT_REPLACE_MESSAGE0 = "semselsi %1 s %2 di %3";
/** @export */ Blockly.Msg.TEXT_REPLACE_TOOLTIP = "As isemselsi akk timeḍriwin n uḍris s wayeḍ.";
/** @export */ Blockly.Msg.TEXT_REVERSE_HELPURL = "https://github.com/google/blockly/wiki/Text#reversing-text";  // untranslated
/** @export */ Blockly.Msg.TEXT_REVERSE_MESSAGE0 = "tti %1";
/** @export */ Blockly.Msg.TEXT_REVERSE_TOOLTIP = "Ad yetti asmizzwer n isekkilen deg uḍris.";
/** @export */ Blockly.Msg.TEXT_TEXT_HELPURL = "https://en.wikipedia.org/wiki/String_(computer_science)";
/** @export */ Blockly.Msg.TEXT_TEXT_TOOLTIP = "Asekkil, awal neɣ izirig n uḍris.";
/** @export */ Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
/** @export */ Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "Tukksa n isekkilen imellalen seg sin n idisan";
/** @export */ Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "tukksa n isekkilen seg uzelmaḍ";
/** @export */ Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "tukksa n isekkilen seg uyeffus";
/** @export */ Blockly.Msg.TEXT_TRIM_TOOLTIP = "Ad d-yerr anɣel n uḍris s isekkilen ilmawen yettwakksen seg ixf neɣ i sin.";
/** @export */ Blockly.Msg.TODAY = "Ass-a";
/** @export */ Blockly.Msg.UNDO = "Err-d";
/** @export */ Blockly.Msg.VARIABLES_DEFAULT_NAME = "aferdis";
/** @export */ Blockly.Msg.VARIABLES_GET_CREATE_SET = "Rnu 'sbadu %1'";
/** @export */ Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
/** @export */ Blockly.Msg.VARIABLES_GET_TOOLTIP = "Ad d-yerr azal n umutti-agi.";
/** @export */ Blockly.Msg.VARIABLES_SET = "sbadu %1 ar %2";
/** @export */ Blockly.Msg.VARIABLES_SET_CREATE_GET = "Rnu 'awi-d %1'";
/** @export */ Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
/** @export */ Blockly.Msg.VARIABLES_SET_TOOLTIP = "Ad yesbadu amutti-agi akken ad yegdu azal n unekcam.";
/** @export */ Blockly.Msg.VARIABLE_ALREADY_EXISTS = "Amutti s yisem '%1' yella yakan.";
/** @export */ Blockly.Msg.VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE = "Amutti s yisem '%1' yella yakan i umutti-nniḍen s wanaw '%2'.";
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
/** @export */ Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
/** @export */ Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
/** @export */ Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
/** @export */ Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
/** @export */ Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
/** @export */ Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
/** @export */ Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
/** @export */ Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
/** @export */ Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
/** @export */ Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
/** @export */ Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
/** @export */ Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
/** @export */ Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
/** @export */ Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;

/** @export */ Blockly.Msg.MATH_HUE = "230";
/** @export */ Blockly.Msg.LOOPS_HUE = "120";
/** @export */ Blockly.Msg.LISTS_HUE = "260";
/** @export */ Blockly.Msg.LOGIC_HUE = "210";
/** @export */ Blockly.Msg.VARIABLES_HUE = "330";
/** @export */ Blockly.Msg.TEXTS_HUE = "160";
/** @export */ Blockly.Msg.PROCEDURES_HUE = "290";
/** @export */ Blockly.Msg.COLOUR_HUE = "20";
/** @export */ Blockly.Msg.VARIABLES_DYNAMIC_HUE = "310";