// This file was automatically generated.  Do not modify.

'use strict';

const messages = Object.create(null);

messages["ADD_COMMENT"] = "ಟಿಪ್ಪಣಿ ಸೇರಿಸು";
messages["CANNOT_DELETE_VARIABLE_PROCEDURE"] = "'%1' ಚರಾಂಶವನ್ನು ಅಳಿಸಲಾಗುವುದಿಲ್ಲ. ಏಕೆಂದರೆ ಇದು '%2' ಕಾರ್ಯಘಟಕದ ವ್ಯಾಖ್ಯಾನದ ಭಾಗವಾಗಿದೆ";
messages["CHANGE_VALUE_TITLE"] = "ಮೌಲ್ಯ ಬದಲಾಯಿಸು:";
messages["CLEAN_UP"] = "ಬ್ಲಾಕ್‍ಗಳನ್ನೆಲ್ಲಾ ಒಪ್ಪವಾಗಿರಿಸು";
messages["COLLAPSED_WARNINGS_WARNING"] = "ಸಂಕುಚಿತಗೊಂಡ ಬ್ಲಾಕ್ ಗಳು ಎಚ್ಚರಿಕೆಗಳನ್ನು ಒಳಗೊಂಡಿರುತ್ತವೆ.";
messages["COLLAPSE_ALL"] = "ಬ್ಲಾಕ್‍ಗಳನ್ನು ಮಡಿಸಿಬಿಡು";
messages["COLLAPSE_BLOCK"] = "ಬ್ಲಾಕ್‍ನ್ನು ಮಡಿಸಿಬಿಡು";
messages["COLOUR_BLEND_COLOUR1"] = "ಬಣ್ಣ 1";
messages["COLOUR_BLEND_COLOUR2"] = "ಬಣ್ಣ 2";
messages["COLOUR_BLEND_HELPURL"] = "https://meyerweb.com/eric/tools/color-blend/#:::rgbp";  // untranslated
messages["COLOUR_BLEND_RATIO"] = "ಅನುಪಾತ";
messages["COLOUR_BLEND_TITLE"] = "ಮಿಶ್ರಣಮಾಡು";
messages["COLOUR_BLEND_TOOLTIP"] = "ಕೊಟ್ಟಿರುವ ಅನುಪಾತದಂತೆ(0.0 - 1.0) ಎರಡು ಬಣ್ಣಗಳನ್ನು ಮಿಶ್ರಣ ಮಾಡುತ್ತದೆ.";
messages["COLOUR_PICKER_HELPURL"] = "https://en.wikipedia.org/wiki/Color";
messages["COLOUR_PICKER_TOOLTIP"] = "ವರ್ಣಫಲಕದಿಂದ ಬಣ್ಣವನ್ನು ಆರಿಸು.";
messages["COLOUR_RANDOM_HELPURL"] = "http://randomcolour.com";  // untranslated
messages["COLOUR_RANDOM_TITLE"] = "ಯಾದೃಚ್ಛಿಕ ಬಣ್ಣ";
messages["COLOUR_RANDOM_TOOLTIP"] = "ಯಾದೃಚ್ಛಿಕವಾಗಿ ಯಾವುದಾದರೂ ಒಂದು ಬಣ್ಣವನ್ನು ಆರಿಸು.";
messages["COLOUR_RGB_BLUE"] = "ನೀಲಿ";
messages["COLOUR_RGB_GREEN"] = "ಹಸಿರು";
messages["COLOUR_RGB_HELPURL"] = "https://www.december.com/html/spec/colorpercompact.html";  // untranslated
messages["COLOUR_RGB_RED"] = "ಕೆಂಪು";
messages["COLOUR_RGB_TITLE"] = "ಬಣ್ಣದಿಂದ";
messages["COLOUR_RGB_TOOLTIP"] = "ನಿರ್ದಿಷ್ಟ ಪ್ರಮಾಣದಲ್ಲಿ ಕೆಂಪು, ಹಸಿರು ಮತ್ತು ನೀಲಿಯನ್ನು ಹೊಂದಿದ ಒಂದು ಬಣ್ಣವನ್ನು ರಚಿಸಿ. ಎಲ್ಲಾ ಮೌಲ್ಯಗಳು 0 ಮತ್ತು 100 ರ ನಡುವೆ ಇರಲಿ.";
messages["CONTROLS_FLOW_STATEMENTS_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
messages["CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK"] = "ಪುನರಾವರ್ತನೆಯಿಂದ ನಿರ್ಗಮಿಸು";
messages["CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE"] = "ಲೂಪ್ ಮುಂದಿನ ಪುನರಾವರ್ತನೆಯೊಂದಿಗೆ ಮುಂದುವರೆಯಲಿ";
messages["CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK"] = "ಒಳಹೊಕ್ಕಿರುವ ಲೂಪಿನಿಂದ ನಿರ್ಗಮಿಸು.";
messages["CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE"] = "ಈ ಲೂಪಿನ ಉಳಿದ ಭಾಗವನ್ನು ಬಿಟ್ಟು, ಮುಂದಿನ ಪುನರಾವರ್ತನೆಯೊಂದಿಗೆ ಮುಂದುವರಿಸಿ.";
messages["CONTROLS_FLOW_STATEMENTS_WARNING"] = "ಎಚ್ಚರಿಕೆ: ಈ ಬ್ಲಾಕನ್ನು  ಲೂಪ್‌ನಲ್ಲಿ ಮಾತ್ರ ಬಳಸಬಹುದು.";
messages["CONTROLS_FOREACH_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
messages["CONTROLS_FOREACH_TITLE"] = "%2 ಪಟ್ಟಿಯಲ್ಲಿರುವ ಪ್ರತಿ  %1  ಅಂಶಕ್ಕೆ";
messages["CONTROLS_FOREACH_TOOLTIP"] = "ಪಟ್ಟಿಯಲ್ಲಿರುವ ಪ್ರತಿಯೊಂದು ಅಂಶಕ್ಕೆ, ಚರಾಂಶ  '%1'ನ್ನು   ಅಂಶಕ್ಕೆ ಜೋಡಿಸಿ, ತದನಂತರ ಕೆಲವು ಹೇಳಿಕೆಗಳನ್ನು ಮಾಡಿ.";
messages["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
messages["CONTROLS_FOR_TITLE"] = "%1 ಜೊತೆ ಎಣಿಸು %2 ಇಂದ %3 ತನಕ %4 ಪ್ರಮಾಣದಲ್ಲಿ";
messages["CONTROLS_FOR_TOOLTIP"] = "ಚರಾಂಶವಾದ %1 ಪ್ರಾರಂಭ ಸಂಖ್ಯೆಯಿಂದ ಅಂತಿಮ ಸಂಖ್ಯೆಯವರೆಗೆ ಮೌಲ್ಯಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಲಿ, ನಿರ್ದಿಷ್ಟ ಮಧ್ಯಂತರದಿಂದ ಎಣಿಸಿ, ಮತ್ತು ನಿರ್ದಿಷ್ಟಪಡಿಸಿದ ಬ್ಲಾಕ್ ಗಳನ್ನು  ಮಾಡಲಿ.";
messages["CONTROLS_IF_ELSEIF_TOOLTIP"] = "'ಆಗಿದ್ದರೆ' ಬ್ಲಾಕ್ ಗೆ ಒಂದು ಷರತ್ತು ಸೇರಿಸಿ.";
messages["CONTROLS_IF_ELSE_TOOLTIP"] = "ಅಂತಿಮವಾದ, ಎಲ್ಲವನ್ನೂ-ಹಿಡಿ ಷರತ್ತನ್ನು 'ಆಗಿದ್ದರೆ' ಬ್ಲಾಕ್ ಗೆ ಸೇರಿಸಿ.";
messages["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
messages["CONTROLS_IF_IF_TOOLTIP"] = "ಈ 'ಆಗಿದ್ದರೆ' ಬ್ಲಾಕನ್ನು ಮರು ಸಂರಚಿಸಲು ಅದರ ಭಾಗಗಳನ್ನು ಸೇರಿಸು, ತೆಗೆ ಅಥವಾ ಮರುಕ್ರಮಗೊಳಿಸು.";
messages["CONTROLS_IF_MSG_ELSE"] = "ಇಲ್ಲದಿದ್ದರೆ";
messages["CONTROLS_IF_MSG_ELSEIF"] = "ಆಗಿರದಿದ್ದರೆ";
messages["CONTROLS_IF_MSG_IF"] = "ಆಗಿದ್ದರೆ";
messages["CONTROLS_IF_TOOLTIP_1"] = "ಮೌಲ್ಯವು ಸತ್ಯವಾಗಿದ್ದರೆ, ಕೆಲವು ಹೇಳಿಕೆಗಳನ್ನು ಮಾಡಿ.";
messages["CONTROLS_IF_TOOLTIP_2"] = "ಮೌಲ್ಯವು ಸತ್ಯ ಆಗಿದ್ದರೆ, ಮೊದಲನೇ ವಿಭಾಗದ ಹೇಳಿಕೆಗಳನ್ನು ಮಾಡು, ಇಲ್ಲವಾದರೆ, ಎರಡನೇ ವಿಭಾಗದ ಹೇಳಿಕೆಗಳನ್ನು ಮಾಡು.";
messages["CONTROLS_IF_TOOLTIP_3"] = "ಮೊದಲನೇ ಮೌಲ್ಯವು ಸತ್ಯವಾಗಿದ್ದರೆ, ಮೊದಲ ವಿಭಾಗದ ಹೇಳಿಕೆಗಳನ್ನು  ಮಾಡಿ. ಇಲ್ಲದಿದ್ದರೆ, ಎರಡನೇ  ಮೌಲ್ಯವು ಸತ್ಯವಾಗಿದ್ದರೆ, ಎರಡನೇ ವಿಭಾಗದ  ಹೇಳಿಕೆಗಳನ್ನು ಮಾಡಿ.";
messages["CONTROLS_IF_TOOLTIP_4"] = "ಮೊದಲನೆಯ ಮೌಲ್ಯವು ಸತ್ಯ ಆಗಿದ್ದರೆ, ಮೊದಲ ವಿಭಾಗದ ಹೇಳಿಕೆಗಳನ್ನು ಮಾಡು. ಇಲ್ಲವಾದರೆ, ಎರಡನೇ ಮೌಲ್ಯವು ಸತ್ಯವಾಗಿದ್ದರೆ, ಎರಡನೇ ವಿಭಾಗದ ಹೇಳಿಕೆಗಳನ್ನು ಮಾಡು. ಒಂದುವೇಳೆ ಯಾವುದೇ ಮೌಲ್ಯವೂ ಸತ್ಯವಾಗಿರದಿದ್ದರೆ, ಕೊನೆಯ ವಿಭಾಗದ ಹೇಳಿಕೆಗಳನ್ನು ಮಾಡು.";
messages["CONTROLS_REPEAT_HELPURL"] = "https://en.wikipedia.org/wiki/For_loop";
messages["CONTROLS_REPEAT_INPUT_DO"] = "ಮಾಡು";
messages["CONTROLS_REPEAT_TITLE"] = "%1 ಬಾರಿ ಪುನರಾವರ್ತಿಸು";
messages["CONTROLS_REPEAT_TOOLTIP"] = "ಕೆಲವು ಹೇಳಿಕೆಗಳನ್ನು ಹಲವಾರು ಬಾರಿ ಮಾಡು.";
messages["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
messages["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "ತನಕ ಪುನರಾವರ್ತಿಸು";
messages["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "ಷರತ್ತು 'ಸತ್ಯ' ಆಗಿರುವವರೆಗೆ ಪುನರಾವರ್ತಿಸು";
messages["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "ಮೌಲ್ಯವು ಸುಳ್ಳಾಗಿರುವವರೆಗೆ, ಕೆಲವು ಹೇಳಿಕೆಗಳನ್ನು ಮಾಡಿ.";
messages["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "ಮೌಲ್ಯವು ಸತ್ಯವಾಗಿರುವವರೆಗೆ, ಕೆಲವು ಹೇಳಿಕೆಗಳನ್ನು ಮಾಡಿ.";
messages["DELETE_ALL_BLOCKS"] = "ಎಲ್ಲಾ %1 ಬ್ಲಾಕ್‍ಗಳನ್ನು ಅಳಿಸುವುದೇ ?";
messages["DELETE_BLOCK"] = "ಬ್ಲಾಕನ್ನು ಅಳಿಸು";
messages["DELETE_VARIABLE"] = "'%1' ಚರಾಂಶವನ್ನು ಅಳಿಸು";
messages["DELETE_VARIABLE_CONFIRMATION"] = "'%2' ಚರಾಂಶದ  '%1' ಉಪಯೋಗಗಳನ್ನು ಅಳಿಸುವುದೇ ?";
messages["DELETE_X_BLOCKS"] = "%1 ಬ್ಲಾಕ್‍ಗಳನ್ನು ಅಳಿಸು";
messages["DIALOG_CANCEL"] = "ರದ್ದುಮಾಡಿ";
messages["DIALOG_OK"] = "ಸರಿ";
messages["DISABLE_BLOCK"] = "ಬ್ಲಾಕನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸು";
messages["DUPLICATE_BLOCK"] = "ಪ್ರತಿ";
messages["DUPLICATE_COMMENT"] = "ಟಿಪ್ಪಣಿಯ ಪ್ರತಿ ಮಾಡು";
messages["ENABLE_BLOCK"] = "ಬ್ಲಾಕನ್ನು ಸಕ್ರಿಯಗೊಳಿಸು";
messages["EXPAND_ALL"] = "ಬ್ಲಾಕ್‍ಗಳನ್ನು ವಿಸ್ತರಿಸು";
messages["EXPAND_BLOCK"] = "ಬ್ಲಾಕನ್ನು ವಿಸ್ತರಿಸು";
messages["EXTERNAL_INPUTS"] = "ಬಾಹ್ಯ ಒಳಾಂಶಗಳು";
messages["HELP"] = "ಸಹಾಯ";
messages["INLINE_INPUTS"] = "ಸಾಲಿನಲ್ಲಿರುವ ಒಳಾoಶಗಳು";
messages["LISTS_CREATE_EMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
messages["LISTS_CREATE_EMPTY_TITLE"] = "ಖಾಲಿ ಪಟ್ಟಿಯನ್ನು ರಚಿಸಿ";
messages["LISTS_CREATE_EMPTY_TOOLTIP"] = "ಯಾವುದೇ ದತ್ತಾಂಶ ದಾಖಲೆಗಳನ್ನು ಹೊಂದಿರದ, 0 ಉದ್ದದ, ಪಟ್ಟಿಯನ್ನು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "ಪಟ್ಟಿ";
messages["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "ಈ ಪಟ್ಟಿಯ ಬ್ಲಾಕ್ ಅನ್ನು ಮರುಸಂರಚಿಸಲು ವಿಭಾಗಗಳನ್ನು ಸೇರಿಸಿ, ತೆಗೆದುಹಾಕಿ ಅಥವಾ ಮರುಕ್ರಮಗೊಳಿಸಿ.";
messages["LISTS_CREATE_WITH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
messages["LISTS_CREATE_WITH_INPUT_WITH"] = "ಇದರೊಂದಿಗೆ ಪಟ್ಟಿಯನ್ನು ರಚಿಸಿ.";
messages["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "ಪಟ್ಟಿಗೆ ಒಂದು ಅಂಶವನ್ನು ಸೇರಿಸಿ.";
messages["LISTS_CREATE_WITH_TOOLTIP"] = "ಹಲವು ಅಂಶಗಳೊಂದಿಗೆ ಪಟ್ಟಿಯನ್ನು ರಚಿಸಿ.";
messages["LISTS_GET_INDEX_FIRST"] = "ಮೊದಲ";
messages["LISTS_GET_INDEX_FROM_END"] = "# ಕೊನೆಯಿಂದ";
messages["LISTS_GET_INDEX_FROM_START"] = "#";  // untranslated
messages["LISTS_GET_INDEX_GET"] = "ಪಡೆಯಿರಿ";
messages["LISTS_GET_INDEX_GET_REMOVE"] = "ಪಡೆಯಿರಿ ಮತ್ತು ತೆಗೆದುಹಾಕಿ";
messages["LISTS_GET_INDEX_LAST"] = "ಕೊನೆಯ";
messages["LISTS_GET_INDEX_RANDOM"] = "ಯಾದೃಚ್ಛಿಕ";
messages["LISTS_GET_INDEX_REMOVE"] = "ತೆಗೆ";
messages["LISTS_GET_INDEX_TAIL"] = "";  // untranslated
messages["LISTS_GET_INDEX_TOOLTIP_GET_FIRST"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ಮೊದಲ ಅಂಶವನ್ನು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_FROM"] = "ಪಟ್ಟಿಯಲ್ಲಿ ನಿರ್ದಿಷ್ಟಪಡಿಸಿದ ಸ್ಥಾನದಲ್ಲಿ ಇರುವ ಅಂಶವನ್ನು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_LAST"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ಕೊನೆಯ ಅಂಶವನ್ನು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_RANDOM"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ಯಾದೃಚ್ಛಿಕ ಅಂಶವನ್ನು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ಮೊದಲ ಸ್ಥಾನದಲ್ಲಿನ ಅಂಶವನ್ನು ತೆಗೆದು ಹಾಕುವುದು ಮತ್ತು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM"] = "ಪಟ್ಟಿಯಲ್ಲಿ ನಿರ್ದಿಷ್ಟಪಡಿಸಿದ ಸ್ಥಾನದಲ್ಲಿನ ಅಂಶವನ್ನು ತೆಗೆದು ಹಾಕುವುದು ಮತ್ತು ಹಿಂತಿರುಗಿಸುವುದು .";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ಕೊನೆಯ ಸ್ಥಾನದಲ್ಲಿನ ಅಂಶವನ್ನು ತೆಗೆದು ಹಾಕುವುದು ಮತ್ತು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ಯಾದೃಚ್ಛಿಕ ಸ್ಥಾನದಲ್ಲಿನ ಅಂಶವನ್ನು ತೆಗೆದು ಹಾಕುವುದು ಮತ್ತು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ಮೊದಲ ಅಂಶವನ್ನು ತೆಗೆದುಹಾಕುತ್ತದೆ.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM"] = "ಪಟ್ಟಿಯಲ್ಲಿ ನಿರ್ದಿಷ್ಟಪಡಿಸಿದ ಸ್ಥಾನದಲ್ಲಿರುವ ಅಂಶವನ್ನು ತೆಗೆದುಹಾಕುತ್ತದೆ.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ಕೊನೆಯ ಅಂಶವನ್ನು ತೆಗೆದುಹಾಕುತ್ತದೆ.";
messages["LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ಯಾದೃಚ್ಛಿಕ ಅಂಶವನ್ನು ತೆಗೆದುಹಾಕುತ್ತದೆ.";
messages["LISTS_GET_SUBLIST_END_FROM_END"] = "ಕೊನೆಯಿಂದ # ವರೆಗೆ";
messages["LISTS_GET_SUBLIST_END_FROM_START"] = "# ವರೆಗೆ";
messages["LISTS_GET_SUBLIST_END_LAST"] = "ಕೊನೆಯವರೆಗೂ";
messages["LISTS_GET_SUBLIST_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
messages["LISTS_GET_SUBLIST_START_FIRST"] = "ಮೊದಲಿನಿಂದ ಉಪ-ಪಟ್ಟಿಯನ್ನು ಪಡೆಯಿರಿ";
messages["LISTS_GET_SUBLIST_START_FROM_END"] = "# ನಿಂದ ಉಪ-ಪಟ್ಟಿಯನ್ನು ಕೊನೆಯಿಂದ ಪಡೆಯಿರಿ";
messages["LISTS_GET_SUBLIST_START_FROM_START"] = "# ನಿಂದ ಉಪ-ಪಟ್ಟಿಯನ್ನು ಪಡೆಯಿರಿ";
messages["LISTS_GET_SUBLIST_TAIL"] = "";  // untranslated
messages["LISTS_GET_SUBLIST_TOOLTIP"] = "ಪಟ್ಟಿಯ ನಿರ್ದಿಷ್ಟ ಭಾಗದ ಪ್ರತಿಯನ್ನು ರಚಿಸುತ್ತದೆ.";
messages["LISTS_INDEX_FROM_END_TOOLTIP"] = "%1 ಕೊನೆಯ ಅಂಶ ಆಗಿದೆ.";
messages["LISTS_INDEX_FROM_START_TOOLTIP"] = "%1 ಮೊದಲ ಅಂಶ ಆಗಿದೆ.";
messages["LISTS_INDEX_OF_FIRST"] = "ಅಂಶದ ಮೊದಲ ಸಂಭವವನ್ನು ಹುಡುಕಿ";
messages["LISTS_INDEX_OF_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
messages["LISTS_INDEX_OF_LAST"] = "ಅಂಶದ ಕೊನೆಯ ಸಂಭವವನ್ನು ಹುಡುಕಿ";
messages["LISTS_INDEX_OF_TOOLTIP"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ಅಂಶದ ಮೊದಲ/ಕೊನೆಯ ಸಂಭಾವ್ಯದ ಸೂಚಿಯನ್ನು ಹಿಂತಿರುಗಿಸುವುದು. ಅಂಶ ಕಂಡುಬರದಿದ್ದರೆ %1 ಅನ್ನು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["LISTS_INLIST"] = "ಪಟ್ಟಿಯಲ್ಲಿ";
messages["LISTS_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
messages["LISTS_ISEMPTY_TITLE"] = "%1 ಖಾಲಿಯಾಗಿದೆ";
messages["LISTS_ISEMPTY_TOOLTIP"] = "ಪಟ್ಟಿ ಖಾಲಿಯಾಗಿದ್ದರೆ ಸತ್ಯ ಎಂದು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
messages["LISTS_LENGTH_TITLE"] = "%1 ರ ಉದ್ದ";
messages["LISTS_LENGTH_TOOLTIP"] = "ಪಟ್ಟಿಯ ಉದ್ದವನ್ನು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["LISTS_REPEAT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
messages["LISTS_REPEAT_TITLE"] = "%1 ಅಂಶದೊಂದಿಗೆ %2 ಬಾರಿ  ಪುನರಾವರ್ತಿತಗೊಂಡ ಪಟ್ಟಿಯನ್ನು ರಚಿಸಿ.";
messages["LISTS_REPEAT_TOOLTIP"] = "ಕೊಟ್ಟಿರುವ ಮೌಲ್ಯವನ್ನು ನಿರ್ದಿಷ್ಟ ಬಾರಿ ಪುನರಾವರ್ತಿಸುವ ಪಟ್ಟಿಯನ್ನು ರಚಿಸುತ್ತದೆ.";
messages["LISTS_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";  // untranslated
messages["LISTS_REVERSE_MESSAGE0"] = "%1 ನ್ನು ಹಿಮ್ಮುಖಗೊಳಿಸಿ";
messages["LISTS_REVERSE_TOOLTIP"] = "ಪಟ್ಟಿಯ ಪ್ರತಿಯನ್ನು ಹಿಮ್ಮುಖಗೊಳಿಸಿ.";
messages["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
messages["LISTS_SET_INDEX_INPUT_TO"] = "ಹಾಗೆ";
messages["LISTS_SET_INDEX_INSERT"] = "ನಲ್ಲಿ ಸೇರಿಸಿ";
messages["LISTS_SET_INDEX_SET"] = "ಗೊತ್ತುಪಡಿಸಿ";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST"] = "ಪಟ್ಟಿಯ ಪ್ರಾರಂಭದಲ್ಲಿ ಅಂಶವನ್ನು ಸೇರಿಸುತ್ತದೆ.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_FROM"] = "ಪಟ್ಟಿಯಲ್ಲಿ ನಿರ್ದಿಷ್ಟಪಡಿಸಿದ ಸ್ಥಾನದಲ್ಲಿ ಅಂಶವನ್ನು ಸೇರಿಸುತ್ತದೆ.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_LAST"] = "ಅಂಶವನ್ನು ಪಟ್ಟಿಯ ಕೊನೆಯಲ್ಲಿ ಸೇರಿಸಿ.";
messages["LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM"] = "ಅಂಶವನ್ನು ಪಟ್ಟಿಯಲ್ಲಿ ಯಾದೃಚ್ಛಿಕವಾಗಿ  ಒಳಸೇರಿಸುತ್ತದೆ.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_FIRST"] = "ಪಟ್ಟಿಯಲ್ಲಿ ಮೊದಲ ಅಂಶವನ್ನು ಗೊತ್ತುಪಡಿಸುತ್ತದೆ.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_FROM"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ನಿರ್ದಿಷ್ಟಪಡಿಸಿದ ಸ್ಥಾನದಲ್ಲಿ ಅಂಶವನ್ನು ಗೊತ್ತುಪಡಿಸುತ್ತದೆ.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_LAST"] = "ಪಟ್ಟಿಯಲ್ಲಿ ಕೊನೆಯ ಅಂಶವನ್ನು ಗೊತ್ತುಪಡಿಸುತ್ತದೆ.";
messages["LISTS_SET_INDEX_TOOLTIP_SET_RANDOM"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ಯಾದೃಚ್ಛಿಕ ಅಂಶವನ್ನು ಗೊತ್ತುಪಡಿಸುತ್ತದೆ.";
messages["LISTS_SORT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
messages["LISTS_SORT_ORDER_ASCENDING"] = "ಆರೋಹಣ";
messages["LISTS_SORT_ORDER_DESCENDING"] = "ಅವರೋಹಣ";
messages["LISTS_SORT_TITLE"] = "%1 %2 %3 ವಿಂಗಡಿಸಿ";
messages["LISTS_SORT_TOOLTIP"] = "ಪಟ್ಟಿಯ ಪ್ರತಿಯನ್ನು ವಿಂಗಡಿಸಿ.";
messages["LISTS_SORT_TYPE_IGNORECASE"] = "ವರ್ಣಮಾಲೆಯ, ದೊಡ್ಡಕ್ಷರ/ಸಣ್ಣಕ್ಷರವನ್ನು ನಿರ್ಲಕ್ಷಿಸಿ";
messages["LISTS_SORT_TYPE_NUMERIC"] = "ಸಂಖ್ಯಾತ್ಮಕ";
messages["LISTS_SORT_TYPE_TEXT"] = "ವರ್ಣಮಾಲೆಯ";
messages["LISTS_SPLIT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
messages["LISTS_SPLIT_LIST_FROM_TEXT"] = "ಪಠ್ಯದಿಂದ ಪಟ್ಟಿಯನ್ನು ಮಾಡಿ";
messages["LISTS_SPLIT_TEXT_FROM_LIST"] = "ಪಟ್ಟಿಯಿಂದ ಪಠ್ಯವನ್ನು ಮಾಡಿ";
messages["LISTS_SPLIT_TOOLTIP_JOIN"] = "ಪ್ರಾರಂಭ ಅಥವಾ ಅಂತ್ಯ ಚಿನ್ಹೆಯಿಂದ ಬೇರ್ಪಡಿಸಲಾಗಿರುವ ಪಠ್ಯಗಳ  ಪಟ್ಟಿಯನ್ನೆಲ್ಲಾ  ಒಂದು ಪಠ್ಯಕ್ಕೆ ಸೇರಿಸಿ.";
messages["LISTS_SPLIT_TOOLTIP_SPLIT"] = "ಪ್ರಾರಂಭ ಅಥವಾ ಅಂತ್ಯ ಚಿನ್ಹೆಯಲ್ಲಿ ಮುರಿದು, ಪಠ್ಯವನ್ನು ವಿಭಜಿಸಿ ಪಠ್ಯಗಳ ಪಟ್ಟಿಮಾಡಿ.";
messages["LISTS_SPLIT_WITH_DELIMITER"] = "ಪ್ರಾರಂಭ ಅಥವಾ ಅಂತ್ಯ ಚಿನ್ಹೆಯೊಡನೆ";
messages["LOGIC_BOOLEAN_FALSE"] = "ಸುಳ್ಳು";
messages["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
messages["LOGIC_BOOLEAN_TOOLTIP"] = "ಸತ್ಯ ಅಥವಾ ಸುಳ್ಳು  ಎರಡರಲ್ಲಿ ಒಂದನ್ನು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["LOGIC_BOOLEAN_TRUE"] = "ಸತ್ಯ";
messages["LOGIC_COMPARE_HELPURL"] = "https://en.wikipedia.org/wiki/Inequality_(mathematics)";
messages["LOGIC_COMPARE_TOOLTIP_EQ"] = "ಎರಡೂ ಒದಗಿಸುವ ಅಂಶಗಳು ಪರಸ್ಪರ ಸಮನಾಗಿದ್ದರೆ, ಸರಿ ಹಿಂತಿರುಗಿಸಿ.";
messages["LOGIC_COMPARE_TOOLTIP_GT"] = "ಮೊದಲನೇ ಒದಗಿಸುವ ಅಂಶ ಎರಡನೇ ಒದಗಿಸುವ ಅಂಶಕ್ಕಿಂತ ದೊಡ್ಡದಾಗಿದ್ದರೆ ಸರಿ ಹಿಂತಿರುಗಿಸಿ.";
messages["LOGIC_COMPARE_TOOLTIP_GTE"] = "ಮೊದಲನೇ ಒದಗಿಸುವ ಅಂಶ ಎರಡನೇ ಒದಗಿಸುವ ಅಂಶಕ್ಕಿಂತ ದೊಡ್ಡದು ಅಥವಾ ಸಮನಾಗಿದ್ದರೆ ಸರಿ ಹಿಂತಿರುಗಿಸಿ.";
messages["LOGIC_COMPARE_TOOLTIP_LT"] = "ಮೊದಲನೇ ಒದಗಿಸುವ ಅಂಶ ಎರಡನೇ ಒದಗಿಸುವ ಅಂಶಕ್ಕಿಂತ ಚಿಕ್ಕದ್ದಾಗಿದ್ದರೆ ಸರಿ ಹಿಂತಿರುಗಿಸಿ.";
messages["LOGIC_COMPARE_TOOLTIP_LTE"] = "ಮೊದಲನೇ ಒದಗಿಸುವ ಅಂಶ ಎರಡನೇ ಒದಗಿಸುವ ಅಂಶಕ್ಕಿಂತ ಚಿಕ್ಕದು ಅಥವಾ ಸಮನಾಗಿದ್ದರೆ ಸರಿ ಹಿಂತಿರುಗಿಸಿ.";
messages["LOGIC_COMPARE_TOOLTIP_NEQ"] = "ಎರಡೂ ಒದಗಿಸುವ ಅಂಶಗಳು ಪರಸ್ಪರ ಸಮನಾಗಿರದಿದ್ದರೆ ಸರಿ ಹಿಂತಿರುಗಿಸಿ.";
messages["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
messages["LOGIC_NEGATE_TITLE"] = "%1 ಅಲ್ಲ";
messages["LOGIC_NEGATE_TOOLTIP"] = "ಒದಗಿಸುವ ಅಂಶ ಸುಳ್ಳಾಗಿದ್ದರೆ ಸರಿಯೆನ್ನಿ. ಒದಗಿಸುವ ಅಂಶ ಸತ್ಯವಾಗಿದ್ದರೆ ತಪ್ಪೆನ್ನಿ.";
messages["LOGIC_NULL"] = "ಶೂನ್ಯ";
messages["LOGIC_NULL_HELPURL"] = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
messages["LOGIC_NULL_TOOLTIP"] = "ಶೂನ್ಯವನ್ನು  ಹಿಂತಿರುಗಿಸಿ.";
messages["LOGIC_OPERATION_AND"] = "ಮತ್ತು";
messages["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
messages["LOGIC_OPERATION_OR"] = "ಅಥವಾ";
messages["LOGIC_OPERATION_TOOLTIP_AND"] = "ಒದಗಿಸುವ ಎರಡೂ ಅಂಶಗಳು ಸರಿಯಾಗಿದ್ದರೆ ಸರಿ ಹಿಂತಿರುಗಿಸಿ.";
messages["LOGIC_OPERATION_TOOLTIP_OR"] = "ಯಾವುದಾದರೂ ಒಂದು ಒದಗಿಸುವ ಅಂಶ ಸತ್ಯವಾಗಿದ್ದರೆ ಸರಿ ಹಿಂತಿರುಗಿಸಿ.";
messages["LOGIC_TERNARY_CONDITION"] = "ಪರೀಕ್ಷೆ";
messages["LOGIC_TERNARY_HELPURL"] = "https://en.wikipedia.org/wiki/%3F:";  // untranslated
messages["LOGIC_TERNARY_IF_FALSE"] = "ಸುಳ್ಳು ಆಗಿದ್ದರೆ";
messages["LOGIC_TERNARY_IF_TRUE"] = "ಸತ್ಯ ಆಗಿದ್ದರೆ";
messages["LOGIC_TERNARY_TOOLTIP"] = "'ಪರೀಕ್ಷೆ'ಯಲ್ಲಿನ ಷರತ್ತನ್ನು ಪರಿಶೀಲಿಸಿ. ಷರತ್ತು ಸರಿಯಾಗಿದ್ದರೆ, 'ಸತ್ಯವಾಗಿದ್ದರೆ' ಮೌಲ್ಯವನ್ನು; ಇಲ್ಲದಿದ್ದರೆ 'ಸುಳ್ಳಾಗಿದ್ದರೆ' ಮೌಲ್ಯವನ್ನೂ ಹಿಂತಿರುಗಿಸುವುದು.";
messages["MATH_ADDITION_SYMBOL"] = "+";  // untranslated
messages["MATH_ARITHMETIC_HELPURL"] = "https://en.wikipedia.org/wiki/Arithmetic";
messages["MATH_ARITHMETIC_TOOLTIP_ADD"] = "ಎರಡು ಸಂಖ್ಯೆಗಳ ಮೊತ್ತವನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "ಎರಡು ಸಂಖ್ಯೆಗಳ ಭಾಗಲಬ್ಧವನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "ಎರಡು ಸಂಖ್ಯೆಗಳ ವ್ಯತ್ಯಾಸವನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "ಎರಡು ಸಂಖ್ಯೆಗಳ ಗುಣಲಬ್ಧವನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_ARITHMETIC_TOOLTIP_POWER"] = "ಮೊದಲ ಸಂಖ್ಯೆಯ ಘಾತಾಂಶ ಎರಡನೇ ಸಂಖ್ಯೆಯಾದಾಗಿನ ಫಲಿತಾಂಶವನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_ATAN2_HELPURL"] = "https://en.wikipedia.org/wiki/Atan2";
messages["MATH_ATAN2_TITLE"] = "X:%1 Y:%2 ಬಿಂದುವಿನ ಆರ್ಕ್ ಟ್ಯಾನ್";
messages["MATH_ATAN2_TOOLTIP"] = "ಬಿಂದು (X,Y) ನ  ಆರ್ಕ್ ಟ್ಯಾಂಜೆಂಟ್ ನ್ನು -180 ರಿಂದ 180 ರವರೆಗಿನ ಡಿಗ್ರಿಗಳಲ್ಲಿ ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_CHANGE_HELPURL"] = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
messages["MATH_CHANGE_TITLE"] = "%1 ಅನ್ನು %2 ರಿಂದ ಬದಲಾಯಿಸಿ";
messages["MATH_CHANGE_TOOLTIP"] = "ಚರಾಂಶ '%1' ಕ್ಕೆ ಒಂದು ಸಂಖ್ಯೆಯನ್ನು ಸೇರಿಸಿ.";
messages["MATH_CONSTANT_HELPURL"] = "https://en.wikipedia.org/wiki/Mathematical_constant";
messages["MATH_CONSTANT_TOOLTIP"] = "ಸಾಮಾನ್ಯ ಸ್ಥಿರಾಂಕಗಳಲ್ಲಿ ಒಂದನ್ನು ಹಿಂತಿರುಗಿಸಿ:π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (infinity).";
messages["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
messages["MATH_CONSTRAIN_TITLE"] = "%1ಅನ್ನು  ಕಡಿಮೆ %2 ಹೆಚ್ಚಿನ %3  ಮೌಲ್ಯಗಳ ನಡುವೆ  ನಿರ್ಬಂಧಿಸಿ";
messages["MATH_CONSTRAIN_TOOLTIP"] = "ನಿಗದಿತ ಮಿತಿಗಳ ನಡುವೆ ಸಂಖ್ಯೆಯನ್ನು ನಿರ್ಬಂಧಿಸಿ(ಒಳಗೊ೦ಡ).";
messages["MATH_DIVISION_SYMBOL"] = "÷";  // untranslated
messages["MATH_IS_DIVISIBLE_BY"] = "ಇದರಿಂದ ಭಾಗಿಸಬಹುದೇ?";
messages["MATH_IS_EVEN"] = "ಸಮ ಸಂಖ್ಯೆಯೇ?";
messages["MATH_IS_NEGATIVE"] = "ಋಣಾತ್ಮಕವೇ?";
messages["MATH_IS_ODD"] = "ಬೆಸ ಸಂಖ್ಯೆಯೇ?";
messages["MATH_IS_POSITIVE"] = "ಧನಾತ್ಮಕವೇ?";
messages["MATH_IS_PRIME"] = "ಅವಿಭಾಜ್ಯ ಸಂಖ್ಯೆಯೇ?";
messages["MATH_IS_TOOLTIP"] = "ಒಂದು ಸಂಖ್ಯೆ ಸಮ, ಬೆಸ, ಅವಿಭಾಜ್ಯ, ಪೂರ್ಣ, ಧನಾತ್ಮಕ, ಋಣಾತ್ಮಕವಾಗಿದೆಯೇ ಅಥವಾ ನಿರ್ದಿಷ್ಟ ಸಂಖ್ಯೆಯಿಂದ ಭಾಗಿಸ ಬಹುದೇ ಎಂದು ಪರಿಶೀಲಿಸಿ. ಸತ್ಯ ಅಥವಾ ಸುಳ್ಳು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_IS_WHOLE"] = "ಪೂರ್ಣಸಂಖ್ಯೆಯೇ?";
messages["MATH_MODULO_HELPURL"] = "https://en.wikipedia.org/wiki/Modulo_operation";
messages["MATH_MODULO_TITLE"] = "%1 ÷ %2 ರ ಶೇಷ";
messages["MATH_MODULO_TOOLTIP"] = "ಎರಡು ಸಂಖ್ಯೆಗಳ ವಿಭಜನೆಯ ಶೇಷವನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_MULTIPLICATION_SYMBOL"] = "×";  // untranslated
messages["MATH_NUMBER_HELPURL"] = "https://en.wikipedia.org/wiki/Number";
messages["MATH_NUMBER_TOOLTIP"] = "ಒಂದು ಸಂಖ್ಯೆ.";
messages["MATH_ONLIST_HELPURL"] = "";  // untranslated
messages["MATH_ONLIST_OPERATOR_AVERAGE"] = "ಪಟ್ಟಿಯ ಸರಾಸರಿ";
messages["MATH_ONLIST_OPERATOR_MAX"] = "ಪಟ್ಟಿಯ ಗರಿಷ್ಠ";
messages["MATH_ONLIST_OPERATOR_MEDIAN"] = "ಪಟ್ಟಿಯ ಮಧ್ಯಾಂಕ";
messages["MATH_ONLIST_OPERATOR_MIN"] = "ಪಟ್ಟಿಯ ಕನಿಷ್ಠ";
messages["MATH_ONLIST_OPERATOR_MODE"] = "ಪಟ್ಟಿಯಲ್ಲಿನ  ಆಗಾಗ್ಗೆ ಕಾಣಿಸಿಕೊಳ್ಳುವ ಸಂಖ್ಯೆಗಳು";
messages["MATH_ONLIST_OPERATOR_RANDOM"] = "ಪಟ್ಟಿಯ ಯಾದೃಚ್ಛಿತ ಅಂಶ";
messages["MATH_ONLIST_OPERATOR_STD_DEV"] = "ಪಟ್ಟಿಯ ಪ್ರಮಾಣಿತ ವಿಚಲನ";
messages["MATH_ONLIST_OPERATOR_SUM"] = "ಪಟ್ಟಿಯ ಮೊತ್ತ";
messages["MATH_ONLIST_TOOLTIP_AVERAGE"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ಸಂಖ್ಯಾ ಮೌಲ್ಯಗಳ ಸರಾಸರಿ (ಅಂಕಗಣಿತದ ಸರಾಸರಿ) ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_ONLIST_TOOLTIP_MAX"] = "ಪಟ್ಟಿಯಲ್ಲಿರುವ ಗರಿಷ್ಠ ಸಂಖ್ಯೆಯನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_ONLIST_TOOLTIP_MEDIAN"] = "ಪಟ್ಟಿಯಲ್ಲಿನ ಮಧ್ಯಾಂಕ ಸಂಖ್ಯೆಯನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_ONLIST_TOOLTIP_MIN"] = "ಪಟ್ಟಿಯಲ್ಲಿರುವ ಕನಿಷ್ಠ ಸಂಖ್ಯೆಯನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_ONLIST_TOOLTIP_MODE"] = "ಪಟ್ಟಿಯಲ್ಲಿರುವ ಸಾಮಾನ್ಯ ಅಂಶಗಳ ಪಟ್ಟಿಯನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_ONLIST_TOOLTIP_RANDOM"] = "ಪಟ್ಟಿಯ ಯಾದೃಚ್ಛಿತ ಅಂಶವನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_ONLIST_TOOLTIP_STD_DEV"] = "ಪಟ್ಟಿಯ ಪ್ರಮಾಣಿತ ವಿಚಲನವನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_ONLIST_TOOLTIP_SUM"] = "ಪಟ್ಟಿಯಲ್ಲಿರುವ ಎಲ್ಲಾ ಸಂಖ್ಯೆಗಳ ಮೊತ್ತವನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_POWER_SYMBOL"] = "^";  // untranslated
messages["MATH_RANDOM_FLOAT_HELPURL"] = "https://en.wikipedia.org/wiki/Random_number_generation";
messages["MATH_RANDOM_FLOAT_TITLE_RANDOM"] = "ಯಾದೃಚ್ಛಿತ ಭಿನ್ನರಾಶಿ";
messages["MATH_RANDOM_FLOAT_TOOLTIP"] = "0.0 (ಒಳಗೊಂಡ) ಮತ್ತು 1.0 (ವಿಶೇಷ) ನಡುವೆ ಯಾದೃಚ್ಛಿತ ಭಿನ್ನರಾಶಿಯನ್ನು  ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_RANDOM_INT_HELPURL"] = "https://en.wikipedia.org/wiki/Random_number_generation";
messages["MATH_RANDOM_INT_TITLE"] = "ಯಾದೃಚ್ಛಿತ ಪೂರ್ಣಾಂಕ %1 ರಿಂದ %2 ರವರೆಗೆ";
messages["MATH_RANDOM_INT_TOOLTIP"] = "ಎರಡು ನಿರ್ದಿಷ್ಟ ಮಿತಿಗಳ ನಡುವೆ ಇರುವ ಯಾದೃಚ್ಛಿತ ಪೂರ್ಣಾಂಕವನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_ROUND_HELPURL"] = "https://en.wikipedia.org/wiki/Rounding";
messages["MATH_ROUND_OPERATOR_ROUND"] = "ಸುತ್ತು";
messages["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "ಕೆಳಗಿನ ಪೂರ್ಣಾಂಕ ಮಾಡಿ.";
messages["MATH_ROUND_OPERATOR_ROUNDUP"] = "ಮೇಲಿನ ಪೂರ್ಣಾಂಕ ಮಾಡಿ.";
messages["MATH_ROUND_TOOLTIP"] = "ಒಂದು ಸಂಖ್ಯೆಯನ್ನು ಮೇಲಿನ ಅಥವಾ ಕೆಳಗಿನ ಪೂರ್ಣಾಂಕ ಮಾಡಿ.";
messages["MATH_SINGLE_HELPURL"] = "https://en.wikipedia.org/wiki/Square_root";
messages["MATH_SINGLE_OP_ABSOLUTE"] = "ಪರಿಪೂರ್ಣ";
messages["MATH_SINGLE_OP_ROOT"] = "ವರ್ಗಮೂಲ";
messages["MATH_SINGLE_TOOLTIP_ABS"] = "ಸಂಖ್ಯೆಯೊಂದರ ಪರಿಪೂರ್ಣ ಮೌಲ್ಯವನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_SINGLE_TOOLTIP_EXP"] = "ಒಂದು ಸಂಖ್ಯೆಯ e ಘಾತವಾಗಿದ್ದಾಗಿನ ಮೌಲ್ಯವನ್ನು  ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_SINGLE_TOOLTIP_LN"] = "ಸಂಖ್ಯೆಯ ನೈಸರ್ಗಿಕ ಲಾಗರಿಥಮ್ ಅನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_SINGLE_TOOLTIP_LOG10"] = "ಒಂದು ಸಂಖ್ಯೆಯ ಆಧಾರ 10 ಲಾಗರಿಥಮನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_SINGLE_TOOLTIP_NEG"] = "ಸಂಖ್ಯೆಯೊಂದರ ನಿರಾಕರಣೆಯನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_SINGLE_TOOLTIP_POW10"] = "ಒಂದು ಸಂಖ್ಯೆಯ 10ರ ಘಾತವಾಗಿದ್ದಾಗಿನ ಮೌಲ್ಯವನ್ನು  ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_SINGLE_TOOLTIP_ROOT"] = "ಸಂಖ್ಯೆಯ ವರ್ಗಮೂಲವನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_SUBTRACTION_SYMBOL"] = "-";  // untranslated
messages["MATH_TRIG_ACOS"] = "acos";  // untranslated
messages["MATH_TRIG_ASIN"] = "asin";  // untranslated
messages["MATH_TRIG_ATAN"] = "atan";  // untranslated
messages["MATH_TRIG_COS"] = "cos";  // untranslated
messages["MATH_TRIG_HELPURL"] = "https://en.wikipedia.org/wiki/Trigonometric_functions";
messages["MATH_TRIG_SIN"] = "sin";  // untranslated
messages["MATH_TRIG_TAN"] = "tan";  // untranslated
messages["MATH_TRIG_TOOLTIP_ACOS"] = "ಸಂಖ್ಯೆಯೊಂದರ ಆರ್ಕ್ ಕೊಸೈನ್ ಅನ್ನು ಹಿಂತಿರುಗಿಸಿ(ರೇಡಿಯನ್‌ಗಳಲ್ಲ)";
messages["MATH_TRIG_TOOLTIP_ASIN"] = "ಸಂಖ್ಯೆಯೊಂದರ ಆರ್ಕ್ ಸೈನ್ ಅನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["MATH_TRIG_TOOLTIP_ATAN"] = "ಸಂಖ್ಯೆಯೊಂದರ ಆರ್ಕ್ ಟ್ಯಾಂಜೆಂಟ್ ಅನ್ನು ಹಿಂತಿರುಗಿಸಿ(ರೇಡಿಯನ್‌ಗಳಲ್ಲ)";
messages["MATH_TRIG_TOOLTIP_COS"] = "ಕೋನವೊಂದರ ಕೊಸೈನ್ ಅನ್ನು ಹಿಂತಿರುಗಿಸಿ(ರೇಡಿಯನ್‌ಗಳಲ್ಲ)";
messages["MATH_TRIG_TOOLTIP_SIN"] = "ಕೋನವೊಂದರ ಸೈನ್ ಅನ್ನು ಹಿಂತಿರುಗಿಸಿ(ರೇಡಿಯನ್‌ಗಳಲ್ಲ)";
messages["MATH_TRIG_TOOLTIP_TAN"] = "ಕೋನವೊಂದರ ಟ್ಯಾಂಜೆಂಟ್ ಅನ್ನು ಹಿಂತಿರುಗಿಸಿ(ರೇಡಿಯನ್‌ಗಳಲ್ಲ)";
messages["NEW_COLOUR_VARIABLE"] = "ಬಣ್ಣದ ಚರಾಂಶವನ್ನು ಸೃಷ್ಟಿಸು ...";
messages["NEW_NUMBER_VARIABLE"] = "ಸಂಖ್ಯಾ ಚರಾಂಶವನ್ನು ಸೃಷ್ಟಿಸು ...";
messages["NEW_STRING_VARIABLE"] = "ಚಿಹ್ನೆಗಳ ಸರಣಿಯ ಚರಾಂಶವನ್ನು ಸೃಷ್ಟಿಸು...";
messages["NEW_VARIABLE"] = "ಚರಾಂಶವನ್ನು ಸೃಷ್ಟಿಸು ...";
messages["NEW_VARIABLE_TITLE"] = "ಹೊಸ ಚರಾಂಶದ ಹೆಸರು:";
messages["NEW_VARIABLE_TYPE_TITLE"] = "ಹೊಸ ಚರಾಂಶದ ಡೇಟಾಪ್ರಕಾರ:";
messages["ORDINAL_NUMBER_SUFFIX"] = "";  // untranslated
messages["PROCEDURES_ALLOW_STATEMENTS"] = "ಹೇಳಿಕೆಗಳನ್ನು ಅನುಮತಿಸಿ";
messages["PROCEDURES_BEFORE_PARAMS"] = "ಜೊತೆ:";
messages["PROCEDURES_CALLNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
messages["PROCEDURES_CALLNORETURN_TOOLTIP"] = "ಬಳಕೆದಾರ-ವ್ಯಾಖ್ಯಾನಿತ ಕಾರ್ಯಘಟಕ '%1'ಅನ್ನು ಚಲಾಯಿಸಿ.";
messages["PROCEDURES_CALLRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";
messages["PROCEDURES_CALLRETURN_TOOLTIP"] = "ಬಳಕೆದಾರ-ವ್ಯಾಖ್ಯಾನಿತ ಕಾರ್ಯಘಟಕ '%1'ಅನ್ನು ಚಲಾಯಿಸಿ ಮತ್ತು ಅದರ ಹೊರಾಂಶವನ್ನು ಉಪಯೋಗಿಸಿ";
messages["PROCEDURES_CALL_BEFORE_PARAMS"] = "ಜೊತೆ:";
messages["PROCEDURES_CREATE_DO"] = "'%1' ರಚಿಸಿ";
messages["PROCEDURES_DEFNORETURN_COMMENT"] = "ಈ ಕಾರ್ಯಘಟಕವನ್ನು ವಿವರಿಸಿ ...";
messages["PROCEDURES_DEFNORETURN_DO"] = "";  // untranslated
messages["PROCEDURES_DEFNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
messages["PROCEDURES_DEFNORETURN_PROCEDURE"] = "ಏನಾದರೂ ಮಾಡಿ";
messages["PROCEDURES_DEFNORETURN_TITLE"] = "ಗೆ";
messages["PROCEDURES_DEFNORETURN_TOOLTIP"] = "ಯಾವುದೇ ಹೊರಾಂಶ ಇಲ್ಲದ ಕಾರ್ಯಘಟಕವನ್ನು ರಚಿಸುತ್ತದೆ.";
messages["PROCEDURES_DEFRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
messages["PROCEDURES_DEFRETURN_RETURN"] = "ಹಿಂತಿರುಗಿಸಿ";
messages["PROCEDURES_DEFRETURN_TOOLTIP"] = "ಹೊರಾಂಶ ಇರುವ ಕಾರ್ಯ ಘಟಕವನ್ನು ರಚಿಸುತ್ತದೆ.";
messages["PROCEDURES_DEF_DUPLICATE_WARNING"] = "ಎಚ್ಚರಿಕೆ: ಈ ಕಾರ್ಯಘಟಕವು ನಕಲಿ ನಿಯತಾಂಕಗಳನ್ನು ಹೊಂದಿದೆ.";
messages["PROCEDURES_HIGHLIGHT_DEF"] = "ಕಾರ್ಯಘಟಕದ ವ್ಯಾಖ್ಯಾನವನ್ನು ಹೈಲೈಟ್ ಮಾಡಿ";
messages["PROCEDURES_IFRETURN_HELPURL"] = "http://c2.com/cgi/wiki?GuardClause";  // untranslated
messages["PROCEDURES_IFRETURN_TOOLTIP"] = "ಒಂದು ಮೌಲ್ಯವು ಸತ್ಯವಾಗಿದ್ದರೆ, ಎರಡನೇ ಮೌಲ್ಯವನ್ನು ಹಿಂತಿರುಗಿಸಿ.";
messages["PROCEDURES_IFRETURN_WARNING"] = "ಎಚ್ಚರಿಕೆ: ಈ ಬ್ಲಾಕ್ ಅನ್ನು ಕಾರ್ಯಘಟಕದ ವ್ಯಾಖ್ಯಾನದಲ್ಲಿ ಮಾತ್ರ ಬಳಸಬಹುದು.";
messages["PROCEDURES_MUTATORARG_TITLE"] = "ಒಳಾoಶದ ಹೆಸರು:";
messages["PROCEDURES_MUTATORARG_TOOLTIP"] = "ಕಾರ್ಯಘಟಕಕ್ಕೆ  ಒಳಾoಶವನ್ನು  ಸೇರಿಸಿ.";
messages["PROCEDURES_MUTATORCONTAINER_TITLE"] = "ಒಳಾoಶಗಳು";
messages["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "ಈ ಕಾರ್ಯಕ್ಕೆ ಒಳಾoಶಗಳನ್ನು ಸೇರಿಸಿ, ತೆಗೆದುಹಾಕಿ ಅಥವಾ ಮರುಕ್ರಮಗೊಳಿಸಿ.";
messages["REDO"] = "ಮತ್ತೆ ಮಾಡು";
messages["REMOVE_COMMENT"] = "ಟಿಪ್ಪಣಿ ಅಳಿಸು";
messages["RENAME_VARIABLE"] = "ಚರಾಂಶವನ್ನು ಮರುಹೆಸರಿಸು...";
messages["RENAME_VARIABLE_TITLE"] = "ಎಲ್ಲ '%1' ಚರಾಂಶಗಳನ್ನು ಮರುಹೆಸರಿಸು:";
messages["TEXT_APPEND_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
messages["TEXT_APPEND_TITLE"] = " %1 ಕ್ಕೆ  ಪಠ್ಯ  %2 ನ್ನು ಕೊನೆಯಲ್ಲಿ ಸೇರಿಸಿ.";
messages["TEXT_APPEND_TOOLTIP"] = "'%1' ಚರಾಂಶಕ್ಕೆ  ಕೆಲವು ಪಠ್ಯವನ್ನು ಕೊನೆಯಲ್ಲಿ ಸೇರಿಸಿ.";
messages["TEXT_CHANGECASE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
messages["TEXT_CHANGECASE_OPERATOR_LOWERCASE"] = "ಸಣ್ಣಕ್ಷರಕ್ಕೆ";
messages["TEXT_CHANGECASE_OPERATOR_TITLECASE"] = "ಶೀರ್ಷಿಕೆಯ ಅಕ್ಷರವಾಗಿ";
messages["TEXT_CHANGECASE_OPERATOR_UPPERCASE"] = "ದೊಡ್ಡಕ್ಷರಕ್ಕೆ";
messages["TEXT_CHANGECASE_TOOLTIP"] = "ಪಠ್ಯದ ಪ್ರತಿಯನ್ನು ಪ್ರಸ್ತುತಕ್ಕೆ ವಿರುದ್ಡವಾದ ದೊಡ್ಡಕ್ಷರ ಅಥವಾ ಸಣ್ಣಕ್ಷರದಲ್ಲಿ ಹಿಂತಿರುಗಿಸಿ.";
messages["TEXT_CHARAT_FIRST"] = "ಮೊದಲ ಅಕ್ಷರವನ್ನು ಪಡೆಯಿರಿ";
messages["TEXT_CHARAT_FROM_END"] = "ಕೊನೆಯಿಂದ # ಅಕ್ಷರ  ಪಡೆಯಿರಿ";
messages["TEXT_CHARAT_FROM_START"] = "# ಅಕ್ಷರ  ಪಡೆಯಿರಿ";
messages["TEXT_CHARAT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
messages["TEXT_CHARAT_LAST"] = "ಕೊನೆಯ ಅಕ್ಷರವನ್ನು ಪಡೆಯಿರಿ";
messages["TEXT_CHARAT_RANDOM"] = "ಯಾದೃಚ್ಛಿತ ಅಕ್ಷರವನ್ನು ಪಡೆಯಿರಿ";
messages["TEXT_CHARAT_TAIL"] = "";  // untranslated
messages["TEXT_CHARAT_TITLE"] = "ಪಠ್ಯದಲ್ಲಿ %1 %2";
messages["TEXT_CHARAT_TOOLTIP"] = "ನಿರ್ದಿಷ್ಟಪಡಿಸಿದ ಸ್ಥಾನದಲ್ಲಿನ ಅಕ್ಷರವನ್ನು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["TEXT_COUNT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#counting-substrings";  // untranslated
messages["TEXT_COUNT_MESSAGE0"] = "%2 ರಲ್ಲಿ %1 ಅನ್ನು ಎಣಿಸಿ";
messages["TEXT_COUNT_TOOLTIP"] = "ಬೇರೆ ಕೆಲವು ಪಠ್ಯಗಳಲ್ಲಿ ಕೆಲವು ಪಠ್ಯವು ಎಷ್ಟು ಬಾರಿ ಸಂಭವಿಸುತ್ತದೆ ಎಂಬುದನ್ನು ಎಣಿಸಿ.";
messages["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "ಪಠ್ಯಕ್ಕೆ ಒಂದು ಅಂಶವನ್ನು ಸೇರಿಸಿ.";
messages["TEXT_CREATE_JOIN_TITLE_JOIN"] = "ಸೇರಿಸು";
messages["TEXT_CREATE_JOIN_TOOLTIP"] = "ಈ ಬ್ಲಾಕನ್ನು ಮರು ಸಂರಚಿಸಲು ಅದರ ಭಾಗಗಳನ್ನು ಸೇರಿಸು, ತೆಗೆ ಅಥವಾ ಮರುಕ್ರಮಗೊಳಿಸು.";
messages["TEXT_GET_SUBSTRING_END_FROM_END"] = "ಕೊನೆಯಿಂದ # ಅಕ್ಷರದವರೆಗೆ";
messages["TEXT_GET_SUBSTRING_END_FROM_START"] = "# ಅಕ್ಷರದವರೆಗೆ";
messages["TEXT_GET_SUBSTRING_END_LAST"] = "ಕೊನೆಯ ಅಕ್ಷರದವರೆಗೆ";
messages["TEXT_GET_SUBSTRING_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
messages["TEXT_GET_SUBSTRING_INPUT_IN_TEXT"] = "ಪಠ್ಯದಲ್ಲಿ";
messages["TEXT_GET_SUBSTRING_START_FIRST"] = "ಮೊದಲ ಅಕ್ಷರದಿಂದ ಉಪಸರಣಿಯನ್ನು ಪಡೆಯಿರಿ";
messages["TEXT_GET_SUBSTRING_START_FROM_END"] = "# ಅಕ್ಷರದಿಂದ  ಚಿಹ್ನೆಗಳ ಉಪಸರಣಿಯನ್ನು ಕೊನೆಯಿಂದ  ಪಡೆಯಿರಿ";
messages["TEXT_GET_SUBSTRING_START_FROM_START"] = "# ಅಕ್ಷರದಿಂದ ಚಿಹ್ನೆಗಳ ಉಪಸರಣಿಯನ್ನು ಪಡೆಯಿರಿ";
messages["TEXT_GET_SUBSTRING_TAIL"] = "";  // untranslated
messages["TEXT_GET_SUBSTRING_TOOLTIP"] = "ಪಠ್ಯದ ನಿರ್ದಿಷ್ಟ ಭಾಗವನ್ನು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["TEXT_INDEXOF_HELPURL"] = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
messages["TEXT_INDEXOF_OPERATOR_FIRST"] = "ಪಠ್ಯದ ಮೊದಲ ಸಂಭವವನ್ನು ಹುಡುಕಿ";
messages["TEXT_INDEXOF_OPERATOR_LAST"] = "ಪಠ್ಯದ ಕೊನೆಯ ಸಂಭವವನ್ನು ಹುಡುಕಿ";
messages["TEXT_INDEXOF_TITLE"] = "ಪಠ್ಯದಲ್ಲಿ %1 %2 %3";
messages["TEXT_INDEXOF_TOOLTIP"] = "ಎರಡನೇ ಪಠ್ಯದಲ್ಲಿ ಮೊದಲ ಪಠ್ಯದ ಸಂಭಾವ್ಯದ, ಮೊದಲ/ಕೊನೆಯ ಸೂಚ್ಯಂಕವನ್ನು ಹಿಂತಿರುಗಿಸುವುದು. ಪಠ್ಯ ಕಂಡುಬಂದಿಲ್ಲದಿದ್ದರೆ %1 ಅನ್ನು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["TEXT_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
messages["TEXT_ISEMPTY_TITLE"] = "%1 ಖಾಲಿಯಿದೆ";
messages["TEXT_ISEMPTY_TOOLTIP"] = "ಒದಗಿಸಿದ ಪಠ್ಯ ಖಾಲಿಯಾಗಿದ್ದರೆ  'ಸತ್ಯ' ಹಿಂತಿರುಗಿಸುವುದು.";
messages["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
messages["TEXT_JOIN_TITLE_CREATEWITH"] = "ಇದರೊಂದಿಗೆ ಪಠ್ಯವನ್ನು ರಚಿಸಿ";
messages["TEXT_JOIN_TOOLTIP"] = "ಹಲವಾರು ಅಂಶಗಳನ್ನು ಒಟ್ಟುಗೂಡಿಸುವ ಮೂಲಕ ಪಠ್ಯದ ತುಣುಕನ್ನು ರಚಿಸಿ.";
messages["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
messages["TEXT_LENGTH_TITLE"] = "%1ರ ಉದ್ದ";
messages["TEXT_LENGTH_TOOLTIP"] = "ಒದಗಿಸಿದ ಪಠ್ಯದಲ್ಲಿನ ಅಕ್ಷರಗಳ ಸಂಖ್ಯೆಯನ್ನು (ಖಾಲಿ ಜಾಗ ಒಳಗೊಂಡಂತೆ) ಹಿಂತಿರುಗಿಸುವುದು.";
messages["TEXT_PRINT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
messages["TEXT_PRINT_TITLE"] = "%1 ಮುದ್ರಿಸಿ";
messages["TEXT_PRINT_TOOLTIP"] = "ನಿರ್ದಿಷ್ಟಪಡಿಸಿದ ಪಠ್ಯ, ಸಂಖ್ಯೆ ಅಥವಾ ಇತರ ಮೌಲ್ಯವನ್ನು ಮುದ್ರಿಸಿ.";
messages["TEXT_PROMPT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
messages["TEXT_PROMPT_TOOLTIP_NUMBER"] = "ಬಳಕೆದಾರರಿಗೆ  ಸಂಖ್ಯೆಗಾಗಿ ಜ್ಞಾಪಿಸಿ.";
messages["TEXT_PROMPT_TOOLTIP_TEXT"] = "ಬಳಕೆದಾರರಿಗೆ  ಕೆಲವು ಪಠ್ಯಕ್ಕಾಗಿ ಜ್ಞಾಪಿಸಿ.";
messages["TEXT_PROMPT_TYPE_NUMBER"] = "ಸಂದೇಶದೊಂದಿಗೆ ಸಂಖ್ಯೆಗಾಗಿ ಜ್ಞಾಪಿಸಿ";
messages["TEXT_PROMPT_TYPE_TEXT"] = "ಸಂದೇಶದೊಂದಿಗೆ ಪಠ್ಯಕ್ಕಾಗಿ ಜ್ಞಾಪಿಸಿ";
messages["TEXT_REPLACE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#replacing-substrings";  // untranslated
messages["TEXT_REPLACE_MESSAGE0"] = "%1 ಅನ್ನು %3 ರಲ್ಲಿ %2 ರೊಂದಿಗೆ ಬದಲಾಯಿಸಿ.";
messages["TEXT_REPLACE_TOOLTIP"] = "ಬೇರೆ ಪಠ್ಯದೊಳಗಿನ ಎಲ್ಲಾ ಕೆಲವು ಪಠ್ಯದ ಸಂಭಾವ್ಯಗಳನ್ನು  ಬದಲಾಯಿಸಿ.";
messages["TEXT_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#reversing-text";  // untranslated
messages["TEXT_REVERSE_MESSAGE0"] = "%1 ಅನ್ನು ಹಿಮ್ಮುಖಗೊಳಿಸಿ.";
messages["TEXT_REVERSE_TOOLTIP"] = "ಪಠ್ಯದಲ್ಲಿನ ಅಕ್ಷರಗಳ ಕ್ರಮವನ್ನು ಹಿಮ್ಮುಖಗೊಳಿಸಿ.";
messages["TEXT_TEXT_HELPURL"] = "https://en.wikipedia.org/wiki/String_(computer_science)";
messages["TEXT_TEXT_TOOLTIP"] = "ಒಂದು ಅಕ್ಷರ, ಪದ ಅಥವಾ ಪಠ್ಯದ ಸಾಲು.";
messages["TEXT_TRIM_HELPURL"] = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
messages["TEXT_TRIM_OPERATOR_BOTH"] = "ಎರಡೂ ಕಡೆಯಿಂದ ಖಾಲಿ ಜಾಗಗಳನ್ನು ಕತ್ತರಿಸಿ ಹಾಕಿ";
messages["TEXT_TRIM_OPERATOR_LEFT"] = "ಎಡಗಡೆಯಿಂದ ಖಾಲಿ ಜಾಗಗಳನ್ನು ಕತ್ತರಿಸಿ ಹಾಕಿ";
messages["TEXT_TRIM_OPERATOR_RIGHT"] = "ಬಲಗಡೆಯಿಂದ ಖಾಲಿ ಜಾಗಗಳನ್ನು ಕತ್ತರಿಸಿ ಹಾಕಿ";
messages["TEXT_TRIM_TOOLTIP"] = "ಒಂದು ಅಥವಾ ಎರಡೂ ತುದಿಗಳಿಂದ ತೆಗೆದುಹಾಕಲಾದ ಖಾಲಿ ಜಾಗ ಒಳಗೊಂಡಂತೆ ಪಠ್ಯದ ಪ್ರತಿಯನ್ನು ಹಿಂತಿರುಗಿಸುವುದು.";
messages["TODAY"] = "ಇಂದು";
messages["UNDO"] = "ಹಿಂದಿನಂತೆ ಮಾಡು";
messages["UNNAMED_KEY"] = "ಹೆಸರಿಡದ";
messages["VARIABLES_DEFAULT_NAME"] = "ಅಂಶ";
messages["VARIABLES_GET_CREATE_SET"] = "'%1 ಬದಲಿಸಿ'  ರಚಿಸಿ";
messages["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
messages["VARIABLES_GET_TOOLTIP"] = "ಈ ಚರಾಂಶದ ಮೌಲ್ಯವನ್ನು ಹಿಂತಿರುಗಿಸುತ್ತದೆ.";
messages["VARIABLES_SET"] = "%1 ನ್ನು %2 ಕ್ಕೆ ಬದಲಿಸಿ";
messages["VARIABLES_SET_CREATE_GET"] = "'%1 ಪಡೆಯಿರಿ' ರಚಿಸಿ";
messages["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
messages["VARIABLES_SET_TOOLTIP"] = "ಈ ಚರಾಂಶವನ್ನು  ಸೇರಿಸುವ ಅಂಶಕ್ಕೆ ಸಮಾನವಾಗಿ ಬದಲಿಸುತ್ತದೆ.";
messages["VARIABLE_ALREADY_EXISTS"] = "'%1' ಹೆಸರಿನ ಚರಾಂಶ ಈಗಾಗಲೇ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ.";
messages["VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE"] = "%1' ಹೆಸರಿನ ಚರಾಂಶ ಈಗಾಗಲೇ  '%2' ಡೇಟಾ ಪ್ರಕಾರದಲ್ಲಿ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ.";
messages["WORKSPACE_ARIA_LABEL"] = "ಬ್ಲಾಕ್ಲಿ ಕಾರ್ಯಕ್ಷೇತ್ರ";
messages["WORKSPACE_COMMENT_DEFAULT_TEXT"] = "ಏನಾದರು ಹೇಳಿ...";
messages["CONTROLS_FOREACH_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_FOR_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = messages["CONTROLS_IF_MSG_ELSEIF"];
messages["CONTROLS_IF_ELSE_TITLE_ELSE"] = messages["CONTROLS_IF_MSG_ELSE"];
messages["CONTROLS_IF_IF_TITLE_IF"] = messages["CONTROLS_IF_MSG_IF"];
messages["CONTROLS_IF_MSG_THEN"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["CONTROLS_WHILEUNTIL_INPUT_DO"] = messages["CONTROLS_REPEAT_INPUT_DO"];
messages["LISTS_CREATE_WITH_ITEM_TITLE"] = messages["VARIABLES_DEFAULT_NAME"];
messages["LISTS_GET_INDEX_HELPURL"] = messages["LISTS_INDEX_OF_HELPURL"];
messages["LISTS_GET_INDEX_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_GET_SUBLIST_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_INDEX_OF_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["LISTS_SET_INDEX_INPUT_IN_LIST"] = messages["LISTS_INLIST"];
messages["MATH_CHANGE_TITLE_ITEM"] = messages["VARIABLES_DEFAULT_NAME"];
messages["PROCEDURES_DEFRETURN_COMMENT"] = messages["PROCEDURES_DEFNORETURN_COMMENT"];
messages["PROCEDURES_DEFRETURN_DO"] = messages["PROCEDURES_DEFNORETURN_DO"];
messages["PROCEDURES_DEFRETURN_PROCEDURE"] = messages["PROCEDURES_DEFNORETURN_PROCEDURE"];
messages["PROCEDURES_DEFRETURN_TITLE"] = messages["PROCEDURES_DEFNORETURN_TITLE"];
messages["TEXT_APPEND_VARIABLE"] = messages["VARIABLES_DEFAULT_NAME"];
messages["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = messages["VARIABLES_DEFAULT_NAME"];

messages["MATH_HUE"] = "230";
messages["LOOPS_HUE"] = "120";
messages["LISTS_HUE"] = "260";
messages["LOGIC_HUE"] = "210";
messages["VARIABLES_HUE"] = "330";
messages["TEXTS_HUE"] = "160";
messages["PROCEDURES_HUE"] = "290";
messages["COLOUR_HUE"] = "20";
messages["VARIABLES_DYNAMIC_HUE"] = "310";