// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.sr.latn');

goog.require('Blockly.Msg');

/** @export */ Blockly.Msg.ADD_COMMENT = "Dodaj komentar";
/** @export */ Blockly.Msg.CANNOT_DELETE_VARIABLE_PROCEDURE = "Ne mogu da obrišem varijablu ’%1’ jer je deo definicije funkcije ’%2’";
/** @export */ Blockly.Msg.CHANGE_VALUE_TITLE = "Promeni vrednost:";
/** @export */ Blockly.Msg.CLEAN_UP = "Ukloni blokove";
/** @export */ Blockly.Msg.COLLAPSE_ALL = "Skupi blokove";
/** @export */ Blockly.Msg.COLLAPSE_BLOCK = "Skupi blok";
/** @export */ Blockly.Msg.COLOUR_BLEND_COLOUR1 = "boja 1";
/** @export */ Blockly.Msg.COLOUR_BLEND_COLOUR2 = "boja 2";
/** @export */ Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";
/** @export */ Blockly.Msg.COLOUR_BLEND_RATIO = "odnos";
/** @export */ Blockly.Msg.COLOUR_BLEND_TITLE = "pomešaj";
/** @export */ Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Pomešati dve boje zajedno sa datim odnosom (0.0 - 1.0).";
/** @export */ Blockly.Msg.COLOUR_PICKER_HELPURL = "https://sr.wikipedia.org/wiki/Boja";
/** @export */ Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Izaberite boju sa palete.";
/** @export */ Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
/** @export */ Blockly.Msg.COLOUR_RANDOM_TITLE = "slučajna boja";
/** @export */ Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Izaberite boju nasumice.";
/** @export */ Blockly.Msg.COLOUR_RGB_BLUE = "plava";
/** @export */ Blockly.Msg.COLOUR_RGB_GREEN = "zelena";
/** @export */ Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";
/** @export */ Blockly.Msg.COLOUR_RGB_RED = "crvena";
/** @export */ Blockly.Msg.COLOUR_RGB_TITLE = "boja sa";
/** @export */ Blockly.Msg.COLOUR_RGB_TOOLTIP = "Kreiraj boju sa određenom količinom crvene,zelene, i plave. Sve vrednosti moraju biti između 0 i 100.";
/** @export */ Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
/** @export */ Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "Izađite iz petlje";
/** @export */ Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "nastavi sa sledećom iteracijom petlje";
/** @export */ Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Napusti sadržaj petlje.";
/** @export */ Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Preskoči ostatak ove petlje, i nastavi sa sledećom iteracijom(ponavljanjem).";
/** @export */ Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Upozorenje: Ovaj blok može da se upotrebi samo unutar petlje.";
/** @export */ Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
/** @export */ Blockly.Msg.CONTROLS_FOREACH_TITLE = "za svaku stavku %1 na spisku %2";
/** @export */ Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "Za svaku stavku unutar liste, podesi promenjivu '%1' po stavci, i onda načini neke izjave-naredbe.";
/** @export */ Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
/** @export */ Blockly.Msg.CONTROLS_FOR_TITLE = "prebroj sa %1 od %2 do %3 od %4";
/** @export */ Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Imaj promenjivu \"%1\" uzmi vrednosti od početnog broja do zadnjeg broja, brojeći po određenom intervalu, i izvrši određene blokove.";
/** @export */ Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Dodajte uslov bloku „ako“.";
/** @export */ Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Dodaj konačni, catch-all  (uhvati sve) uslove if bloka.";
/** @export */ Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
/** @export */ Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Dodaj, ukloni, ili preuredi delove kako bih rekonfigurisali ovaj if blok.";
/** @export */ Blockly.Msg.CONTROLS_IF_MSG_ELSE = "inače";
/** @export */ Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "inače-ako";
/** @export */ Blockly.Msg.CONTROLS_IF_MSG_IF = "ako";
/** @export */ Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "ako je vrednost tačna, onda izvrši neke naredbe-izjave.";
/** @export */ Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "ako je vrednost tačna, onda izvrši prvi blok naredbi, U suprotnom, izvrši drugi blok naredbi.";
/** @export */ Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Ako je prva vrednost tačna, onda izvrši prvi blok naredbi, u suprotnom, ako je druga vrednost tačna , izvrši drugi blok naredbi.";
/** @export */ Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Ako je prva vrednost tačna, onda izvrši prvi blok naredbi, u suprotnom, ako je druga vrednost tačna , izvrši drugi blok naredbi. Ako ni jedna od vrednosti nije tačna, izvrši poslednji blok naredbi.";
/** @export */ Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://sr.wikipedia.org/wiki/For_petlja";
/** @export */ Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "izvrši";
/** @export */ Blockly.Msg.CONTROLS_REPEAT_TITLE = "ponovi %1 puta";
/** @export */ Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Odraditi neke naredbe nekoliko puta.";
/** @export */ Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
/** @export */ Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "ponavljati do";
/** @export */ Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "ponavljati dok";
/** @export */ Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Dok vrednost nije tačna, onda izvršiti neke naredbe.";
/** @export */ Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Dok je vrednost tačna, onda izvršite neke naredbe.";
/** @export */ Blockly.Msg.DELETE_ALL_BLOCKS = "Da obrišem svih %1 blokova?";
/** @export */ Blockly.Msg.DELETE_BLOCK = "Obriši blok";
/** @export */ Blockly.Msg.DELETE_VARIABLE = "Obriši promenljivu '%1'";
/** @export */ Blockly.Msg.DELETE_VARIABLE_CONFIRMATION = "Da obrišem %1 upotreba promenljive '%2'?";
/** @export */ Blockly.Msg.DELETE_X_BLOCKS = "Obriši %1 blokova";
/** @export */ Blockly.Msg.DISABLE_BLOCK = "Onemogući blok";
/** @export */ Blockly.Msg.DUPLICATE_BLOCK = "Dupliraj";
/** @export */ Blockly.Msg.ENABLE_BLOCK = "Omogući blok";
/** @export */ Blockly.Msg.EXPAND_ALL = "Proširi blokove";
/** @export */ Blockly.Msg.EXPAND_BLOCK = "Proširi blok";
/** @export */ Blockly.Msg.EXTERNAL_INPUTS = "Spoljni ulazi";
/** @export */ Blockly.Msg.HELP = "Pomoć";
/** @export */ Blockly.Msg.INLINE_INPUTS = "Unutrašnji ulazi";
/** @export */ Blockly.Msg.IOS_CANCEL = "Otkaži";
/** @export */ Blockly.Msg.IOS_ERROR = "Greška";
/** @export */ Blockly.Msg.IOS_OK = "U redu";
/** @export */ Blockly.Msg.IOS_PROCEDURES_ADD_INPUT = "+ Dodaj unos";
/** @export */ Blockly.Msg.IOS_PROCEDURES_ALLOW_STATEMENTS = "Dozvoli izjave";
/** @export */ Blockly.Msg.IOS_PROCEDURES_DUPLICATE_INPUTS_ERROR = "Ova funkcija ima duplicirane unose.";
/** @export */ Blockly.Msg.IOS_PROCEDURES_INPUTS = "UNOSI";
/** @export */ Blockly.Msg.IOS_VARIABLES_ADD_BUTTON = "Dodaj";
/** @export */ Blockly.Msg.IOS_VARIABLES_ADD_VARIABLE = "+ Dodaj varijablu";
/** @export */ Blockly.Msg.IOS_VARIABLES_DELETE_BUTTON = "Obriši";
/** @export */ Blockly.Msg.IOS_VARIABLES_EMPTY_NAME_ERROR = "Ne možete da koristite prazno ime varijable.";
/** @export */ Blockly.Msg.IOS_VARIABLES_RENAME_BUTTON = "Preimenuj";
/** @export */ Blockly.Msg.IOS_VARIABLES_VARIABLE_NAME = "Ime varijable";
/** @export */ Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";
/** @export */ Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "napravi prazan spisak";
/** @export */ Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "vraća listu, dužine 0, ne sadržavajući  evidenciju podataka";
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "spisak";
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Dodajte, izbrišite, ili preuredite delove kako bi se reorganizovali ovaj blok liste.";
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "napravi spisak sa";
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Dodajte stavku na spisak.";
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Kreiraj listu sa bilo kojim brojem stavki.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_FIRST = "prva";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_FROM_END = "# sa kraja";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_GET = "preuzmi";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "preuzmi i ukloni";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_LAST = "poslednja";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_RANDOM = "slučajna";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_REMOVE = "ukloni";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Vraća prvu stavku na spisku.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM = "Vraća stavku na određenu poziciju na listi.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Vraća poslednju stavku na spisku.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Vraća slučajnu stavku sa spiska.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Uklanja i vraća prvu stavku sa spiska.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM = "Uklanja i vraća stavku sa određenog položaja na spisku.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Uklanja i vraća poslednju stavku sa spiska.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Uklanja i vraća slučajnu stavku sa spiska.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Uklanja prvu stavku sa spiska.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM = "Uklanja stavku sa određenog položaja na spisku.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Uklanja poslednju stavku sa spiska.";
/** @export */ Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Uklanja slučajnu stavku sa spiska.";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "do # od kraja";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "do #";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "do poslednje";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "preuzmi podspisak od prve";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "preuzmi podspisak iz # sa kraja";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "preuzmi podspisak od #";
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Pravi kopiju određenog dela liste.";
/** @export */ Blockly.Msg.LISTS_INDEX_FROM_END_TOOLTIP = "%1 je poslednja stavka.";
/** @export */ Blockly.Msg.LISTS_INDEX_FROM_START_TOOLTIP = "%1 je prva stavka.";
/** @export */ Blockly.Msg.LISTS_INDEX_OF_FIRST = "pronađi prvo pojavljivanje stavke";
/** @export */ Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
/** @export */ Blockly.Msg.LISTS_INDEX_OF_LAST = "pronađi poslednje pojavljivanje stavke";
/** @export */ Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Vraća broj prvog i/poslednjeg ulaska elementa u listu. Vraća %1 Ako element nije pronađen.";
/** @export */ Blockly.Msg.LISTS_INLIST = "na spisku";
/** @export */ Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
/** @export */ Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 je prazan";
/** @export */ Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "Vraća vrednost tačno ako je lista prazna.";
/** @export */ Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
/** @export */ Blockly.Msg.LISTS_LENGTH_TITLE = "dužina spiska %1";
/** @export */ Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Vraća dužinu spiska.";
/** @export */ Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
/** @export */ Blockly.Msg.LISTS_REPEAT_TITLE = "Napraviti listu sa stavkom %1 koja se ponavlja %2 puta";
/** @export */ Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Pravi listu koja se sastoji od zadane vrednosti koju ponavljamo određeni broj šuta.";
/** @export */ Blockly.Msg.LISTS_REVERSE_HELPURL = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";
/** @export */ Blockly.Msg.LISTS_REVERSE_MESSAGE0 = "obrnuto %1";
/** @export */ Blockly.Msg.LISTS_REVERSE_TOOLTIP = "Obrni kopiju spiska.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
/** @export */ Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "kao";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_INSERT = "ubaci na";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_SET = "postavi";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Ubacuje stavku na početak spiska.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM = "Ubacuje stavku na određeni položaj na spisku.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Dodajte stavku na kraj spiska.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Ubacuje stavku na slučajno mesto na spisku.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Postavlja prvu stavku na spisku.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM = "Postavlja stavku na određeni položaj na spisku.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Postavlja poslednju stavku na spisku.";
/** @export */ Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Postavlja slučajnu stavku na spisku.";
/** @export */ Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
/** @export */ Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "rastuće";
/** @export */ Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "opadajuće";
/** @export */ Blockly.Msg.LISTS_SORT_TITLE = "sortiraj %1 %2 %3";
/** @export */ Blockly.Msg.LISTS_SORT_TOOLTIP = "Sortirajte kopiju spiska.";
/** @export */ Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "azbučno, ignoriši mala i velika slova";
/** @export */ Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "kao brojeve";
/** @export */ Blockly.Msg.LISTS_SORT_TYPE_TEXT = "azbučno";
/** @export */ Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
/** @export */ Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "napravite listu sa teksta";
/** @export */ Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "da tekst iz liste";
/** @export */ Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Da se pridruži listu tekstova u jedan tekst, podeljenih za razdvajanje.";
/** @export */ Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Podeliti tekst u listu tekstova, razbijanje na svakom graničnik.";
/** @export */ Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "sa razdvajanje";
/** @export */ Blockly.Msg.LOGIC_BOOLEAN_FALSE = "netačno";
/** @export */ Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
/** @export */ Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Vraća ili tačno ili netačno.";
/** @export */ Blockly.Msg.LOGIC_BOOLEAN_TRUE = "tačno";
/** @export */ Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://sr.wikipedia.org/wiki/Nejednakost";
/** @export */ Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Vraća vrednost „tačno“ ako su oba ulaza jednaka.";
/** @export */ Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Vraća vrednost „tačno“ ako je prvi ulaz veći od drugog.";
/** @export */ Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Vraća vrednost „tačno“ ako je prvi ulaz veći ili jednak drugom.";
/** @export */ Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Vraća vrednost „tačno“ ako je prvi ulaz manji od drugog.";
/** @export */ Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Vraća vrednost „tačno“ ako je prvi ulaz manji ili jednak drugom.";
/** @export */ Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Vraća vrednost „tačno“ ako su oba ulaza nejednaka.";
/** @export */ Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
/** @export */ Blockly.Msg.LOGIC_NEGATE_TITLE = "nije %1";
/** @export */ Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Vraća vrednost „tačno“ ako je ulaz netačan. Vraća vrednost „netačno“ ako je ulaz tačan.";
/** @export */ Blockly.Msg.LOGIC_NULL = "bez vrednosti";
/** @export */ Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";
/** @export */ Blockly.Msg.LOGIC_NULL_TOOLTIP = "Vraća „bez vrednosti“.";
/** @export */ Blockly.Msg.LOGIC_OPERATION_AND = "i";
/** @export */ Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
/** @export */ Blockly.Msg.LOGIC_OPERATION_OR = "ili";
/** @export */ Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Vraća vrednost „tačno“ ako su oba ulaza tačna.";
/** @export */ Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Vraća vrednost „tačno“ ako je bar jedan od ulaza tačan.";
/** @export */ Blockly.Msg.LOGIC_TERNARY_CONDITION = "proba";
/** @export */ Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";
/** @export */ Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "ako je netačno";
/** @export */ Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "ako je tačno";
/** @export */ Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Proveri uslov u 'test'. Ako je uslov tačan, tada vraća 'if true' vrednost; u drugom slučaju vraća 'if false' vrednost.";
/** @export */ Blockly.Msg.MATH_ADDITION_SYMBOL = "+";
/** @export */ Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://en.wikipedia.org/wiki/Arithmetic";
/** @export */ Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Vratite zbir dva broja.";
/** @export */ Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Vraća količnik dva broja.";
/** @export */ Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Vraća razliku dva broja.";
/** @export */ Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Vraća proizvod dva broja.";
/** @export */ Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Vraća prvi broj stepenovan drugim.";
/** @export */ Blockly.Msg.MATH_CHANGE_HELPURL = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
/** @export */ Blockly.Msg.MATH_CHANGE_TITLE = "promeni %1 za %2";
/** @export */ Blockly.Msg.MATH_CHANGE_TOOLTIP = "Dodajte broj promenljivoj „%1“.";
/** @export */ Blockly.Msg.MATH_CONSTANT_HELPURL = "https://sr.wikipedia.org/wiki/Matematička_konstanta";
/** @export */ Blockly.Msg.MATH_CONSTANT_TOOLTIP = "vrati jednu od zajedničkih konstanti: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), ili ∞ (infinity).";
/** @export */ Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
/** @export */ Blockly.Msg.MATH_CONSTRAIN_TITLE = "ograniči %1 nisko %2 visoko %3";
/** @export */ Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Ograničava broj na donje i gornje granice (uključivo).";
/** @export */ Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";
/** @export */ Blockly.Msg.MATH_IS_DIVISIBLE_BY = "je deljiv sa";
/** @export */ Blockly.Msg.MATH_IS_EVEN = "je paran";
/** @export */ Blockly.Msg.MATH_IS_NEGATIVE = "je negativan";
/** @export */ Blockly.Msg.MATH_IS_ODD = "je neparan";
/** @export */ Blockly.Msg.MATH_IS_POSITIVE = "je pozitivan";
/** @export */ Blockly.Msg.MATH_IS_PRIME = "je prost";
/** @export */ Blockly.Msg.MATH_IS_TOOLTIP = "Provjerava da li je broj paran, neparan, prost, cio, pozitivan, negativan, ili da li je deljiv sa određenim brojem. Vraća tačno ili netačno.";
/** @export */ Blockly.Msg.MATH_IS_WHOLE = "je ceo";
/** @export */ Blockly.Msg.MATH_MODULO_HELPURL = "https://sr.wikipedia.org/wiki/Kongruencija";
/** @export */ Blockly.Msg.MATH_MODULO_TITLE = "podsetnik od %1 ÷ %2";
/** @export */ Blockly.Msg.MATH_MODULO_TOOLTIP = "Vraća podsetnik od deljenja dva broja.";
/** @export */ Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";
/** @export */ Blockly.Msg.MATH_NUMBER_HELPURL = "https://en.wikipedia.org/wiki/Number";
/** @export */ Blockly.Msg.MATH_NUMBER_TOOLTIP = "Neki broj.";
/** @export */ Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "prosek spiska";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "maks. spiska";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "medijana spiska";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "min. spiska";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "modus spiska";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "slučajna stavka spiska";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "standardna devijacija spiska";
/** @export */ Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "zbir spiska";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Vraća prosek numeričkih vrednosti sa spiska.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Vraća najveći broj sa spiska.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Vraća medijanu sa spiska.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Vraća najmanji broj sa spiska.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Vraća najčešće stavke sa spiska.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Vraća slučajni element sa spiska.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Vraća standardnu devijaciju spiska.";
/** @export */ Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Vraća zbir svih brojeva sa spiska.";
/** @export */ Blockly.Msg.MATH_POWER_SYMBOL = "^";
/** @export */ Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://sr.wikipedia.org/wiki/Generator_slučajnih_brojeva";
/** @export */ Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "slučajni razlomak";
/** @export */ Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Vraća slučajni razlomak između 0.0 (uključivo) i 1.0 (isključivo).";
/** @export */ Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://sr.wikipedia.org/wiki/Generator_slučajnih_brojeva";
/** @export */ Blockly.Msg.MATH_RANDOM_INT_TITLE = "sličajno odabrani cijeli broj od %1 do %2";
/** @export */ Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Vraća slučajno odabrani celi broj između dve određene granice, uključivo.";
/** @export */ Blockly.Msg.MATH_ROUND_HELPURL = "https://sr.wikipedia.org/wiki/Zaokruživanje";
/** @export */ Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "zaokruži";
/** @export */ Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "zaokruži naniže";
/** @export */ Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "zaokruži naviše";
/** @export */ Blockly.Msg.MATH_ROUND_TOOLTIP = "Zaokružite broj na veću ili manju vrednost.";
/** @export */ Blockly.Msg.MATH_SINGLE_HELPURL = "https://sr.wikipedia.org/wiki/Kvadratni_koren";
/** @export */ Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "apsolutan";
/** @export */ Blockly.Msg.MATH_SINGLE_OP_ROOT = "kvadratni koren";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Vraća apsolutnu vrednost broja.";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "vratiti e na vlasti broja.";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Vraća prirodni logaritam broja.";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Vraća logaritam broja sa osnovom 10.";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Vraća negaciju broja.";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Vraća 10-ti stepen broja.";
/** @export */ Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Vraća kvadratni koren broja.";
/** @export */ Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";
/** @export */ Blockly.Msg.MATH_TRIG_ACOS = "arc cos";
/** @export */ Blockly.Msg.MATH_TRIG_ASIN = "arc sin";
/** @export */ Blockly.Msg.MATH_TRIG_ATAN = "arc tan";
/** @export */ Blockly.Msg.MATH_TRIG_COS = "cos";
/** @export */ Blockly.Msg.MATH_TRIG_HELPURL = "https://sr.wikipedia.org/wiki/Trigonometrijske_funkcije";
/** @export */ Blockly.Msg.MATH_TRIG_SIN = "sin";
/** @export */ Blockly.Msg.MATH_TRIG_TAN = "tan";
/** @export */ Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Vraća arkus kosinus broja.";
/** @export */ Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Vraća arkus broja.";
/** @export */ Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Vraća arkus tangens broja.";
/** @export */ Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Vraća kosinus stepena (ne radijan).";
/** @export */ Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Vraća sinus stepena (ne radijan).";
/** @export */ Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Vraća tangens stepena (ne radijan).";
/** @export */ Blockly.Msg.NEW_COLOUR_VARIABLE = "Create colour variable...";  // untranslated
/** @export */ Blockly.Msg.NEW_NUMBER_VARIABLE = "Create number variable...";  // untranslated
/** @export */ Blockly.Msg.NEW_STRING_VARIABLE = "Create string variable...";  // untranslated
/** @export */ Blockly.Msg.NEW_VARIABLE = "Napravi promenljivu…";
/** @export */ Blockly.Msg.NEW_VARIABLE_TITLE = "Ime nove promenljive:";
/** @export */ Blockly.Msg.NEW_VARIABLE_TYPE_TITLE = "New variable type:";  // untranslated
/** @export */ Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
/** @export */ Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "dozvoliti izreke";
/** @export */ Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "sa:";
/** @export */ Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";
/** @export */ Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Pokrenite prilagođenu funkciju „%1“.";
/** @export */ Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";
/** @export */ Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Pokrenite prilagođenu funkciju „%1“ i koristi njen izlaz.";
/** @export */ Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "sa:";
/** @export */ Blockly.Msg.PROCEDURES_CREATE_DO = "Napravi „%1“";
/** @export */ Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "Opisati ovu funkciju...";
/** @export */ Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
/** @export */ Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
/** @export */ Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "uradite nešto";
/** @export */ Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "da";
/** @export */ Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Pravi funkciju bez izlaza.";
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "vrati";
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Pravi funkciju sa izlazom.";
/** @export */ Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Upozorenje: Ova funkcija ima duplikate parametara.";
/** @export */ Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Istakni definiciju funkcije";
/** @export */ Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";  // untranslated
/** @export */ Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "Ukoliko je vrednost tačna, vrati drugu vrednost.";
/** @export */ Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Upozorenje: Ovaj blok se može koristiti jedino u definiciji funkcije.";
/** @export */ Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "naziv ulaza:";
/** @export */ Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Dodajte ulazna funkcija.";
/** @export */ Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "ulazi";
/** @export */ Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Da dodate, uklonite ili pereuporяdočitь ulaza za ovu funkciju.";
/** @export */ Blockly.Msg.REDO = "Ponovi";
/** @export */ Blockly.Msg.REMOVE_COMMENT = "Ukloni komentar";
/** @export */ Blockly.Msg.RENAME_VARIABLE = "Preimenuj promenljivu…";
/** @export */ Blockly.Msg.RENAME_VARIABLE_TITLE = "Preimenuj sve „%1“ promenljive u:";
/** @export */ Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
/** @export */ Blockly.Msg.TEXT_APPEND_TITLE = "na %1 dodaj tekst %2";
/** @export */ Blockly.Msg.TEXT_APPEND_TOOLTIP = "Dodajte tekst na promenljivu „%1“.";
/** @export */ Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
/** @export */ Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "malim slovima";
/** @export */ Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "svaka reč velikim slovom";
/** @export */ Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "velikim slovima";
/** @export */ Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Vraća primerak teksta sa drugačijom veličinom slova.";
/** @export */ Blockly.Msg.TEXT_CHARAT_FIRST = "preuzmi prvo slovo";
/** @export */ Blockly.Msg.TEXT_CHARAT_FROM_END = "preuzmi slovo # sa kraja";
/** @export */ Blockly.Msg.TEXT_CHARAT_FROM_START = "preuzmi slovo #";
/** @export */ Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
/** @export */ Blockly.Msg.TEXT_CHARAT_LAST = "preuzmi poslednje slovo";
/** @export */ Blockly.Msg.TEXT_CHARAT_RANDOM = "preuzmi slučajno slovo";
/** @export */ Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
/** @export */ Blockly.Msg.TEXT_CHARAT_TITLE = "u tekstu %1 %2";
/** @export */ Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Vraća slovo na određeni položaj.";
/** @export */ Blockly.Msg.TEXT_COUNT_HELPURL = "https://github.com/google/blockly/wiki/Text#counting-substrings";
/** @export */ Blockly.Msg.TEXT_COUNT_MESSAGE0 = "broj %1 u %2";
/** @export */ Blockly.Msg.TEXT_COUNT_TOOLTIP = "Broji koliko puta se neki tekst pojavljuje unutar nekog drugog teksta.";
/** @export */ Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "Dodajte stavku u tekst.";
/** @export */ Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "spajanjem";
/** @export */ Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Dodaj, ukloni, ili drugačije poredaj odjelke kako bi iznova postavili ovaj tekst blok.";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "slovu # sa kraja";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "slovu #";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "poslednjem slovu";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "u tekstu";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "preuzmi podnisku iz prvog slova";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "preuzmi podnisku iz slova # sa kraja";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "preuzmi podnisku iz slova #";
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
/** @export */ Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Vraća određeni deo teksta.";
/** @export */ Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
/** @export */ Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "pronađi prvo pojavljivanje teksta";
/** @export */ Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "pronađi poslednje pojavljivanje teksta";
/** @export */ Blockly.Msg.TEXT_INDEXOF_TITLE = "u tekstu %1 %2 %3";
/** @export */ Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Vraća odnos prvog/zadnjeg pojavljivanja teksta u drugom tekstu. Vrađa %1 ako tekst nije pronađen.";
/** @export */ Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
/** @export */ Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 je prazan";
/** @export */ Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Vraća tačno ako je dostavljeni tekst prazan.";
/** @export */ Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
/** @export */ Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "napiši tekst sa";
/** @export */ Blockly.Msg.TEXT_JOIN_TOOLTIP = "Napraviti dio teksta spajajući različite stavke.";
/** @export */ Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
/** @export */ Blockly.Msg.TEXT_LENGTH_TITLE = "dužina teksta %1";
/** @export */ Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Vraća broj slova (uključujući razmake) u datom tekstu.";
/** @export */ Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
/** @export */ Blockly.Msg.TEXT_PRINT_TITLE = "prikaži %1";
/** @export */ Blockly.Msg.TEXT_PRINT_TOOLTIP = "Prikažite određeni tekst, broj ili drugu vrednost na ekranu.";
/** @export */ Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
/** @export */ Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Pitajte korisnika za broj.";
/** @export */ Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Pitajte korisnika za unos teksta.";
/** @export */ Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "pitaj za broj sa porukom";
/** @export */ Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "pitaj za tekst sa porukom";
/** @export */ Blockly.Msg.TEXT_REPLACE_HELPURL = "https://github.com/google/blockly/wiki/Text#replacing-substrings";
/** @export */ Blockly.Msg.TEXT_REPLACE_MESSAGE0 = "zamena %1 sa %2 u %3";
/** @export */ Blockly.Msg.TEXT_REPLACE_TOOLTIP = "Zamena svih pojava nekog teksta unutar nekog drugog teksta.";
/** @export */ Blockly.Msg.TEXT_REVERSE_HELPURL = "https://github.com/google/blockly/wiki/Text#reversing-text";
/** @export */ Blockly.Msg.TEXT_REVERSE_MESSAGE0 = "obrnuto %1";
/** @export */ Blockly.Msg.TEXT_REVERSE_TOOLTIP = "Obrće redosled karaktera u tekstu.";
/** @export */ Blockly.Msg.TEXT_TEXT_HELPURL = "https://sr.wikipedia.org/wiki/Niska";
/** @export */ Blockly.Msg.TEXT_TEXT_TOOLTIP = "Slovo, reč ili red teksta.";
/** @export */ Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
/** @export */ Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "trim praznine sa obe strane";
/** @export */ Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "skratiti prostor sa leve strane";
/** @export */ Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "skratiti prostor sa desne strane";
/** @export */ Blockly.Msg.TEXT_TRIM_TOOLTIP = "Vraća kopiju teksta sa uklonjenim prostorom sa jednog od dva kraja.";
/** @export */ Blockly.Msg.TODAY = "Danas";
/** @export */ Blockly.Msg.UNDO = "Opozovi";
/** @export */ Blockly.Msg.VARIABLES_DEFAULT_NAME = "stavka";
/** @export */ Blockly.Msg.VARIABLES_GET_CREATE_SET = "Napravi „postavi %1“";
/** @export */ Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
/** @export */ Blockly.Msg.VARIABLES_GET_TOOLTIP = "Vraća vrednost ove promenljive.";
/** @export */ Blockly.Msg.VARIABLES_SET = "postavi %1 u %2";
/** @export */ Blockly.Msg.VARIABLES_SET_CREATE_GET = "Napravi „preuzmi %1“";
/** @export */ Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
/** @export */ Blockly.Msg.VARIABLES_SET_TOOLTIP = "Postavlja promenljivu tako da bude jednaka ulazu.";
/** @export */ Blockly.Msg.VARIABLE_ALREADY_EXISTS = "Promenljiva pod imenom '%1' već postoji.";
/** @export */ Blockly.Msg.VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE = "Varijabla po imenu '%1' već postoji za drugu varijablu tipa '%2'.";
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
/** @export */ Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
/** @export */ Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
/** @export */ Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
/** @export */ Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
/** @export */ Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
/** @export */ Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
/** @export */ Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
/** @export */ Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
/** @export */ Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
/** @export */ Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
/** @export */ Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
/** @export */ Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
/** @export */ Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
/** @export */ Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
/** @export */ Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
/** @export */ Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
/** @export */ Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;

/** @export */ Blockly.Msg.MATH_HUE = "230";
/** @export */ Blockly.Msg.LOOPS_HUE = "120";
/** @export */ Blockly.Msg.LISTS_HUE = "260";
/** @export */ Blockly.Msg.LOGIC_HUE = "210";
/** @export */ Blockly.Msg.VARIABLES_HUE = "330";
/** @export */ Blockly.Msg.TEXTS_HUE = "160";
/** @export */ Blockly.Msg.PROCEDURES_HUE = "290";
/** @export */ Blockly.Msg.COLOUR_HUE = "20";
/** @export */ Blockly.Msg.VARIABLES_DYNAMIC_HUE = "310";