var MSG = {
  title: "Código",
  blocks: "Bloques",
  linkTooltip: "Gardar e crear unha ligazón aos bloques.",
  runTooltip: "Executar o programa definido polos bloques no espazo de traballo.",
  badCode: "Erro do programa:\n%1",
  timeout: "Superouse o número máximo de iteracións durante a execución.",
  discard: "Queres borrar os %1 bloques?",
  trashTooltip: "Descartar todos os bloques.",
  catLogic: "Lóxica",
  catLoops: "Bucles",
  catMath: "Matemáticas",
  catText: "Texto",
  catLists: "Listas",
  catColour: "Cor",
  catVariables: "Variables",
  catFunctions: "Funcións",
  listVariable: "lista",
  textVariable: "texto",
  httpRequestError: "Houbo un problema coa solicitude.",
  linkAlert: "Comparte os teus bloques con esta ligazón:\n\n%1",
  hashError: "Sentímolo, \"%1\" non se corresponde con ningún programa gardado.",
  xmlError: "Non se puido cargar o ficheiro gardado. Se cadra, foi creado cunha versión diferente de Blockly.",
  badXml: "Erro de análise do XML:\n%1\n\nSelecciona \"Aceptar\" se queres anular os cambios ou \"Cancelar\" para seguir editando o XML."
};
