var MSG = {
  title: "Kod",
  blocks: " Blokovi",
  linkTooltip: "Spremi i napravi poveznicu na program..",
  runTooltip: "Pokreni program zadan blokovima u radnom prostoru.",
  badCode: "Greška u programu:\n%1",
  timeout: "Maksimalni broj iteracija je prekoračen.",
  trashTooltip: " Izbriši sve blokove.",
  catLogic: "Logika",
  catLoops: "Petlje",
  catMath: "Matematika",
  catText: "Tekst",
  catLists: "Liste",
  catColour: "Boja",
  catVariables: "Varijable",
  catFunctions: "Funkcije",
  listVariable: "lista",
  textVariable: "tekst",
  httpRequestError: "Postoji problem sa zahtjevom.",
  linkAlert: "Podijelite svoj program javnom poveznicom. Obrisat ćemo ga nakon godinu dana ne korištenja. Program nije povezan s vašim korisničkim računom te je zaštićen Google\'s Privacy Policy. Molimo vas ne stavljajte u program nikakve osobne informacije .\n\n%1",
  hashError: "Žao nam je,  '%1' ne odgovara niti jednom spremljenom programu.",
  xmlError: "Ne možemo učitati vaš spremljen program. Možda je napravljen nekom drugom inačicom Blocklyja?",
  badXml: "Greška u parsiranju XML:\n%1\n\nOdaberite 'OK' kako biste odbacili promjene ili 'Odustani' za nastavak editiranja XML."
};
