var MSG = {
  title: "Kódszerkesztő",
  blocks: "Blokkok",
  linkTooltip: "Hivatkozás létrehozása",
  runTooltip: "Program futtatása.",
  badCode: "Program hiba:\n%1",
  timeout: "A program elérte a maximális végrehajtási időt.",
  trashTooltip: "Összes blokk törlése.",
  catLogic: "Logikai műveletek",
  catLoops: "Ciklusok",
  catMath: "Matematikai műveletek",
  catText: "Sztring műveletek",
  catLists: "Listakezelés",
  catColour: "Színek",
  catVariables: "Változók",
  catFunctions: "Eljárások",
  listVariable: "lista",
  textVariable: "szöveg",
  httpRequestError: "A kéréssel kapcsolatban probléma merült fel.",
  linkAlert: "Ezzel a hivatkozással tudod megosztani a programodat:\n\n%1",
  hashError: "Sajnos a '%1' hivatkozás nem tartozik egyetlen programhoz sem.",
  loadError: "A programodat nem lehet betölteni.  Elképzelhető, hogy a Blockly egy másik verziójában készült?",
  parseError: "Hiba az %1 feldolgozásakor:\n%2\n\nVáltozások elvetése?"
};
