var MSG = {
  title: "Còdes",
  blocks: "Blòch",
  linkTooltip: "Argistré e lijé ai blòch.",
  runTooltip: "Fé andé ël programa definì dai blòch ant lë spassi ëd travaj.",
  badCode: "Eror dël programa:\n%1",
  timeout: "Nùmer màssim d'arpetission d'esecussion sorpassà.",
  trashTooltip: "Scarté tuti ij blòch.",
  catLogic: "Lògica",
  catLoops: "Liasse",
  catMath: "Matemàtica",
  catText: "Test",
  catLists: "Liste",
  catColour: "Color",
  catVariables: "Variàbij",
  catFunctions: "Fonsion",
  listVariable: "lista",
  textVariable: "test",
  httpRequestError: "A-i é staje un problema con l'arcesta.",
  linkAlert: "Ch'a partagia ij sò blòch grassie a sta liura: %1",
  hashError: "An dëspias, '%1 a corëspond a gnun programa salvà.",
  loadError: "A l'é nen podusse carié so archivi salvà. Miraco a l'é stàit creà con na version diferenta ëd Blockly?",
  parseError: "Eror d'anàlisi dl'%1:\n%2\n\nSelessioné 'Va bin' për lassé perde toe modìfiche o 'Anulé' për modifiché ancora l'%1."
};
