# This workflow will do a clean install, start the selenium server, and run
# all of our browser based tests

name: Run browser manually

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # TODO (#2114): re-enable osx build.
        # os: [ubuntu-latest, macos-latest]
        os: [macos-latest]
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at
        # https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm Install
        run: npm install

      - name: Linux Test Setup
        if: runner.os == 'Linux'
        run: source ./tests/scripts/setup_linux_env.sh

      - name: Run Build
        run: npm run build

      - name: Run Test
        run: npm run test:browser

        env:
          CI: true
