on:
  pull_request_target:
    types:
      - opened
      - edited
name: conventional-release-labels
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels:
            '{"feat": "PR: feature", "fix": "PR: fix", "breaking": "breaking
            change", "chore": "PR: chore", "docs": "PR: docs", "refactor": "PR:
            refactor", "revert": "PR: revert", "deprecate": "deprecation"}'
          ignored_types: '[]'
