on:
  pull_request_target:
    types:
      - opened
name: Welcome new contributors
jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: >
            Welcome! It looks like this is your first pull request in Blockly,
            so here are a couple of tips:

            - You can find tips about contributing to Blockly and how to
            validate your changes on our
            [developer site](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change).

            - All contributors must sign the Google Contributor License
            Agreement (CLA). If the google-cla bot leaves a comment on this
            PR, make sure you follow the instructions.

            - We use conventional commits to make versioning the package easier. Make sure your commit
            message is in the [proper format](https://developers.google.com/blockly/guides/contribute/get-started/commits)
            or [learn how to fix it](https://developers.google.com/blockly/guides/contribute/get-started/commits#fixing_non-conventional_commits).

            - If any of the other checks on this PR fail, you can click on
            them to learn why. It might be that your change caused a test
            failure, or that you need to double-check the
            [style guide](https://developers.google.com/blockly/guides/contribute/core/style_guide).

            Thank you for opening this PR! A member of the Blockly team will review it soon.
